### ISSUE TITLE
Externalized tikz in tabular breaks

### ISSUE THREAD

**Issue by t-wissmann** [latex3/hyperref#103]
Since hyperref v6.88h (more precisely since 148c34fd27da2c2fc609ef5f243dcf8ef5df24d8), the tikz externalize feature fails for `tikzpicture`s that are within a `tabular` environment. Take the following `file.tex`:
```tex
\documentclass{article}

% compile with:
%
%   pdflatex -shell-escape FILE.tex

% without hyperref, the following compiles fine; with or without -shell-escape
\usepackage{hyperref}

\usepackage{tikz}
\usetikzlibrary{external}
\tikzset{external/up to date check=diff}

% detect whether -shell-escape is passed or not to
% pdflatex, and only enable \tikzexternalize if -shell-escape
% has been passed.
\usepackage{pdftexcmds}
\usepackage{ifthen}
\makeatletter
\ifthenelse{\pdf@shellescape=1}{\tikzexternalize}{}
\makeatother

\begin{document}
% the following forces remake, to avoid accidental inclusion of a previoiusly successfully
% built picture
\tikzset{external/remake next}
\begin{tikzpicture}
\node {externalizing works in principle};
\end{tikzpicture}

\tikzset{external/remake next}
\begin{tabular}{l}
\begin{tikzpicture}
\node {but it fails within a tabular/array};
\end{tikzpicture}
\end{tabular}
\end{document}
```
With hyperref v6.88e, the above file compiles fine with `pdflatex -shell-escape`, but with hyperref v6.88h, the externalization of the first `tikzpicture` works fine, but the second fails:
```
===== 'mode=convert with system call': Invoking 'pdflatex -shell-escape -halt-o
n-error -interaction=batchmode -jobname "file-figure1" "\def\tikzexternalrealjo
b{file}\input{file}"' ========
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
system returned with code 256
```
and the log of `file-figure1` says:
```
[1

{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
! Missing \cr inserted.
<inserted text> 
                \cr 
l.36 \end{tabular}
                   
Here is how much of TeX's memory you used:
 15413 strings out of 492623
 299337 string characters out of 6135669
 359938 words of memory out of 5000000
 19106 multiletter control sequences out of 15000+600000
 3941 words of font info for 15 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 56i,14n,58p,572b,622s stack positions out of 5000i,500n,10000p,200000b,80000s

!  ==> Fatal error occurred, no output PDF file produced!
```
And in a much more complex tex document, the concrete error message is different, e.g.
```
{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}]
! Extra }, or forgotten \endgroup.
\endarray ->\crcr \egroup 
                          \egroup \@arrayright \gdef \@preamble {}
```

A git bisect shows that both issues are introduced by 148c34fd27da2c2fc609ef5f243dcf8ef5df24d8 so I hope the short MWE is enough to find the actual issue here.

**Comment by u-fischer** [comment]
Like always it is a good idea to load hyperref as late as possible. Move tikz before hyperref. 

(both tikz and hyperref are adding code to a shipout hook and hyperref's code doesn't like it to be in the middle of the tikz code).

**Comment by t-wissmann** [comment]
Oh... I was not aware of this.. If include tikz first, then the code is indeed compiling.

Is this still a bug? Sometimes I can't avoid that hyperref is loaded quite early (if I understand it correctly, the beamer class load hyperref per default, so I don't know how to avoid the issue there.)

**Comment by u-fischer** [comment]
As a workaround you can disable the code that makes the troubles with 

~~~~
\makeatletter
\def\Hy@DisableOption#1{}
~~~~

I'm not sure if one can call it a bug but I don't like it very much that hyperref tries to disable options in the middle of the shipout. As your example shows it is fragile.  In the long run I hope that pdf resources can be managed better, but for now we should perhaps revert the change made for issue #97, a missing warning is better than an error.  @davidcarlisle  what do you mean?

**Comment by u-fischer** [comment]
I reverted the change. This should resolve this issue with the next update.

**Comment by t-wissmann** [comment]
Thanks a lot! Regarding the workaround, it's already a workaround to move `\usepackage{tikz}` before `\usepackage{hyperref}`.

**Comment by muzimuzhi** [comment]
Maybe we need to add a `tikz`-related subsection under section 9.1 _Package Compatibility_ of user manual of hyperref.
