### ISSUE TITLE
crash interacting with \sb and \scriptsize

### ISSUE THREAD

**Issue by joeharr4** [latex3/hyperref#105]
Loading hyperref, defining a macro \sb that uses \scriptsize, and calling \url causes an infinite loop.  You do not actually have to use the \sb macro, just defining it breaks latex.  Here is a minimal example:

[sb-error3.tex.gz](https://github.com/latex3/hyperref/files/3692956/sb-error3.tex.gz)

Note that \sb is a standard math-mode macro that does subscripts.  I have a macro that generalizes it to do subscripts in either math or regular text (pre 1994!).  It cannot coexist with hyperref.  But, hyperref does not expose an \sb macro, nor can I find one in the hyperref code.

Thanks,

--jh--

**Comment by josephwright** [comment]
The `\sb` _is_ `_` in standard LaTeX: I think treating as a _macro_ is pretty risk. (It's from plain, where it was provided in case the keyboard didn't provide `_`). You don't need `hyperref` to get an issue
```latex
\documentclass{article}
\errorcontextlines=\maxdimen
\usepackage{url}

\def\sb#1{\scriptsize #1}

\begin{document}

\url{http://example.com}

\end{document}
```

**Comment by davidcarlisle** [comment]
Nice test file, thanks:-)

This is is actually url package not hyperref, your test file could be changed to

```
\documentclass{article}

\usepackage{url}

\def\sb#1{\scriptsize #1}

% \makeatletter
% \let\zzz_
% \def\set@mathnolig#1{\ifnum\mathcode`#1<32768
%    \begingroup\lccode`\~`#1\lowercase{\endgroup
%      \edef~}{\mathchar\number\mathcode`#1\zzz{\/}}%
%    \mathcode`#1=32768 \fi}
% \makeatother

\begin{document}

\url{http://example.com}

\end{document}

```

If you uncomment the commented code it should work again.

Arguably `\sb` is a "standard command" to access the original definition of `_` in case `_` has been redefined, which is the way it is being used by url, in which case it would be the responsibility of the code changing _ to make this safe, but in practice it would be easiest of url made a change here.

Actually a better fix, that doesn't assume `_` has its standard definition at the point url.sty is loaded is


{```
\catcode`\_=8
\gdef\set@mathnolig#1{\ifnum\mathcode`#1<32768
   \begingroup\lccode`\~`#1\lowercase{\endgroup
     \edef~}{\mathchar\number\mathcode`#1_{\/}}%
   \mathcode`#1=32768 \fi}
}


I'll ask Donald Arseneau if he wants to adjust url.sty here.
```

**Comment by davidcarlisle** [comment]
@josephwright  I see we came to the  same conclusion:-)

**Comment by davidcarlisle** [comment]
closing as not a hyperref issue.  (I have mailed Donald, to see if he wants to change url package)

**Comment by joeharr4** [comment]
Thank you both for such a quick and thorough response!

Why am I messing with \sb, you ask?  That's just the tip of the iceberg.  The underlying package, jokingly called joetex.tex, is an attempt to let TeX and LaTeX be used for ordinary documents, without having to backslash every symbol on the keyboard.  This is very useful for converting large documents from other sources, such as Word, emails, web pages, PDFs, etc.  Once you're at the point of doing typesetting in such documents, it replaces things like _x^y with \sbp{x}{y} and $x$ with \math{x}.  It lets you turn on and off the character unreservations with fine granularity, and to interpret commands in the normal environment on an as-needed basis.  I wrote it in the mid-1980s and have used it unchanged since 1994, even for scientific documents.  It broke for the first time on hyperlinks, when I belatedly started using them about five years ago.  I've finally gotten around to chasing the problem down, rather than avoiding/patching hyperlinking packages.

I think "joetex" is of general interest (with a better name), and your reply makes me think it can be done, perhaps easily, in a robust way.  It isn't long.  However, I am not nearly as TeX-savvy as I would need to be to do that and to maintain it in the age of modern TeX.  The code you sent was pretty much gibberish to me, and I'm not sure what it does.  Would either of you be willing to help me turn this into releasable code and get it contributed to the TeX community?  It's attached.  If you think it's viable, I'll open up a repo for it.  There's some support for non-special characters in ConTeXT, but I'm interested in TeX and LaTeX.  Perhaps there's something already, but a quick search didn't find it for me.

Thanks,

--jh--

[joe.tex.gz](https://github.com/latex3/hyperref/files/3693402/joe.tex.gz)
