### ISSUE TITLE
hyperref with dvipdfm and xr-hyper / referencing external label twice erroneously causes warnings

### ISSUE THREAD

**Issue by Ulrich-Diez** [latex3/hyperref#107]
<h2>Relevant files:</h2>

`hyperref.sty [2019/09/28 v7.00a Hypertext links for LaTeX]`  
`hdvipdfm.def [2019/09/28 v7.00a Hyperref driver for dvipdfm]`  
`hpdftex.def  [2019/09/28 v7.00a Hyperref driver for pdfTeX]`  
`xr-hyper.sty [2019/10/03 v6.1 eXternal References (DPC)]`

<h2>Description of scenario showing the problem:</h2>

You have the document `file1.tex`:
`file1.tex` contains a referencing label.

You have the document `file2.tex`: 
`file2.tex` loads the packages:
 - `hyperref` with the `dvipdfm`-driver-option 
 - `xr-hyper`

`file2.tex` via `xr-hyper`'s command `\externaldocument` loads the referencing-label from `file1.tex`/`file1.aux`.

When `\pageref` is applied to some external referencing-label twice, then with the second reference you get the message:

    Package hyperref Warning: Invalid page number (0)
    (hyperref)                for remote PDF file.
    (hyperref)                Using page 1 on input line ...

<h2>Examples exhibiting the problematic/erroneous behaviour:</h2>

`file1.tex`:

    \documentclass{article}
    
    \usepackage{hyperref}
    
    \begin{document}
    
    Empty page \newpage
    
    \section{Section in File1}\label{LabelFromFile1}
    This is referenced within file2.
    
    \end{document}

`file2.tex`:

    \documentclass{article}
    
    \usepackage{xr-hyper}
    \usepackage[%
      dvipdfm
    %  pdftex
    ]{hyperref}
    
    \externaldocument[file1-]{file1}
    
    \begin{document}
    
    Reference to label in file 1:
    
    \expandafter\show\csname Hy@href@page\endcsname
    
    \pageref{file1-LabelFromFile1}
    
    \expandafter\show\csname Hy@href@page\endcsname
    
    \pageref{file1-LabelFromFile1}
    
    \expandafter\show\csname Hy@href@page\endcsname
    
    \end{document}

<h3>Instructions:</h3>

 - Have `file1.tex` and `file2.tex` in the same directory.
 - Have that directory as the active directory/current directory.
 - Compile `file1.tex` until `file1.aux` exists and `file1.log` doesn't tell you to re-run LaTeX again.
 - Compile with latex (not pdflatex!) `file2.tex` until `file2.log` doesn't tell you to re-run LaTeX again.
 
Within `file2.log` you will find the message

    Package hyperref Warning: Invalid page number (0)
    (hyperref)                for remote PDF file.
    (hyperref)                Using page 1 on input line 21.

Within `file2.log` you will see that after the first call to `\pageref` the macro `\Hy@href@page` is not empty any more but expands to "0". I doubt that this change is correct.

(When compiling with the `pdftex`-driver-option instead of the `dvipdfm`-driver-option, then `\Hy@href@page` is always empty.)

<h2>My guess about the cause of this:</h2>

The warning is issued by the macro `\Hy@MakeRemoteAction` of `hyperref.sty`. (See line 7947 of hyperref.dtx [2019/09/28].)
`\Hy@MakeRemoteAction` acts as follows: 
 - In case `\Hy@href@page` is empty, `\Hy@href@page` gets redefined to expand to `0`.
 - In case `\Hy@href@page` expands to a value smaller than 1 (which is the case with the value `0`), the mentioned warning is written to screen and to .log-file.

`\Hy@MakeRemoteAction` in turn is called by the macro `\hyper@linkfile`.

Some driver-files (re)define `\hyper@linkfile`.

With some driver-files, e.g., `hpdftex.def`, everything done by `\hyper@linkfile` takes place within a group/within a local scope. (See line 14035 of hyperref.dtx [2019/09/28].) Thus with these driver-files `\Hy@MakeRemoteAction`'s redefining of `\Hy@href@page` to expand to `0` has no global effect. Thus here the warning does not occur.

With the driver-file `hdvipdfm.def` the things done by `\hyper@linkfile` do not take place within a group/within a local scope. (See line 15201 of hyperref.dtx [2019/09/28].) Thus with this driver-file `\Hy@MakeRemoteAction`'s redefining of `\Hy@href@page` to expand to `0` has a global effect. Thus with the second `\pageref`-reference `\Hy@href@page` is found non-empty but as `0` which triggers the warning.

When you redefine `hdvipdfm.def`'s `\hyper@linkfile` to do everything within a local scope (as is the case with `hpdftex.def`'s `\hyper@linkfile`), the warning is not there any more:

`file2.tex` with suggested fix for `hdvipdfm.def [2019/09/28 v7.00a Hyperref driver for dvipdfm]`:

    \documentclass{article}
    
    \usepackage{xr-hyper}
    \usepackage[%
      dvipdfm
    ]{hyperref}
    
    \makeatletter
    % \hyper@linkfil as in hdvipdfm.def [2019/09/28 v7.00a Hyperref driver for dvipdfm]
    % , but surrounding group added:
    \def\hyper@linkfile#1#2#3{%
      \begingroup %----\begingroup added
      \leavevmode
      \Hy@BeginAnnot{%
        \def\Hy@pstringF{#2}%
        \Hy@CleanupFile\Hy@pstringF
        \Hy@pstringdef\Hy@pstringF\Hy@pstringF
        \Hy@pstringdef\Hy@pstringD{#3}%
        \Hy@MakeRemoteAction %----Without the group the effects of \Hy@MakeRemoteAction are global.
        \@pdfm@mark{%
          bann<<%
            /Type/Annot%
            /Subtype/Link%
            \ifHy@pdfa /F 4\fi
            \Hy@setpdfborder
            \Hy@setpdfhighlight
            \ifx\@filebordercolor\relax
            \else
              /C[\@filebordercolor]%
            \fi
            /A<<%
              /S/GoToR%
              /F(\Hy@pstringF)%
              /D%
              \ifx\\#3\\%
                [\Hy@href@page\@pdfremotestartview]%
              \else
                (\Hy@pstringD)%
              \fi
              \Hy@SetNewWindow
              \Hy@href@nextactionraw
            >>%
          >>%
        }%
        \Hy@colorlink\@filecolor
      }%
      #1\Hy@xspace@end
      \Hy@EndAnnot
      \endgroup %----\endgroup added
    }%
    \makeatother    
    
    \externaldocument[file1-]{file1}
    
    \begin{document}
    
    Reference to label in file 1:
    
    \expandafter\show\csname Hy@href@page\endcsname
    
    \pageref{file1-LabelFromFile1}
    
    \expandafter\show\csname Hy@href@page\endcsname
    
    \pageref{file1-LabelFromFile1}
    
    \expandafter\show\csname Hy@href@page\endcsname
    
    \end{document}

But I am not sure if this redefinition is save.  
I leave judging the value of my analysis to the experts.

**Edit on Monday, October 28, 2019:**

I now found out that links to external files only work out when these external files were created using pdflatex and the `pdftex`-driver-option: In this case the external files will be opened and scrolled to the pages where the corresponding named destinations are placed.

When the external files were created using latex and the `dvipdfmx`-driver-option and the dvipdfmx-program for converting them to .pdf, then the external files will be opened but scrolling to the pages where the corresponding named destinations are placed does not occur any more.

Sincerely

Ulrich Diez

**Comment by u-fischer** [comment]
You are right about the source of the warning. And the same applies also to the xetex driver. But I'm not quite sure if one should add the group as I don't know if it was left out for a reason or not.

**Comment by davidcarlisle** [comment]
> Is somebody there who does know and who can take care of it?

we'll look but to be honest you probably know as much as anyone about hyperref+dvipdfmx , but as a general aim it would be good (as we did with the color/graphics driver back end files) to bring all the hyperref back end files into closer alignment with more clearly defined uniform interfaces to the central code.

Apart from fixing this for hyperref itself we need to (again) gain a good understanding of the capabilities of each driver to get uniform interfaces for the expl3 back end drawing code.


So thanks for the examples, and more are welcome if you have them, although I can't promise an immediate fix.

**Comment by u-fischer** [comment]
Try `\special{dvipdfmx:config C 0x10}` in the external document created with xetex or latex/dvipdfmx. This should recover the correct destination names and allow to referenced them from outside. See also 
https://tug.org/pipermail/dvipdfmx/2019-May/000003.html

**Comment by Ulrich-Diez** [comment]
u-fischer wrote:

> You are right about the source of the warning. And the same applies also to the xetex driver. But I'm not quite sure if one should add the group as I don't know if it was left out for a reason or not.

IIRC, then xetex produces dvi and converts that to pdf using dvipdfmx ?

> Try `\special{dvipdfmx:config C 0x10}` in the external document created with xetex or latex/dvipdfmx. This should recover the correct destination names and allow to referenced them from outside. See also
> https://tug.org/pipermail/dvipdfmx/2019-May/000003.html

Thank you, thank you, thank you, thank you very much! ;-)

I will test that and mention it in my answer to the use-case at [TeX LaTeX StackExchange](https://tex.stackexchange.com/a/512544/118714)

**Comment by u-fischer** [comment]
> > You are right about the source of the warning. And the same applies also to the xetex driver. But I'm not quite sure if one should add the group as I don't know if it was left out for a reason or not.
> 
> IIRC, then xetex produces dvi and converts that to pdf using dvipdfmx ?

xetex produces xdv (and extended dvi) and then (x)dvipdfmx for the pdf. 

I don't see a reason why the group should lead to a problem, so I will add it and run the test suite. If the xetex tests don't fail it should be okay.

**Comment by Ulrich-Diez** [comment]
> xetex produces xdv (and extended dvi) and then (x)dvipdfmx for the pdf.

Thank you for the clarification.
 
> I don't see a reason why the group should lead to a problem, so I will add it and run the test suite. If the xetex tests don't fail it should be okay.

The code of `\hyper@linkfile` of `hdvipdfm.def`/`hxetex.tex` is wrapped in `\Hy@BeginAnnot`/`\Hy@EndAnnot`.  
I suppose these (erroneously) were taken for something that already restrict things to a local scope.
