### ISSUE TITLE
hyperref-v7.00b works with pdflatex, but not with latex

### ISSUE THREAD

**Issue by balducci** [latex3/hyperref#108]
hello

when processing this latex source:

    ----8<----
    \documentclass{article}
    \usepackage{hyperref}
    \begin{document}

    hello, world!

    \end{document}
    ---->8----

with latex and hyperref-v7.00b, I get the following error:

    ----8<----
    delete_me.8IU6Or latex 000-pc.tex
    This is pdfTeX, Version 3.14159265-2.6-1.40.20 (Web2C 2020/dev) (preloaded format=latex)
     restricted \write18 enabled.
    entering extended mode
    (./000-pc.tex
    LaTeX2e <2019-10-01> patch level 2
    (/usr/share/texmf.local/texmf/tex/latex/base/article.cls
    Document Class: article 2019/10/25 v1.4k Standard LaTeX document class
    (/usr/share/texmf.local/texmf/tex/latex/base/size10.clo))
    (/usr/share/texmf.local/texmf/tex/latex/hyperref/hyperref.sty
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/ltxcmds.sty)
    (/usr/share/texmf.local/texmf/tex/latex/iftex/iftex.sty)
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/pdftexcmds.sty
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/infwarerr.sty)
    (/usr/share/texmf.local/texmf/tex/latex/iftex/ifluatex.sty)
    (/usr/share/texmf.local/texmf/tex/latex/iftex/ifpdf.sty))
    (/usr/share/texmf.local/texmf/tex/latex/graphics/keyval.sty)
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/kvsetkeys.sty
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/etexcmds.sty))
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/kvdefinekeys.sty)
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/pdfescape.sty)
    (/usr/share/texmf.local/texmf/tex/latex/oberdiek/hycolor.sty
    (/usr/share/texmf.local/texmf/tex/latex/oberdiek/xcolor-patch.sty
    (/usr/share/texmf.local/texmf/tex/latex/oberdiek/hopatch.sty)))
    (/usr/share/texmf.local/texmf/tex/latex/oberdiek/letltxmacro.sty)
    (/usr/share/texmf.local/texmf/tex/latex/oberdiek/auxhook.sty)
    (/usr/share/texmf.local/texmf/tex/latex/oberdiek/kvoptions.sty)
    (/usr/share/texmf.local/texmf/tex/latex/hyperref/pd1enc.def)
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/intcalc.sty)
    (/usr/share/texmf.local/texmf/tex/latex/url/url.sty)
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/bitset.sty
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/bigintcalc.sty))
    (/usr/share/texmf.local/texmf/tex/generic/oberdiek/atbegshi.sty))
    ! Undefined control sequence.
    \Hy@AtEndOfPackageHook ...ex}\else \ifnum \OpMode 
                                                      =10 \def \Hy@driver {hvtex...
    l.3 \begin
              {document}
    ---->8----

On the other hand, processing with pdflatex works fine.

But using hyperref-v7.00a or hyperref-v6.88i works fine with both
latex and pdflatex, ie:

      ----8<----
      hyperref  pdflatex  latex
      -------------------------
      v6.88i    good      good
      v7.00a    good      good
      v7.00b    good      bad
      ---->8----

Am I missing something or is there a problem with hyperref-v7.00b?

Here are the versions of latex and pdflatex I'm using:

    ----8<----
    #:48> pdflatex --version
    pdfTeX 3.14159265-2.6-1.40.20 (Web2C 2020/dev)
    kpathsea version 6.3.2/dev
    Copyright 2019 Han The Thanh (pdfTeX) et al.
    There is NO warranty.  Redistribution of this software is
    covered by the terms of both the pdfTeX copyright and
    the Lesser GNU General Public License.
    For more information about these matters, see the file
    named COPYING and the pdfTeX source.
    Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
    Compiled with libpng 1.5.30; using libpng 1.5.30
    Compiled with zlib 1.2.11; using zlib 1.2.11
    Compiled with xpdf version 4.02
    ---->8----

    ----8<----
    #:49> latex --version
    pdfTeX 3.14159265-2.6-1.40.20 (Web2C 2020/dev)
    kpathsea version 6.3.2/dev
    Copyright 2019 Han The Thanh (pdfTeX) et al.
    There is NO warranty.  Redistribution of this software is
    covered by the terms of both the pdfTeX copyright and
    the Lesser GNU General Public License.
    For more information about these matters, see the file
    named COPYING and the pdfTeX source.
    Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
    Compiled with libpng 1.5.30; using libpng 1.5.30
    Compiled with zlib 1.2.11; using zlib 1.2.11
    Compiled with xpdf version 4.02
    ---->8----

thanks a lot

ciao
-gabriele

**Comment by u-fischer** [comment]
Please show the log-file, not the terminal output.

**Comment by davidcarlisle** [comment]
Sorry about that, if you do not use vTeX, a temporary fix is to put

`\chardef\OpMode=20`

as the first line of hyperref, I'll put out a proper fix later today.

**Comment by davidcarlisle** [comment]
@balducci  7.0c is now checked in, and I added additional configuration the build scripts to make sure that the basic test files get checked with latex as well as pdflatex lualatex and xelatex, so hopefully it won't be quite so broken in the future.

Thanks for the report, You could get it from here although I am just about to re-submit it to ctan so it should come via the usual update channels in a day or so.

**Comment by balducci** [comment]
thanks a lot for taking the time to fix this!
I realize that there are probably few people using "plain" latex nowadays (even less using "plain" tex), yet "back compatibility" is always a Good Thing, no?

thank you very much again
ciao
-gabriele

**Comment by davidcarlisle** [comment]
@balducci  oh sure yes, there are probably more people than you think still using dvi based tex (for pstricks , or for speed, or because they like it or...)  it was a stupid error with a misplaced \ifvtex guard on my part. Most of our testing (here and in the main latex format tests) works by comparing annotated log files so pdflatex and latex are essentially the same in that view as the actual output isn't used, but unfortunately  that meant here we were not testing with latex at all and the misplaced guard made latex take the vtex code in one place.

I have re-arranged the test suite so a group of tests now run in more engines so hopefully such an error won't slip past again.

Thanks again for the report (even if it did spoil my weekend:-)
