### ISSUE TITLE
Hyperref manual.pdf being compiled with lualatex, straight double quotes end up curly

### ISSUE THREAD

**Issue by jfbu** [latex3/hyperref#113]
Here is relevant screenshot:
![Capture d’écran 2019-12-07 à 23 06 23](https://user-images.githubusercontent.com/2589111/70381194-7e901b80-1946-11ea-971e-908b7ccbf013.png)
and a copy paste from PDF of part of it
`` Option ”pdfencoding” selects between these en- codings:``.

With T1 encoding and pdflatex a `"` in source gives a `"` in PDF (copied pastable). But not with xelatex/lualatex and fontspec applying by default so-called "TeX ligatures".

<sub>I am not sure why the transform of `"` into `”` is part of "TeX ligatures" apart from the fact that this was the OT1 behavior and that the matching double quote `“` could back then be obtained via `\char92 ` (sic) ... but fontspec does not transform `\char92` into `“` --- it does activate the ````` ``--> “`````  --- and anyhow being truthful to Knuth OT1 when handling OpenType font is probably, certainly, not the rationale behind that inclusion of the transform ``"-->”`` done by default by fontspec...</sub>

**Comment by u-fischer** [comment]
Well `"pdfdoc"` is simply bad markup and this should be changed to e.g. \enquote{pdfdoc}. 

I don't know why `"` was added to +tlig, it looks a bit questionable, but it is not a hyperref problem.

**Comment by jfbu** [comment]
Unfortunately executing `\defaultfontfeatures[...]{}` will also modify the rendering of `` `foo' `` input (single quotes), of which numerous instances are found in the manual.tex file.

You say the fix is to use  `\enquote{...}` but that is a break away from legacy rendering of hyperref manual.pdf (my example came from README.pdf and possibly all such instances but not checked) .

**Comment by u-fischer** [comment]
> You say the fix is to use `\enquote{...}` but that is a break away from legacy rendering of hyperref manual.pdf

Where is the problem? Why shouldn't we improve the manual if we find an error?

**Comment by jfbu** [comment]
There is no problem, if you judge there was an error in the rendering of the "README" to PDF. The error is revealed when one compiles via Unicode and fontspec, is there a specific reason the manual.pdf should use a Unicode engine and fonts?

**Comment by davidcarlisle** [comment]
@jfbu when I picked these up some years ago  to form this Git repository the pdfs on ctan were made by luatex, so I did the same while reverse engineering a build script. I suspect they were made with luatex because of the file size saving:

```
$ ls -l manual-*pdf
-rw-r--r-- 1  .... 296941 Jan 18 11:39 manual-luatex.pdf
-rw-r--r-- 1 ..... 647881 Jan 18 11:39 manual-pdftex.pdf
``
