### ISSUE TITLE
Back-referencing figures and tables

### ISSUE THREAD

**Issue by aliciaakemi** [latex3/hyperref#114]
Is there any easy way to use the hyperref package to cross-reference back text that references figures or tables, so that the table caption can reference back the text that cited it?

**Comment by u-fischer** [comment]
This here is an issue tracker not a general support forum for hyperref. You can find here a list of better suited sites: http://tug.org/interest.html#texhelp

Beside this: as a caption can be cited in more than one place a back reference is not well defined and so doesn't make much sense. If you want to back to the place use the shortcuts of your pdf viewer (normally alt + left arrow).

**Comment by aliciaakemi** [comment]
ok. thank you.

**Comment by aliciaakemi** [comment]
> This here is an issue tracker not a general support forum for hyperref. You can find here a list of better suited sites: http://tug.org/interest.html#texhelp
> 
> Beside this: as a caption can be cited in more than one place a back reference is not well defined and so doesn't make much sense. If you want to back to the place use the shortcuts of your pdf viewer (normally alt + left arrow).

What could I do inside the hyperref code to automate this process?
I suppose it is not a very difficult modification to make since the bibliographic cross-reference code could be reused for that purpose.
