### ISSUE TITLE
[doc] Some options are missing from big option list in Sec. 3.9

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/hyperref#117]
Following options are missing from Sec. 3.9 _Big alphabetical list_, documentation of `hyperref`.
```
allbordercolors
allcolors
driverfallback
hidelinks
pdfborderstyle
psdextra
```

Also, in that list, option `pdfpagelabels` is not in alphabetical order. It should appear just before option `pdfpagelayout`.
https://github.com/latex3/hyperref/blob/43014a0f8bf5f6db127475e158e8e1dd8a648329/doc/manual.tex#L981-L983

**Comment by davidcarlisle** [comment]
thanks
