### ISSUE TITLE
Problems with hyperlink to external PDF file (also latex)

### ISSUE THREAD

**Issue by quaatz** [latex3/hyperref#118]
Hi everybody,
if I try to have hyperlinks in my document to an external PDF file also generated with latex, the links are broken. The last working release seems to be version 6.88i.

Both latex files are located in the same directory.
latex1.tex:

```
\documentclass{article}
\usepackage{xr-hyper}
\usepackage{hyperref}
\externaldocument[ext1:]{latex2}

\begin{document}

\section{Erste Ueberschrift}
\label{sec:1}

Reference: \ref{ext1:sec:1}.
Hyperref: \hyperref[ext1:sec:1]{Test}

\end{document}
```

And the second one: latex2.tex
```
\documentclass{article}
\pagenumbering{roman}
\usepackage{xr-hyper}
\usepackage{hyperref}

\begin{document}
    \section{Erste Ueberschrift}
    \label{sec:1}
\end{document}
```

I hope that the mistake is not on my side.
Thanks for your effort.
Frederik

**Comment by aldanor** [comment]
Just wanted to post the same thing; in my case it works with pdflatex, but not xelatex (latest texlive distribution, all packages updated to latest versions).

My MWE is almost exactly the same as @quaatz's, so I'm not going to repeat it.

The outcome is this:

- when compiled with `latexmk -pdf`, the cross-document hyperlinks are properly generated, it opens the other document and jumps to the right location
- when compiled with `latexmk -pdfxe` (xelatex), the cross-document link works but opens the **first page** of the referenced document only. Any idea why?

**Comment by aldanor** [comment]
Really hoping @davidcarlisle would have an idea 🙏

**Comment by aldanor** [comment]
Interesting - tried recompiling with v6.88e, but got same result.

Just for completeness, here's my example:

```tex
% foo.tex
\documentclass{article}
\usepackage{lipsum}
\usepackage{hyperref}
\listfiles

\begin{document}
\section{Introduction}
\lipsum[1-10]
\subsection{Hello}\label{hello}
\lipsum[1-10]
\end{document}
```

```tex
% bar.tex
\documentclass{article}
\usepackage{xr-hyper}
\usepackage{hyperref}
\listfiles

\begin{document}
\externaldocument[F-]{foo}
Ref \ref{F-hello}.
\end{document}
```

This works:

```sh
latexmk foo.tex -pdf
latexmk bar.tex -pdf
```

Here links exist but are broken:

```sh
latexmk foo.tex -pdfxe
latexmk bar.tex -pdfxe
```

**Comment by aldanor** [comment]
Ok, I think I have figured it out (after reading some source code, latexmk source, and tons of other stuff I didn't really intend reading...)

In options for `xdvipdfmx`, you have to prevent it from optimizing pdf locations (check its help) by passing `-C 0x0010` flag (**very** obvious flag, right?!).

So you can either do

```sh
$ xelatex foo.tex -no-pdf
$ xdvipdfmx -C 0x0010 foo.xdv
```

or add

```pl
$xdvipdfmx  = 'xdvipdfmx -C 0x0010 -o %D %O %S';
```

to `latexmkrc`.

Or, pass `-output-driver` to `xelatex`.

Either way, this is NOT the most obvious thing. Should it be maybe mentioned somewhere in the hyperref docs so it's googlable or something? (so as to help other poor souls who will get stuck at the same thing; it's a driver defaults problem and not a hyperref issue I guess - but people will ask here for help like we did with @quaatz)

**Comment by davidcarlisle** [comment]
@aldanor  thanks for the analysis, it may be worth raising this with the xdvipfmx developers, see if we can improve the default interaction.

@quaatz  can say if you were using xetex/xdvipdfm, your initial report mentioned latex rather than xelatex, so I'm not sure if this is the same issue?

**Comment by quaatz** [comment]
Hey guys,
thanks for the vital discussion.
I am using PDFTex with MikTex (Windows) and TexLive (Linux) in the latest distribution. I do not use xelatex.
The link on Windows resolves to: latex2.pdf%7B%7D%7B%7D%7B%7D#section.1%7B%7D%7B%7D%7B%%7D
In Linux it resolves to the corresponding curling brackets latex2.pdf{}{}{}#section.1{}{}{}
Thanks a lot.

**Comment by kia999** [comment]
I noted the same trouble just today, PDF browser like PDFSumatra complains that it cannot find external PDF file with correct path appendix with {}{}.

**Comment by quaatz** [comment]
Hi Ulrike,
Just saw that you pushed a fix. Thank you! I will test it as soon as it is avaible in the master branch.

**Comment by muzimuzhi** [comment]
> In options for `xdvipdfmx`, you have to prevent it from optimizing pdf locations (check its help) by passing `-C 0x0010` flag (**very** obvious flag, right?!).
> 
> So you can either do
> 
> ```shell
> $ xelatex foo.tex -no-pdf
> $ xdvipdfmx -C 0x0010 foo.xdv
> ```
> 
> or add
> 
> ```perl
> $xdvipdfmx  = 'xdvipdfmx -C 0x0010 -o %D %O %S';
> ```
> 
> to `latexmkrc`.
> 
> Or, pass `-output-driver` with the above settings to `xelatex`.

Or use `\special{dvipdfmx:config C 0x0010}` in `foo.tex`. See [documentation of `dvipdfmx`](http://mirrors.ctan.org/systems/doc/dvipdfmx/dvipdfmx.pdf), sec. 1.3.1 and 3.2. A more radical solution would be to change the default behavior of `(x)dvipdfmx` by modifying its config file `kpsewhich -progname=dvipdfmx -format='other text files'`.

Here is an attempt to insert `\special{dvimdfmx:config ...}` automatically,  by providing a new `hyperref` option `xrhyper`.

```tex
% foo.tex
\documentclass{article}
\usepackage{lipsum}
\usepackage{hyperref}
\listfiles

% config codes
\makeatletter
\newif\ifHy@xrhyper
\Hy@destlabelfalse % redundant

% new bool option "xrhyper", 
% which sets whether prepare for later xr-hyper use or not
\define@key{Hyp}{xrhyper}[true]{%
  \Hy@boolkey{xrhyper}{#1}%
}

% can be moved to corresponding h-driver files
\Hy@AtBeginDocument{%
  \ifHy@xrhyper
    \def\Hy@temp{hxetex}%
    \ifx\Hy@driver\Hy@temp
      \special{dvipdfmx:config C 0x0010}%
    \fi
    \def\Hy@temp{dvipdfmx}%
    \ifx\Hy@driver\Hy@temp
      \special{dvipdfmx:config C 0x0010}%
    \fi
  \fi
}
\makeatother

%% user interface
\hypersetup{xrhyper}

\begin{document}
\section{Introduction}\label{intro}
\lipsum[1-10]
\subsection{Hello}\label{hello}
\lipsum[1-10]
\end{document}
```

**Comment by u-fischer** [comment]
@muzimuzhi a better solution would be if xdvipdfmx would revert this optimization or to add the config always. There is not much to gain here, only lots of problems.  see also https://tug.org/pipermail/dvipdfmx/2019-May/000002.html

**Comment by muzimuzhi** [comment]
> There is not much to gain here, only lots of problems.

Ah, yes. I have encountered the requirement to restore this optimization multiple times. If the optimization is robust, maybe deleting unused named destinations would provide (a little) helpful.

**Comment by u-fischer** [comment]
hyperref disables now the optimization.
