### ISSUE TITLE
when merely useing package "hyperref" (latest version) for a test ,it just error ! 

### ISSUE THREAD

**Issue by ChinaGao-lab0** [latex3/hyperref#122]
i'm a teacher of China,  My system is MacTex with MacOS 15.2, i've tried  many times  with "xelatex"  to compile my tex document,  but it reply me with error  :
**!undefined control sequence .  \ifxetex
!Extra \else. \else**  pointing  to the document **/usr/local/texlive/2019/texmf-dist/tex/latex/hyperref/hyperref.sty**

but what i test  was the only package "hyperref", Who knows the reason,and solving mathod?
`\documentclass[12pt]{book}

\usepackage{hyperref}

%\usepackage[implicit=false]{hyperref}
%\hypersetup{
%   colorlinks=true,
%   linkcolor=blue,
%   filecolor=blue,
%   urlcolr=blue,
%   citecolor=cyan,
%           }

\begin{document}
\tableofcontents

\chapter{once upon a time}
\section{there is a thief}
lkj jkdlsa fijoiewj fiojgfoiu3q09ut4pk34 lkj lkgjo jojleakg f

\chapter{j lkj}
\section{kdls ; }
kjlk; ;lkj f09woe jljgfpo43124567
\end{document}`

**Comment by u-fischer** [comment]
Please show the complete log-file of the compilation.

**Comment by ChinaGao-lab0** [comment]
@u-fischer 
[test3.log](https://github.com/latex3/hyperref/files/4256998/test3.log)

**Comment by ChinaGao-lab0** [comment]
`OG FILE :
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019) (preloaded format=xelatex 2020.2.7) 26 FEB 2020 22:42
entering extended mode
restricted \write18 enabled.
%&-line parsing enabled.
**test3.tex
(./test3.tex
LaTeX2e <2018-12-01>
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/book.cls
Document Class: book 2018/09/03 v1.4i Standard LaTeX document class
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/bk12.clo
File: bk12.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
)
\c@part=\count80
\c@chapter=\count81
\c@section=\count82
\c@subsection=\count83
\c@subsubsection=\count84
\c@paragraph=\count85
\c@subparagraph=\count86
\c@figure=\count87
\c@table=\count88
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/graphics/color.sty
Package: color 2016/07/10 v1.1e Standard LaTeX Color (DPC)
(/usr/local/texlive/2019/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package color Info: Driver file: xetex.def on input line 147.
(/usr/local/texlive/2019/texmf-dist/tex/latex/graphics-def/xetex.def
File: xetex.def 2017/06/24 v5.0h Graphics/color driver for xetex
))
(/usr/local/texlive/2019/texmf-dist/tex/latex/xcolor/xcolor.sty
Package: xcolor 2016/05/11 v2.12 LaTeX color extensions (UK)
(/usr/local/texlive/2019/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: xetex.def on input line 225.
LaTeX Info: Redefining \color on input line 709.
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.
Package xcolor Info: Model `RGB' extended on input line 1364.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1366.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1367.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1370.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1371.
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/hyperref/hyperref.sty
Package: hyperref 2020/01/14 v7.00d Hypertext links for LaTeX
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/ltxcmds.sty
Package: ltxcmds 2016/05/16 v1.23 LaTeX kernel commands for general use (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
and LuaTeX
)
LaTeX Warning: You have requested, on input line 107, version
`2019/10/24' of package iftex,
but only version
`2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
and LuaTeX'
is available.
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty
Package: pdftexcmds 2018/09/10 v0.29 Utility functions of pdfTeX for LuaTeX (HO
)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/infwarerr.sty
Package: infwarerr 2016/05/16 v1.4 Providing info/warning/error messages (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/ifluatex.sty
Package: ifluatex 2016/05/16 v1.4 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/ifpdf.sty
Package: ifpdf 2018/09/07 v3.3 Provides the ifpdf switch
)
Package pdftexcmds Info: LuaTeX not detected.
Package pdftexcmds Info: pdfTeX >= 1.30 not detected.
Package pdftexcmds Info: \pdf@primitive is available.
Package pdftexcmds Info: \pdf@ifprimitive is available.
Package pdftexcmds Info: \pdfdraftmode not found.
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks14
)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
Package: kvsetkeys 2016/05/16 v1.17 Key value parser (HO)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/etexcmds.sty
Package: etexcmds 2016/05/16 v1.6 Avoid name clashes with e-TeX commands (HO)
))
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/kvdefinekeys.sty
Package: kvdefinekeys 2016/05/16 v1.4 Define keys (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/pdfescape.sty
Package: pdfescape 2016/05/16 v1.14 Implements pdfTeX's escape features (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/hycolor/hycolor.sty
Package: hycolor 2020-01-27 v1.10 Color options for hyperref/bookmark (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/oberdiek/letltxmacro.sty
Package: letltxmacro 2016/05/16 v1.5 Let assignment for LaTeX macros (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/oberdiek/auxhook.sty
Package: auxhook 2016/05/16 v1.4 Hooks for auxiliary files (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/latex/oberdiek/kvoptions.sty
Package: kvoptions 2016/05/16 v3.12 Key value format for package options (HO)
)
\@linkdim=\dimen103
\Hy@linkcounter=\count89
\Hy@pagecounter=\count90
! Undefined control sequence.
l.707 \ifxetex
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Extra \else.
l.709 \else
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
l.713 \fi
I'm ignoring this; it doesn't match any \if.
(/usr/local/texlive/2019/texmf-dist/tex/latex/hyperref/pd1enc.def
File: pd1enc.def 2020/01/14 v7.00d Hyperref: PDFDocEncoding definition (HO)
)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/intcalc.sty
Package: intcalc 2016/05/16 v1.2 Expandable calculations with integers (HO)
)
\Hy@SavedSpaceFactor=\count91
! Undefined control sequence.
l.2930 \ifxetex
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Extra \else.
l.2932 \else
I'm ignoring this; it doesn't match any \if.
! Undefined control sequence.
l.2933 \ifvtex
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Undefined control sequence.
l.2934 \ifnum\OpMode
=\z@
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Missing number, treated as zero.
<to be read again>
=
l.2934 \ifnum\OpMode=
\z@
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
! Extra \else.
l.2939 \else
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
l.2942 \fi
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
l.2943 \fi
I'm ignoring this; it doesn't match any \if.
(/usr/local/texlive/2019/texmf-dist/tex/latex/latexconfig/hyperref.cfg
File: hyperref.cfg 2002/06/06 v1.2 hyperref configuration of TeXLive
)
Package hyperref Info: Hyper figures OFF on input line 4547.
Package hyperref Info: Link nesting OFF on input line 4552.
Package hyperref Info: Hyper index ON on input line 4555.
Package hyperref Info: Plain pages OFF on input line 4562.
Package hyperref Info: Backreferencing OFF on input line 4567.
Package hyperref Info: Implicit mode ON; LaTeX internals redefined.
! Undefined control sequence.
l.4773 \ifxetex
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Extra \fi.
l.4779 \fi
I'm ignoring this; it doesn't match any \if.
Package hyperref Info: Bookmarks ON on input line 4800.
\c@Hy@tempcnt=\count92
(/usr/local/texlive/2019/texmf-dist/tex/latex/url/url.sty
\Urlmuskip=\muskip10
Package: url 2013/09/16 ver 3.4 Verb mode for urls, etc.
)
LaTeX Info: Redefining \url on input line 5159.
\XeTeXLinkMargin=\dimen104
! Undefined control sequence.
l.5243 \ifxetex
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Extra \else.
l.5282 \else
I'm ignoring this; it doesn't match any \if.
! LaTeX Error: Command \XeTeXLinkBox already defined.
Or name \end... illegal, see p.192 of the manual.
See the LaTeX manual or LaTeX Companion for explanation.
Type H <return> for immediate help.
...
l.5289 }
%
Your command was ignored.
Type I <command> <return> to replace it with another command,
or <return> to continue without it.
! Extra \fi.
l.5290 \fi
I'm ignoring this; it doesn't match any \if.
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/bitset.sty
Package: bitset 2016/05/16 v1.2 Handle bit-vector datatype (HO)
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/bigintcalc.sty
Package: bigintcalc 2016/05/16 v1.4 Expandable calculations on big integers (HO
)
))
\Fld@menulength=\count93
\Field@Width=\dimen105
\Fld@charsize=\dimen106
Package hyperref Info: Hyper figures OFF on input line 6430.
Package hyperref Info: Link nesting OFF on input line 6435.
Package hyperref Info: Hyper index ON on input line 6438.
Package hyperref Info: backreferencing OFF on input line 6445.
Package hyperref Info: Link coloring OFF on input line 6450.
Package hyperref Info: Link coloring with OCG OFF on input line 6455.
Package hyperref Info: PDF/A mode OFF on input line 6460.
LaTeX Info: Redefining \ref on input line 6500.
LaTeX Info: Redefining \pageref on input line 6504.
(/usr/local/texlive/2019/texmf-dist/tex/generic/oberdiek/atbegshi.sty
Package: atbegshi 2016/06/09 v1.18 At begin shipout hook (HO)
)
\Hy@abspage=\count94
\c@Item=\count95
\c@Hfootnote=\count96
)
! Extra \fi.
\Hy@AtEndOfPackageHook ...Hy@temp \fi \fi \fi \fi
\ifx \Hy@driver \@empty \e...
l.6
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
\Hy@AtEndOfPackageHook ...ver \@empty \fi \fi \fi
\let \HyOpt@DriverType \lt...
l.6
I'm ignoring this; it doesn't match any \if.
! Undefined control sequence.
\Hy@AtEndOfPackageHook ...atex}\fi \else \ifxetex
\def \Hy@driver {hxetex}\e...
l.6
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Extra \else.
\Hy@AtEndOfPackageHook ...Hy@driver {hxetex}\else
\ifnum \ifvtex \OpMode \el...
l.6
I'm ignoring this; it doesn't match any \if.
! Undefined control sequence.
\Hy@AtEndOfPackageHook ...ex}\else \ifnum \ifvtex
\OpMode \else \m@ne \fi =1...
l.6
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Undefined control sequence.
\Hy@AtEndOfPackageHook ... \ifnum \ifvtex \OpMode
\else \m@ne \fi =10 \def \...
l.6
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Missing number, treated as zero.
<to be read again>
\relax
l.6
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
! Missing = inserted for \ifnum.
<to be read again>
\relax
l.6
I was expecting to see `<', `=', or `>'. Didn't.
! Missing number, treated as zero.
<to be read again>
\relax
l.6
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
! LaTeX Error: Missing \begin{document}.
See the LaTeX manual or LaTeX Companion for explanation.
Type H <return> for immediate help.
...
l.6
You're in trouble here. Try typing <return> to proceed.
If that doesn't work, type X <return> to quit.
! Extra \else.
\Hy@AtEndOfPackageHook ...Doc {}}\endinput }\else
\ifnum \ifvtex \OpMode \el...
l.6
I'm ignoring this; it doesn't match any \if.
! Undefined control sequence.
\Hy@AtEndOfPackageHook ...t }\else \ifnum \ifvtex
\OpMode \else \m@ne \fi =\...
l.6
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Undefined control sequence.
\Hy@AtEndOfPackageHook ... \ifnum \ifvtex \OpMode
\else \m@ne \fi =\@ne \def...
l.6
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Missing number, treated as zero.
<to be read again>
\relax
l.6
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
! Missing = inserted for \ifnum.
<to be read again>
\relax
l.6
I was expecting to see `<', `=', or `>'. Didn't.
! Missing number, treated as zero.
<to be read again>
\relax
l.6
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
Missing character: There is no ^^A in font [lmroman12-regular]:mapping=tex-text
;!
! Extra \else.
\Hy@AtEndOfPackageHook ...\Hy@driver {hvtex}\else
\ifnum \ifvtex \OpMode \el...
l.6
I'm ignoring this; it doesn't match any \if.
! Undefined control sequence.
\Hy@AtEndOfPackageHook ...ex}\else \ifnum \ifvtex
\OpMode \else \m@ne \fi =\...
l.6
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Undefined control sequence.
\Hy@AtEndOfPackageHook ... \ifnum \ifvtex \OpMode
\else \m@ne \fi =\tw@ \def...
l.6
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
! Missing number, treated as zero.
<to be read again>
\relax
l.6
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
! Missing = inserted for \ifnum.
<to be read again>
\relax
l.6
I was expecting to see `<', `=', or `>'. Didn't.
! Missing number, treated as zero.
<to be read again>
\relax
l.6
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
Missing character: There is no ^^B in font [lmroman12-regular]:mapping=tex-text
;!
! Extra \else.
\Hy@AtEndOfPackageHook ...\Hy@driver {hvtex}\else
\ifx \HyOpt@DriverFallback...
l.6
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
\Hy@AtEndOfPackageHook ...\fi \fi \fi \fi \fi \fi
\fi \ifx \Hy@driver \Hy@de...
l.6
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
\Hy@AtEndOfPackageHook ...\fi \fi \fi \fi \fi \fi
\ifx \Hy@driver \Hy@defaul...
l.6
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
\Hy@AtEndOfPackageHook ...indo}{color}\fi \fi \fi
\else \def \HyOpt@DriverTy...
l.6
I'm ignoring this; it doesn't match any \if.
! Extra \else.
\Hy@AtEndOfPackageHook ...color}\fi \fi \fi \else
\def \HyOpt@DriverType { (...
l.6
I'm ignoring this; it doesn't match any \if.
! Extra \fi.
\Hy@AtEndOfPackageHook ...\HyOpt@CustomDriver \fi
\Hy@InfoNoLine {Driver\HyO...
l.6
I'm ignoring this; it doesn't match any \if.
Package hyperref Info: Driver (custom): .
! LaTeX Error: File `.def' not found.
Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: def)
Enter file name:
! Emergency stop.
<read *>
l.6 ^^M
*** (cannot \read from terminal in nonstop modes)
Here is how much of TeX's memory you used:
4393 strings out of 492916
64924 string characters out of 6133346
156987 words of memory out of 5000000
8444 multiletter control sequences out of 15000+600000
4008 words of font info for 16 fonts, out of 8000000 for 9000
1348 hyphenation exceptions out of 8191
29i,0n,35p,186b,40s stack positions out of 5000i,500n,10000p,200000b,80000s
No pages of output.`

**Comment by u-fischer** [comment]
You have an outdated version of the `iftex` package and get a warning about it in the log:

~~~~
(/usr/local/texlive/2019/texmf-dist/tex/generic/iftex/iftex.sty
Package: iftex 2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX, 
and LuaTeX
)

LaTeX Warning: You have requested, on input line 107, version
               `2019/10/24' of package iftex,
               but only version
               `2013/04/04 v0.2 Provides if(tex) conditional for PDFTeX, XeTeX,
 and LuaTeX'
               is available.
~~~~

Update your system or at least the iftex package with `tlmgr update iftex` (you probably will need more updates, your hyperref is very new).

**Comment by ChinaGao-lab0** [comment]
EMMMM,  Many  thanks ,i'll have a try
