### ISSUE TITLE
pdfstartpage should default to empty

### ISSUE THREAD

**Issue by viktoriasee** [latex3/hyperref#123]
#### Steps to reproduce 
1. Create a document with hyperref, don't specify pdfstartpage
1. Validate the PDF in Acrobat Preflight for PDF/X.

#### Current behaviour (bug)
1. You will see an error that the file contains an action. The action is to open the document at page 1.
1. The documentation states that pdfstartpage must be an integer. But if you try pdfstartpage={} no action is created thus no validation error occurs. Empty is not an integer!

#### Expected behaviour (correct)
1. Of course, I don't like validation errors. As any PDF viewer I know opens a document on page 1 by default, a separate action to do this is not necessary.
1. The doc should specify explicitely that this can be empty.

**Comment by u-fischer** [comment]
Yes the code explicitly allows an empty argument and this should be documented. I don't think that we can change the default from 1 to empty: the action doesn't only define the page but also the start view (the default is /Fit). If  we would change this it could affect existing documents.

**Comment by viktoriasee** [comment]
When I set `pdfstartpage={}` the *action* that disturbs preflight is gone. pdfstartview=Fit is still there but obviously not considered as an *action*.

Another question is why `pdfstartview=fit` is the default. Why is not *default* (in Acrobat, empty in hyperref) the default? The very similar setting pdfpagelayout is defaults to empty/default. This is not consistent. But maybe OT here.

**Comment by u-fischer** [comment]
This has been now documentated. l3pdfmeta will be extended to x standard at some time and then  pdfstartpage will be set accordingly if the standard is detected.
