### ISSUE TITLE
Ability to specify OutputIntents

### ISSUE THREAD

**Issue by viktoriasee** [latex3/hyperref#124]
### Introduction
If someone wants to create a PDF/A or PDF/X compliant PDF, * has to specify an OutputIntent. OutputIntent has to do what media the creator had in mind when * created the document. Different media have different ability to render colours. Uncoated (newspaper) paper is cheap but will not show very saturated colours. Wide gamut screens can show so many colours but problems are unavoidable when you try to print a picture optimised for screen on a simple paper.

### Status quo
Hyperref already has a pdfa option. But it does not create an OutputIntent. This is somehow a bug in my eyes. You should go all the way through.

### minimal example
```latex
\documentclass{article}
\usepackage[pdfa]{hyperref}

\immediate\pdfobj stream attr{/N 4} file{UncoatedFOGRA29.icc}
\edef\iccobj{\the\pdflastobj}
\pdfcatalog{%
  /OutputIntents [ <<
    /DestOutputProfile \iccobj\space 0 R
    /Info (Uncoated FOGRA29 (ISO 12647-2:2004))
    /OutputCondition(Offset print according to ISO/DIS 12647-2:2003)
    /OutputConditionIdentifier (FOGRA29)
    /RegistryName(http://www.color.org)
    /S /GTS_PDFX
    /Type /OutputIntent
  >><<
    /DestOutputProfile \iccobj\space 0 R
    /Info (Uncoated FOGRA29 (ISO 12647-2:2004))
    /OutputCondition(Offset print according to ISO/DIS 12647-2:2003)
    /OutputConditionIdentifier (FOGRA29)
    /RegistryName(http://www.color.org)
    /S /GTS_PDFA1
    /Type /OutputIntent
  >> ]
}
\begin{document}
\LaTeX
\end{document}
```

### Desired behaviour
Because the above example contains low level commands I would like to have this automatically included. FOGRA29 being a small colour space for uncoated paper is a safe default I think. If someone might like another OutputIntent I suggest an option like `\OutputIntent=FOGRA39`.
When you create an OutputIntent for PDF/A, please also create the same for PDF/X. They should be identical so *one* option is enough. The profiles can be fetched from the https://ctan.org/pkg/colorprofiles

**Comment by u-fischer** [comment]
I quite agree that there should by support for outputintents (and other standard related questions) We are working on the needed low-level code in the pdfresources project. But it should be possible to add them without loading hyperref. Extending hyperref would be imho the wrong way.

**Comment by viktoriasee** [comment]
The question is indeed *where* is the right place for this code snippet. Currently it's included in [pdfx](https://ctan.org/pkg/pdfx). But there is no support for dual OuputIntent as in the example above pdfx is currently incompatible with hyperxmp.
This pdfresources project is not a package yet and I would rather not wait for years to include such a small piece of code. That's also the reason I do not seek creating my own separate package for it.
And hyperref already provides a `pdfa` option. That's a strong argument to include this here I think. Or remove the option.

**Comment by u-fischer** [comment]
the pdfa option of hyperref mostly controls some of the form fields options which are not allowed with pdfa, it is not meant as the implementation of a full standard compliency.  There is nothing in hyperref regarding pdf/X. hyperref is for both standards the wrong package. The package which currently handles standard is as you said pdfx. So for a short term solution I would suggest that you  ask its maintainer to address the issues you have with it. Or you use your low-level code. The long term plan is to get proper support directly in latex but this will take some time.

**Comment by viktoriasee** [comment]
Hyperref today provides an interface to most contents in the document catalog of a PDF a user might want to change. See [p. 78 of the spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf). Excluding OutputIntent looks arbitrary to me.

**Comment by u-fischer** [comment]
From the around 30 keys for the catalog mentioned in the pdf 2.0 spec hyperref handles or affects only around the half. It has e.g. no tool for /AF or /StructTreeRoot or /Thread or /MetaData.

Outputintent is about color. The entry is also relevant for documents which don't need or want the hyperref stuff.

**Comment by u-fischer** [comment]
The new pdfmanagement code contains support to add colorprofiles and outputintents. See the documentation l3pdfmeta.
The interfaces for arbitrary profiles is not finished, but should be added soon. This works also without hyperref. Questions and comments should be made at https://github.com/latex3/pdfresources/issues.
