### ISSUE TITLE
backref causing infinite rerun loop

### ISSUE THREAD

**Issue by urehmann** [latex3/hyperref#127]
Together with the amsrefs package, the package backref causes an infinite
rerun loop. Below is a kind of minimal example.

amsrefs returns a warning for the cite syntax, but the suggested alternative
causes an error ("! Missing \endcsname inserted.")

%\documentclass[10pt]{article}
\documentclass[10pt]{amsart}

\usepackage{backref}
\usepackage{amsrefs}

\begin{document}

\section{Important Result}

Thm. follows from
%\cite{Theorem\~11}*{EZ}.
\cite[Theorem\~11]{EZ}.

\begin{thebibliography}{123}
      \bibitem {EZ}  TestAuthor,
        \emph{TestTitle,} TestJournal \textbf 50  (2045), 601-622.
\end{thebibliography}

\end{document}

**Comment by u-fischer** [comment]
That is an amsrefs bug. It doesn't set the variable that tells backref that the file is open. If you add `\makeatletter\gdef\tf@brf@open{}\makeatother` (at best after \begin{document}) it works.
