### ISSUE TITLE
omit empty deprecated Document Info

### ISSUE THREAD

**Issue by viktoriasee** [latex3/hyperref#128]
### Background
Metadata in PDF documents can be stored in XMP in Document Info or in both. DocumentInfo is deprecated as of PDF 2.0 (see the ISO 32000-2 spec at 14.3.3).

### Problem
Hyperref currently writes `/Author()/Title()/Subject()/Keywords()` in DocumentInfo even when they are not specified. That is not recommended by PDF 2.0.
But even for older PDF 1.7 or earlier it can cause problems.

### Minimal example
```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
Text.
\end{document}
```
### Proposed solution
1. Only write DocumentInfo tags when they are not empty.
1. provide a switch to conveniently diasble setting of DocumentInfo except `/CreationDate` and `/ModDate`

**Comment by u-fischer** [comment]
While it is a bid odd that hyperref writes empty entries, I never heard that it caused any problems. Do you have an example?

**Comment by viktoriasee** [comment]
The reason why DocumentInfo got deprecated is that in DocumentInfo it's not possible to provide author lists. Since LaTeX is often used by scientists this is highly relevant because for them it's very important to appear as individuals in the author list.
You can include author lists in XMP i.e. by using `xmpincl` or `hyperxmp` or `pdfx`. But as long as you provide author as a string in DocumentInfo you will break compatibility with standards such as PDF/A and PDF/X even in cases where pdf version is smaller than 2.0. The rule is that if XMP and DocumentInfo are provided they must match. But you can't match a string to a list.
Yes it is possible to write workarounds in those other packages but I think it's better to fix the problem at its origin. The future of PDF is without DocumentInfo.

**Comment by u-fischer** [comment]
with hyperxmp I don't get an empty author in the info dict:

~~~~

\documentclass{article}%
\usepackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\usepackage{hyperxmp}
\usepackage[unicode]{hyperref}
%\hypersetup{pdfauthor=blub}
\begin{document}%

blub

\end{document}%
~~~~

gives 

~~~~
16 0 obj
<<
/Producer (pdfTeX-1.40.21)
/Creator (TeX)
/CreationDate (D:20200311210535+01'00')
/ModDate (D:20200311210535+01'00')
/Trapped /False
/PTEX.Fullbanner (This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/W32TeX) kpathsea version 6.3.2)
>>
endobj
~~~~

**Comment by u-fischer** [comment]
The hyperref driver used with the new PDF management code doesn't write /Author, /Title /Subject  or /Keywords` to the info dictionary if not explicitly asked to do it, not even it \author and \title is used.

~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
  
\documentclass{article}
\usepackage{hyperref}
\author{me}
\title{title}
\begin{document}
Text.
\end{document}  
~~~~

**Comment by dbitouze** [comment]
> The hyperref driver used with the new PDF management code doesn't write /Author, /Title /Subject or /Keywords` to the info dictionary if not explicitly asked to do it, not even it \author and \title is used.

What will replace this feature?

**Comment by u-fischer** [comment]
@dbitouze  currently you will have to use `pdfauthor` and `pdftitle`  (as you could already). In the long run some of the settings will probably wander into \DeclareDocumentMetadata. 

Beside this: The info dictionary is deprecated in pdf 2.0, most of the data will go into the xmp-Metadata.
