### ISSUE TITLE
pdfborderstyle does not work for mac

### ISSUE THREAD

**Issue by zhyiyu** [latex3/hyperref#130]
I am trying to create underlined links with

`\usepackage[colorlinks = false, pdfborderstyle={/S/U/W 1}]{hyperref}`

but the output is still the default rectangle style. I am using TexShop on mac and it seems like this generally does not work for mac.

Is it possible to make to work?

Thanks!

**Comment by u-fischer** [comment]
~~~~
\documentclass{article}
\usepackage[colorlinks = false, pdfborderstyle={/S/U/W 1}]{hyperref}
\begin{document}
some text \url{https://www.latex-project.org}
\end{document}
~~~~

shows for me in sumatra and adobe reader on windows this:

![image](https://user-images.githubusercontent.com/4047173/76686945-e3cb6b00-661f-11ea-978f-ca92d7ac1401.png)

But the support of such border styles depends on the pdf viewer. It is quite possible that your viewer ignores the settings. There is nothing that hyperref can do here.

**Comment by zhyiyu** [comment]
Thanks!
