### ISSUE TITLE
Backref and multibib

### ISSUE THREAD

**Issue by zazarara** [latex3/hyperref#132]
Hy,

A have a issue while using hyperref with backref option and multibib.
Indeed the bibliography created by newcite{}{} has no backreferences...

Someone ha the solution?

Thanks

**Comment by u-fischer** [comment]
This here is a bug tracker, it is not meant for general support. If you think you found a bug please provide a small complete document that demonstrates it and can be used for tests. If you want general help ask on support sites like tex.stackexchange.com.

**Comment by zazarara** [comment]
Yes, it is a bug.
Find enclosed the MWE.

> \documentclass[a4paper,11pt,twoside]{book} 
\usepackage[utf8]{inputenc}    % pour les accents 
\usepackage[T1]{fontenc}
\usepackage[table]{xcolor}

\definecolor{bleu}{rgb}{.06, .39, 0.71}
\usepackage[pdftex,pdfborder={0 0 0},
      colorlinks=true,
      linkcolor=bleu,
      citecolor=bleu,
      urlcolor=bleu, %violet
      pagebackref=true,
      breaklinks=true,
      naturalnames=true,
      linktoc=all
      ]{hyperref}  

% multi bibliographies
\usepackage{multibib}
     
% Page des citations
% \renewcommand*{\backreflastsep}{, }
\renewcommand*{\backreflastsep}{ et }
\renewcommand*{\backreftwosep}{, }
\renewcommand*{\backref}[1]{}
\renewcommand*{\backrefalt}[4]{%
   \ifcase #1 %
%     No citations.% use \relax if you do not want the "No citations"
%     message
     \relax
   \or
     Cité à la page~#2.%
%      Cité p. #4.%
   \else
     Cité aux pages~#2.%
%      Cité aux pages #4.%
   \fi%
 }

 
% for multi bibliographies
\newcites{mesrefs}{Bibliographie personnelle}

\begin{document}
 

\citemesrefs{RAB_CMAME07}
\cite{Lumley1967}

%%%%%%%%%%%%%%%%%%%
%% Bibliographie
%%%%%%%%%%%%%%%%%%  
\renewcommand{\bibname}{Bibliographie}
\bibliographystyle{apalike-fr}
\bibliography{bib1}
% \renewcommand{\bibname}{Références bibliographiques personnelles}
%
\bibliographystylemesrefs{alpha-fr}
\bibliographymesrefs{bib2}

%\backmatter  

\end{document}

> bib1.bib
@incollection{Lumley1967,
  address = {Moscow},
  author = {Lumley, J. L.},
  booktitle = {Atmospheric turbulence and radio propagation},
  citeulike-article-id = {592403},
  editor = {Yaglom, A.M. and Tatarski, V.I.},
  keywords = {homogeneous},
  pages = {166--178},
  posted-at = {2006-04-20 16:40:24},
  priority = {2},
  publisher = {Nauka},
  title = {{The Structure of Inhomogeneous Turbulent Flows}},
  year = {1967}
}

> bib2.bib
@article{RAB_CMAME07, 
author="I. Rami\`ere and Ph. Angot and M. Belliard",
title="A fictitious domain approach with spread interface for elliptic problems with general boundary conditions",
journal="Computer Methods in Applied Mechecanics and Engineering, vol. 196 (4-6), pp.766-781",
year="2007"}

**Comment by zazarara** [comment]
In this exemple, the "classical" bibliography has back references but not the second one created with newcite
[MWE.pdf](https://github.com/latex3/hyperref/files/4359830/MWE.pdf)

**Comment by u-fischer** [comment]
Yes, multibib is not supported. But I'm not sure if this is something that should be addressed in backref, it looks more like a multibib issue. Why don't you use biblatex + biber instead of multibib? It offers multiple bibliographies and backref out of the box.

**Comment by zazarara** [comment]
It is maybe a multibib issue...
I will try to find the multibib community.
I do prefer bibtex rather than biblatex.
Regards

**Comment by zazarara** [comment]
I really think, it is a backref package problem, since the line 
\@writefile{brf}{\backcite{RAB_CMAME07}{{1}{(document)}{Doc-Start}}}
appears in the second .aux file, but it does not generate the brf associated file.

**Comment by u-fischer** [comment]
Well backref can't know that multibib is redirecting the aux-file handler locally. But you could try this after loading backref.

~~~~
\usepackage{etoolbox}
\makeatletter
\patchcmd\Hy@backout{\@auxout}{\@mainaux}{}{\fail}
\patchcmd\Hy@backout{\@auxout}{\@mainaux}{}{\fail} %yes twice the same line
\makeatother
~~~~

**Comment by zazarara** [comment]
Thanks a lot!!!
That works pretty well!

Thanks again.
