### ISSUE TITLE
allow non-RGB colours

### ISSUE THREAD

**Issue by viktoriasee** [latex3/hyperref#133]
### Description
When you create a document with current hyperref it assumes the document is RGB. While this may be the choice for some, PDF from version 1.6 on is open to N channel profiles (1 gray, 3 RGB, 4 CMYK, 5+ other). This bug and a [workaround are available on stackexchange](https://tex.stackexchange.com/questions/227429/pdf-a-with-cmyk-how) for four years now. 

Afaik, with current hyperref it's not possible to produce CMYK PDF with colored link borders.

### minimal example
```latex
\documentclass{article}
\usepackage[pdfa]{hyperref}

\makeatletter
\immediate\pdfobj stream attr{/N 4} file{UncoatedFOGRA29.icc}
\edef\iccobj{\the\pdflastobj}
\pdfcatalog{%
  /OutputIntents [ <<
    /Type /OutputIntent
    /S /GTS_PDFA1
    /DestOutputProfile \iccobj\space 0 R
    /OutputConditionIdentifier (Uncoated FOGRA29)
    /Info (FOGRA29L)
  >> ]
}
\makeatother

\begin{document}

This is a hyperlink: \url{http://google.com/}

\end{document}
```
This leads to an error because the box around the link is defined by three values (intended for RGB) but the default profile is four channel CMYK.

### workaround
In the above example, put the following code before `\makeatother`:
```latex
\usepackage{etoolbox}
\patchcmd{\hyper@linkurl}{/C[}{/K[}{}{}
```
However, this creates black frames which may not be the user's choice.
 
### Desired behaviour
Let the user define link colours in other formats than RGB. I.e.:
```latex
\hypersetup{%
	colorchannels=4,
	urlbordercolor={1 0.5 0.25 0.1}
}
```

### Other packages
As far as I know, the usage of package `xcolor` does not help here.

**Comment by u-fischer** [comment]
I do find it rather odd to force cmyk for something that is useful only on a screen. 
The workaround looks wrong, it replaces `/C` by the unknown key `/K` and so basically simply removes the color. You can switch to cmyk like this:

~~~~
\documentclass{article}

\usepackage{l3pdf}
\ExplSyntaxOn
\pdf_uncompress:
\ExplSyntaxOff
\usepackage[cmyk]{xcolor}
\usepackage{hyperref}
\makeatletter
\let\HyColor@HyperrefBorderColor\HyColor@XZeroOneThreeFour
\hypersetup{urlbordercolor=red}
\makeatother
\begin{document}

This is a hyperlink: \url{http://google.com/}

\end{document}
~~~~

This will give this annot:

~~~~
<<
/Type /Annot
/Border[0 0 1]/H/I/C[0 1 1 0]
/Rect [236.965 654.025 333.104 665.15]
/Subtype/Link/A<</Type/Action/S/URI/URI(http://google.com/)>>
>>
~~~~

You will have to reset every color as the default definitions are in rgb. 

But the border color doesn't look red in my pdf viewer, but more light blue. So I'm not sure if the viewers handle this correctly.

**Comment by viktoriasee** [comment]
> I do find it rather odd to force cmyk for something that is useful only on a screen.

I agree. Those borders are not printing. I am trying to create a media neutral documents that look the same on paper and on screen. In this regard, CMYK is a good choice because it's a generally smaller colour space. However, without the patch I suggested I get a preflight error in Acrobat DC for PDF/A-1b:
![hyperref-preflight-error](https://user-images.githubusercontent.com/11464744/77261770-4a403100-6c91-11ea-91fa-308bd6535d3c.png)
I even get this error when I use `\usepackage[pdfa,hidelinks]{hyperref}`! In other words a colour error for something that is not visible.

Your workaround does not work. Acrobat interprets the first three values as RGB ignoring the fourth. Thus the light blue color.

I agree the case of non printing link borders is maybe a bad example I should have taken text link colour.

**Comment by u-fischer** [comment]
If adobe interprets the color as rgb it is imho a bug - the specification clearly says that a four number array is cmyk. You could try to cheat and set the color to cyan and hope that adobe shows red. 

The text color of links is a quite different question, this is not set in the annotation dictionary. It should be easy to adapt if it isn't already in cmyk (to late to test now)

**Comment by viktoriasee** [comment]
### Different behaviour of viewers
When I use cyan in your example I get `/C[1 0 0 0]`. The output is:
* red in Acrobat DC
* red in SumatraPDF 2.4
* no frame in SumatraPDF 3.2
* no frame in Microsoft Edge
* no frame in Google Chrome 
* black frame in miktex-texwork viewer

I am confused, which one if at all is right? Not one viewer shows a cyan frame! I was not aware PDFs look so different in different viewers.

### Preflight error
The link as in my minimal example looks like this:
```pdf
<<
	/Type/Annot
	/Border[0 0 1]
	/H/I/C[0 1 1] 
	/Rect [ 236.971 653.958 333.111 665.146 ]
 	/Subtype/Link
 	/A<<
 		/Type/Action
 		/S/URI
 		/URI(http://google.com/)
 	>>
>>
```
This gives the preflight error shown above. When I convert the file in Acrobat DC to PDF/A-1b I get:
```
<<
	/Type/Annot
	/Border[0 0 1]
	/H/I/C[0 1 1]
	/Rect[236.971 653.958 333.111 665.146]
	/Subtype/Link
	/A<<
		/S/URI
		/Type/Action
		/URI(http://google.com/)
	>>
	/AP<</N 17 0 R>>
	/F 4
>>
```
So the difference are the `/AP` and `/F` flag. According to the [ISO 32000-2 spec p. 464](http://intranet.pdfa.org/wp-content/uploads/2016/08/ISO_DIS_32000-2-DIS4.pdf#page=461) `/F 4` is a print flag (dec 4=bin bit 3). `/AP` is an *appearance dictionary* with `/N` defining the normal appearance. I do not know what the values `17 0 R` stand for.

### Rephrasing of the issue
1. How would a workaround look to create links with an `/AP` and `/F` flag?
2. Are you willing to modify `hyperref` in order to create standard compliant links?

**Comment by u-fischer** [comment]
> I am confused, which one if at all is right?

None. As I already wrote: according to the reference, if the C array has four entries it should be interpretated in the /DeviceCMYK color space. If no viewer does it, it is a viewer problem. 

But a RGB border is quite allowed in pdfa. So if you get an error you should perhaps reconsider your color settings instead of trying to tweak the link.

> I do not know what the values `17 0 R` stand for.

17 0 R is an object which defines the appearance, normally a xform object. 

> 1. How would a workaround look to create links with an `/AP` and `/F` flag?

You get the /F flag if you use the pdfa option of hyperref. hyperref has currently no hook or code to add an /AP dictionary. With the experimental driver and pdfresources they can be added. But appearances are boxes, they don't combine well with line breaking in links and I don't have the impression that  viewers are actually making use of them. 

> 2. Are you willing to modify hyperref in order to create standard compliant links?

You can already create standard compliant links. The nonstandard thing here is your handling of the colors and not the hyperref output. Beside this: as I already wrote we are working on extending hyperref.

**Comment by viktoriasee** [comment]
Yes the `pdfa`option creates the `/F` entry but that does not eliminate the preflight error.

Please don't tell me which type of colour space I have to use. There are numerous reasons to use non-RGB colour spaces and they are perfectly allowed (sometimes even mandated) in PDF.

> The nonstandard thing here is your handling of the colors and not the hyperref output.

You mix standard and default. PDF standards allow N colour channels and `hyperref` currently supports just N=3. And if you use N≠3 you don't get a compiler warning just a erroneous PDF.

> as I already wrote we are working on extending hyperref.

So everything is fine then. Put the issue in your roadmap, get it done. Take the next piece of cake.

**Comment by u-fischer** [comment]
> PDF standards allow N colour channels and `hyperref` currently supports just N=3. And if you use N≠3 you don't get a compiler warning just a erroneous PDF.

No you don't get an erroneous PDF. You get a perfectly valid PDF with settings that the viewers don't handle correcty. The only correct way to get cmyk in the border color is to use a four number array for the /C key. I showed you how to do this. If the result isn't to your liking you will either have to drop your wish to get cmyk here or pester the pdf viewers to correctly support this settings. 

> Put the issue in your roadmap, get it done. Take the next piece of cake.

Stay polite. Don't forget that this here is voluntary work and done in our free time.  Fullfilling wishes for unusual color settings will not get a higher priority only because  of your pushing.

**Comment by viktoriasee** [comment]
@u-fischer : Relax. It was no way my intention to appear impolite. I know there is plenty of voluntary work included here, so is my work. Please understand if I am a little impatient. We are after all twelve years after ISO 32000-1 has been released and some things still don't work conveniently in LaTeX. That's a long time in software development.

The workaround you provided is actually pretty cool. I did not notice in the first place because your minimal example still threw validation errors. I agree that there is a [bug in Acrobat DC](https://acrobat.uservoice.com/forums/590923-acrobat-for-windows-and-mac/suggestions/40014586-show-correct-colours-for-cmyk-annotations), I filed a report.

### new minimal example
Here is a minimal example that completely validates as PDF/A-1b in Acro DC, either pdfLaTeX or LuaLaTeX, based on Ulrike's fix:
```latex
\documentclass{article}

\usepackage[cmyk]{xcolor}
\usepackage[pdfa]{hyperref}
\usepackage{hyperxmp}[2020/01/01]

% This section is not needed for MikTeX, maybe for Texlive
%\usepackage{l3pdf}
%\ExplSyntaxOn
%\pdf_uncompress:
%\ExplSyntaxOff

\makeatletter
\immediate\pdfobj stream attr{/N 4} file{UncoatedFOGRA29.icc}
\edef\iccobj{\the\pdflastobj}
\pdfcatalog{%
  /OutputIntents [ <<
    /Type /OutputIntent
    /S /GTS_PDFA1
    /DestOutputProfile \iccobj\space 0 R
    /OutputConditionIdentifier (Uncoated FOGRA29)
    /Info (FOGRA29L)
  >> ]
}
\let\HyColor@HyperrefBorderColor\HyColor@XZeroOneThreeFour
\makeatother

\hypersetup{%
    pdftitle=Title,
    pdfapart=1,
    pdfaconformance=B,
    urlbordercolor=red
}

\begin{document}

lorem ipsum \url{https://tex.stackexchange.com/}

\end{document}
```

**Comment by u-fischer** [comment]
The new PDF management code and the new hyperref driver it contains allow to change the border color model. You have to reset the colors after a change, e.g. by (re)loading a colorscheme.  

The primitive `\pdfcatalog` should not used with the new code.  Outputintents must be added to the catalog with `\pdfmanagement_add:nnn{Catalog}`. The new code contains already support for colorprofiles and outputintent, (currently only sRGB.icc and FOGRA39L_coated.icc are supported, I still need to decide about the interface for other).

~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata
 {
  uncompress,
  pdfstandard=A-2b,
  colorprofiles={A=FOGRA39L_coated.icc}
  }
\documentclass{article}  
\usepackage{hyperref}

\hypersetup{bordercolormodel=cmyk,colorscheme=phelype}
\begin{document}

This is a hyperlink: \url{http://google.com/}

\end{document}
~~~~

will give 

~~~~
<<
/Type /Annot
/Border [0 0 1] /H /I /C [0 0.324708 0.007062 0.275292] /F 4 
/Rect [236.965 703.915 333.104 715.04]
/Subtype/Link/A<</Type /Action /S /URI /URI (http://google.com/) >>
>>
~~~~

The standard drivers will not be extended to do this too.
