### ISSUE TITLE
Consider optional argument of polyglossia \text<lang> in TOC

### ISSUE THREAD

**Issue by jspitz** [latex3/hyperref#135]
Currently, the optional argument is written verbatim to the (PDF) TOC, as in `the [variant=british]colour of life` in the MWE that follows.
```tex
% !TeX TS-program = xelatex
\documentclass{article}

\usepackage[pdfusetitle,bookmarks=true]{hyperref}

\usepackage{polyglossia}
\setdefaultlanguage{english}

\begin{document}

\section{The \textenglish[variant=british]{colour} of life}
\end{document}
```

**Comment by jspitz** [comment]
PS. If this is something we need to fix on the `polyglossia` side, please let me know.

**Comment by u-fischer** [comment]
That is something that polyglossia should handle. hyperref can not start to check the language setup of polyglossia and add suitable replacements for the bookmarks. 

But consider if this is really needed. The number of documents which are using the optional argument like this in a heading is probably rather slim.  A manual `\texorpdfstring` is normally better than enlarging \pdfstringdef with almost never needed cases. 

But if you really want something like this should work:

~~~~
\documentclass{article}

\usepackage[pdfusetitle,bookmarks=true]{hyperref}

\usepackage{polyglossia}
\setdefaultlanguage{english}
\usepackage{xparse}

\makeatletter
\NewExpandableDocumentCommand\xpg@gobbleoptarg{om}{#2}
\pdfstringdefDisableCommands{\let\textenglish\xpg@gobbleoptarg}
\makeatother
\begin{document}

\section{The \textenglish[variant=british]{colour} of life}
\end{document}
~~~~

**Comment by jspitz** [comment]
Thanks. Alas it's needed as for instance LyX outputs language markup in the headings (see https://www.lyx.org/trac/ticket/11813), and making it care for `hyperref` and fiddling with `\texorpdfstring` would be a much larger pain.

**Comment by u-fischer** [comment]
Well I don't agree that this is not a lyx bug. Why on earth does it add the optional argument? It doesn't make sense to do this by default. Optional argument are *optional*.

**Comment by davidcarlisle** [comment]
I would agree with @u-fischer  that this should preferably be fixed in lyx, or failing that in polyglossia, certainly it is not something hyperref can address as producing bookmarks from such a command requires knowledge of the intention of the command. It's enough here to ignore the argument but in general that won't be the case.

Closing the lyx bug report seems premature.

**Comment by jspitz** [comment]
> Well I don't agree that this is not a lyx bug. Why on earth does it add the optional argument? It doesn't make sense to do this by default. Optional arguments are _optional_.

If a user selects British English and the default is American English, we need to output the variant argument. Perhaps not in the case of the bug report, but in many other cases.

**Comment by davidcarlisle** [comment]
No surely you can specify British English at the document level not in each individual section.

**Comment by jspitz** [comment]
> No surely you can specify British English at the document level not in each individual section.

Sure, but consider the case where the document default language needs to be US English, and british only for specific parts (say a British quote in a heading).

**Comment by u-fischer** [comment]
What do you mean by "select"? If the user selects it as default language than lyx should setup the default language correctly. The optional argument would only be sensible if a user selects locally a different language and how often does this happen?

**Comment by jspitz** [comment]
> What do you mean by "select"? If the user selects it as default language than lyx should setup the default language correctly. The optional argument would only be sensible if a user selects locally a different language 

That's the case I am talking about.

> and how often does this happen?

Well, being a linguist by training, I'd say: often enough.

**Comment by u-fischer** [comment]
In the heading there is normally no hyphenation, so specifying the variant is seldom needed. If lyx overdoes here it can imho overdo more and add \texorpdfstring.

**Comment by davidcarlisle** [comment]
The cases where you have linebreaking requiring different hyphenation mid-phrase in a section heading must be vanishingly rare even for linguists:-) having hyphenation at all in a section heading is pretty odd.  But even if occurred in many documents doing the right thing in a pdf string with any markup command needs to be handled differently for each command so needs to be specified along with the main typesetting  definition it's not something hyperref can do except for a few core legacy commands, Otherwise hyperref will just grow uncontrollably having to support every contrib package on ctan.

**Comment by jspitz** [comment]
It's not only about hyphenation. Setting the language variant properly is also needed for proper spellchecking and to get localization (caption and date strings) right. On a more conecptual level, I think proper variant setting is also part of proper semantic markup.

But I see this discussion does not lead us anywhere.
