### ISSUE TITLE
hyperref warning about \thinspace?

### ISSUE THREAD

**Issue by kberry** [latex3/hyperref#136]
Would it be feasible to teach hyperref about \thinspace, so it doesn't emit useless warnings when used inside, e.g., \section? It comes up a lot. As in:

```
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\section{X\thinspace Y}
\end{document}
```

which results in:
```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\leavevmode@ifvmode' on input line 4.


Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                \kern 1.66672pt
(hyperref)                removed on input line 4.
```

Since \thinspace doesn't generally need anything in the text case, it's a bit aggravating to have to sprinkle \texorpdfstring everywhere just for this.

Clearly nothing crucial, just thought it might be easy enough to be worthwhile. --thanks,karl.

**Comment by u-fischer** [comment]
You can always disable such commands yourself to the hook: 

~~~~
\documentclass{article}
\usepackage{hyperref}
\pdfstringdefDisableCommands{\let\thinspace\relax}
\begin{document}
\section{X \thinspace Y}

\end{document}
~~~~

Adding a command by default to hyperref's list should be done only if a signicificant amount of document actually use the command in section commands - every additional command slows down the processing.

**Comment by davidcarlisle** [comment]
also it's not clear what the default text should be:  you hint that an empty string is OK but in other contexts it might need a space or a thin space such as U+2009 (not sure all readers handle that well in bookmarks though)

**Comment by kberry** [comment]
thanks for the hint about \pdfstringdefDisableCommands. No reason for any of us to spend more time on this.
