### ISSUE TITLE
Conversion of keywords in LuaTeX

### ISSUE THREAD

**Issue by viktoriasee** [latex3/hyperref#139]
I want to reuse the variable \pdfkeywords in a text. This works well in pdfTeX but in LuaTeX the content is somehow unicode-escaped:
![hyperref-unicode](https://user-images.githubusercontent.com/11464744/80277203-b4fbe680-86ed-11ea-9c24-8017ceb60f3a.png)

### MWE
```latex
\documentclass{article}

\usepackage{hyperref}

\author{first author, last author}

\hypersetup{%
		pdfkeywords={Key1}
}

\begin{document}
\makeatletter
Author: \@author

Keywords: \@pdfkeywords
\makeatother
\end{document}
```

**Comment by u-fischer** [comment]
the value of pdfkeywords is passed directly through \pdfstringdef. It is not meant for general use. 
Something like this should work if you want to set the keys only in one place:
~~~~
\newcommand\mykeywords{Key1}
\hypersetup{%
		pdfkeywords={\mykeywords}
}
~~~~
