### ISSUE TITLE
hyperref's patch to equation is only partial when amsmath is loaded

### ISSUE THREAD

**Issue by jfbu** [latex3/hyperref#14]
This issue was raised at http://tex.stackexchange.com/questions/235665/incorrect-spacing-after-minus-sign-with-combination-of-amsmath-and-hyperref. I commented upon it in my answer at http://tex.stackexchange.com/a/235715. Following code gives wrong spacing around first unary minus.

``` latex
\documentclass{article}
\usepackage{amsmath}
\usepackage{hyperref}
\begin{document}
\begin{equation}
  -1 = -1 % output: - 1 = -1
\end{equation}
\end{document}
```

For some reason the patch to equation done by hyperref is seemingly partial, when amsmath is loaded.

In my answer http://tex.stackexchange.com/a/235715 I mention a similar but non-related to hyperref problem, involving amsmath and it is now bug report https://www.latex-project.org/cgi-bin/ltxbugs2html?pr=amslatex/4461&category=AMS+LaTeX&responsible=anyone&state=open&keyword=&search=

**Comment by u-fischer** [comment]
This has been corrected. The output looks like this now:

![image](https://github.com/latex3/hyperref/assets/4047173/beb5a1bd-79f8-4c25-a04c-4105598cc371)
