### ISSUE TITLE
Page break occuring in a link in a footnote leads to  most of the next page connected with the link.

### ISSUE THREAD

**Issue by ppasedach** [latex3/hyperref#147]
```
\documentclass{article}
\usepackage{lipsum}
\usepackage{hyperref}
\begin{document}
\lipsum[1]\footnote{\lipsum[2-4]}
\lipsum[3]
\footnote{\lipsum[2] XXX\\
XXX\\
XXX\\
XXX\\
\href{mailto:nobody@nowhere}{nobody@nowhere. Some more blabla to make this go on the next page. And something more here.} \lipsum[2-5]}
\lipsum[1-5]
\end{document}
```

![Selection_045](https://user-images.githubusercontent.com/11517856/87407746-dcfb3780-c5c2-11ea-8f2a-802c0220a9d0.png)

**Comment by u-fischer** [comment]
Yes that is known, but there isn't anything hyperref can do here currently. There will probably in the next pdftex version a primitive which will allow to interrupt the link in such cases but it will take time until this is in the tex systems and the code to make use of it in the footnote code. So better avoid breakable links in footnote for now.

**Comment by u-fischer** [comment]
In a current texsystem this problem can be resolved by loading the PDF management and a patch for the output routine through a testphase code:

~~~~
\DocumentMetadata{testphase=new-or-1} %loads pdfmanagment + output patch
\documentclass{article}
\usepackage{lipsum}
\usepackage{hyperref}
\begin{document}
\lipsum[1]\footnote{\lipsum[2-4]}
\lipsum[3]
\footnote{\lipsum[2] XXX\\
XXX\\
XXX\\
XXX\\
\href{mailto:nobody@nowhere}{nobody@nowhere. Some more blabla to make this go on the next page. And something more here.} \lipsum[2-5]}
\lipsum[1-5]
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/201531398-4f1cf171-d503-4e03-9bbb-7be257a25f40.png)
