### ISSUE TITLE
Multiple Form environments per file

### ISSUE THREAD

**Issue by septatrix** [latex3/hyperref#151]
In the documentation it says that only one Form environment is allowed per file. I did try to use multiple and have not run into any issues yet.

Should this be a limitation of hyperref I would like open this issue as a feature request. If it however is stated in the PDF spec I think it would be good to reference it and either disallow multiple form environments or generate a warning should multiple ones be used.

**Comment by u-fischer** [comment]
Why should you want more than one? The environment initializes a number of objects needed for form fields, putting them twice in the pdf doesn't make any sense at all.

**Comment by septatrix** [comment]
I have two different forms inside the document with multiple pages in between. These should not be treated as the same (regarding action and overlapping names of fields)

**Comment by u-fischer** [comment]
that is not what Form does. It initialize mostly the main Form dictionary and the entry in the catalog, and so they can be only one. If you want to build field trees you will have to create the field objects yourself, there is no code for this in hyperref. But to avoid overlapping names it would be easier to use some prefix in the various parts.

**Comment by car222222** [comment]
This is explained as follows in Section 8.6 of The PDF Reference 1.7:

 A PDF document may contain any number of fields appearing on any combination of pages, all of which make up a single, global interactive form spanning the entire document.

**Comment by septatrix** [comment]
But everything still has to be in the form Form environment, correct? From what you say it seems to be valid to make an empty Form environment and just use all form fields afterwards

**Comment by u-fischer** [comment]
Imho simply using `\Form`  or `\Form[options]` should be enough. I have no idea why the manual suggest to use the command as environment. The only effect it has is to add an additional group, and I never saw anything in the code which looked as if it would need grouping. Try it out, and report back if something breaks ...

**Comment by septatrix** [comment]
So far everything seems to work. It may be a good idea to adjust the section in the documentation to also state `\Form` as an alternative.
