### ISSUE TITLE
Wrong pdfinfo tags and bookmarks encoding with pdfencoding=true and luatex

### ISSUE THREAD

**Issue by nicolasmeric** [latex3/hyperref#155]
If one sets the pdfencoding option to auto using hypersetup, it leads to a wrong encoding of the pdf bookmarks and the pdfinfo tags when using luatex.

Here is a MWE:
```latex
\documentclass{article}

\usepackage{hyperref}

\hypersetup{pdfencoding=auto,pdftitle={É}}

\begin{document}

\section{É}

\end{document}
```

If pdfencoding is not set, everything works fine, but this behavior does not comply with the documentation regarding the pdfencoding option:
> • auto PDFDocEncoding if the string does not contain characters outside the encoding and Unicode otherwise.
> The luatex driver uses unicode by default. If another encoding should be forced, it should be
done in hypersetup.

**Comment by u-fischer** [comment]
Well we changed the default encoding to unicode for lualatex as auto doesn't work well.  Why are you forcing this back?

**Comment by nicolasmeric** [comment]
Hello,
sorry for the delay.
I discussed this issue with the pdfx package maintainer.
The default configuration of pdfx sets up hyperref with this option.
Your answer led him to make these remarks:

> I’d ask for an explanation of what  ‘auto’  is really supposed to do.
And is it actually doing it correctly?
>
> Why is ‘auto’ now wrong with LuaTeX , for bookmarks?
>
> Are there, or have there been (?), circumstances under which
> packages would be expected to alter the value of  pdfencoding ?
>
>
> Personally, I’d prefer to not have to touch it.
> But past experience is behind why that line ever existed in  pdfx.sty .
>
> So some older installations may still need it.
> How do we test for whether it is now needed, or not?

When he speaks about a something to touch, he refers to the line which sets up pdfencoding in the pdfx source code.
Maybe you'll find his remarks interesting.

**Comment by u-fischer** [comment]
well I told him already last year that using `auto` for luatex is wrong: https://github.com/ho-tex/pdftexcmds/issues/3. The code to use PDFDOCencoding for accented chars doesn't work with the unicode engines. hyperref forces unicode for xetex but doesn't do it with luatex.

I changed this now, so in the next version hyperref will force it for luatex too and your example will work. But this won't mean that `auto` is then the right option: it means that hyperref has to check every string if it is pure ascii and this only slow downs the compilation only to save a few bytes, something that today shouldn't matter anymore.

**Comment by nicolasmeric** [comment]
Hello,
I didn't know you already talked about this with him.
It might be a good idea to add a little note in the manual to warn users and packages maintainers and discourage them from using this option with luatex.
Thanks for your explanations.

**Comment by u-fischer** [comment]
This has been resolved by the last updates.
