### ISSUE TITLE
Parameters must be numbered consecutively. \begin{document}

### ISSUE THREAD

**Issue by zoushucai** [latex3/hyperref#158]
eg: 
```
\documentclass[a4paper,11pt,final]{memoir}
\usepackage{hyperref}
\begin{document}
word
\end{document} 
```
Running error
```
Parameters must be numbered consecutively. \begin{document}
```

The operating environment is as follows:
```
MaxTex 2020（MACOS 14.04）,  package has been updated and was updated yesterday


```

**Comment by u-fischer** [comment]
This is a memoir problem. A fixed memoir has already been uploaded to ctan and should reach you soon.

**Comment by u-fischer** [comment]
As a work-around until the update is there, you can add 

         \renewcommand\AtEndPackage[2]{\def\temp{\AddToHook{package/after/#1}{#2}}\temp}

before loading hyperref.

**Comment by zoushucai** [comment]
@u-fischer  Thanks.

**Comment by zoushucai** [comment]
@u-fischer  Thanks.
