### ISSUE TITLE
PDF bookmarks in aea template

### ISSUE THREAD

**Issue by nurfatimaj** [latex3/hyperref#161]
Hello!

Could you please help me find out why hyperref package does not generate section bookmarks in the pdf document, when I use a custom document class. I have already posted a question to the team that provides the class, but I haven't received any answer in about a month. I have tried to examine the .cls file myself to see if there is anything obvious that prevents the pdf bookmarks, but I could not spot anything. I have updated all the packages, but the issue still persists. 

The document class I am talking about is AEA from American Economic Association. It can be found here: https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/aea/skeleton/AEA.cls. 

And just to be clear, whenever I use a standard article class, pdf bookmarks for section are generated perfectly fine (provided I clean up all the auxiliary files before). As soon as I change the document class to AEA, there are no longer pdf bookmarks. Here is a MWE:

```latex
\documentclass{AEA}

\usepackage{hyperref}

\begin{document}
	\section{Section 1}
	\subsection{Subsection 1}
	\section{Section 2}
\end{document}
```
I understand this question is somewhere in between the hyperref package and the AEA document class. If you could just give a look and suggest what could be going on, I'd be grateful! 

Thank you!

**Comment by u-fischer** [comment]
This is not a hyperref bug, better ask such questions one sites like tex.stackexchange. 

Beside this: the class doesn't use a table of contents, and so tocdepth is zero. Use 

       \usepackage[bookmarksdepth=3]{hyperref}

or 

     \setcounter{tocdepth}{3}

**Comment by nurfatimaj** [comment]
> This is not a hyperref bug, better ask such questions one sites like tex.stackexchange.
> 
> Beside this: the class doesn't use a table of contents, and so tocdepth is zero. Use
> 
> ```
>    \usepackage[bookmarksdepth=3]{hyperref}
> ```
> 
> or
> 
> ```
>  \setcounter{tocdepth}{3}
> ```

Thank you so much! The option solved it! :)
