### ISSUE TITLE
pdfLaTeX fails on pstool when hyperref is included

### ISSUE THREAD

**Issue by Tobster77** [latex3/hyperref#166]
Running pdfLaTeX from latest MikTeX (Windows) with psfragfig from the pstool package and hyperref leads to an error, while the same code works fine on TeXlive for me.

I reportet the issue already at the MikTeX repository, and they forwarded me here. @u-fischer was already involved in the discussion of the issue here https://tex.stackexchange.com/questions/570404/pdflatex-fails-on-pstool-when-hyperref-is-included and here https://github.com/MiKTeX/miktex/issues/660, and she informed me that her time is limited. In case some other maintainer of hyperref is interested, I just wanted to place the error report here.

A minimum example, EPS is attached in ZIP archive [take_any_EPS.zip](https://github.com/latex3/hyperref/files/5813363/take_any_EPS.zip):

\documentclass[12pt,a4paper]{article}
\usepackage[margin=2cm,a4paper]{geometry}
\usepackage{hyperref}

\title{psfrag in pdflatex }

\usepackage{graphicx}
\usepackage{pstool}
\usepackage{bookmark}

\begin{document}
Test
\begin{figure}[h!]
\centering
 \psfragfig[mode=errorstop,width=0.9\textwidth]{take_any_EPS}
 {
   \psfrag{t}[lc][lc]{psfrag}
 }
\caption{The EPS image with psfragfig}
\end{figure}

\end{document}
Now removing hyperref and bookmark resolves the issue and creates the correct PDF!

pdfTeX is version 3.14159265-2.6-1.40.21 on MiKTeX 20.11 Portable.
hyperref is version 7.00e from May 17, 2020.
pstool is version 1.5e from January 22, 2018.

**Comment by u-fischer** [comment]
well as said in the tex.sx answer this is not a hyperref bug. The problem must be solve in preview and pstool. Apart from this it compiles for me if I add the patches of the answer and provide a definition for the missing command:

~~~~
\documentclass[12pt,a4paper]{article}
\usepackage[margin=2cm,a4paper]{geometry}
\usepackage{hyperref}

\title{psfrag in pdflatex }

\usepackage{graphicx}
\usepackage{pstool}
\usepackage{bookmark}
\makeatletter
\providecommand\HyPL@Entry[1]{}
\AddToHook{env/document/begin}{%
\@ifpackageloaded{preview}{
\ifPreview
 \let\Hy@FirstPageHook\relax
 \let\Hy@EveryPageAnchor\relax
\fi}{}}
\makeatother
\begin{document}
Test
\begin{figure}[h!]
\centering
\psfragfig[mode=errorstop,width=0.9\textwidth]{take_any_EPS}
{
\psfrag{t}[lc][lc]{psfrag}
}
\caption{The EPS image with psfragfig}
\end{figure}

\end{document}
~~~~
