### ISSUE TITLE
How can I make the reference tag in the bookmark to refer to the right page

### ISSUE THREAD

**Issue by hangzhangust** [latex3/hyperref#168]
The reference bookmark generated by the hyperref did not go to the right page. How can I fix it?

**Comment by muzimuzhi** [comment]
Please be more specific, for example provide a [minimal working example](https://tex.meta.stackexchange.com/q/228). Also for usage questions rather than bug reports or feature requests, Q&A sites like tex.stackexchange.com are more recommended.

**Comment by u-fischer** [comment]
@muzimuzhi wrote: this isn't the right place for such usage questions and you aren't offering enough details, so I'm closing here.
