### ISSUE TITLE
Unclear documentation of pdfusetitle

### ISSUE THREAD

**Issue by septatrix** [latex3/hyperref#169]
The `pdfusetitle` option only seems to work when passed to hyperref during loading. Using it afterwards inside of `\hypersetup` does not work. Weirdly however this gives the output `Option 'pdfusetitle' has already been used,(hyperref) setting the option has no effect`.

I do not know if this is considered a bug but otherwise it would be nice to point out this limitation inside the documentation.

**Comment by u-fischer** [comment]
You get the warning for all options that can be used only as package options. 

I'm not happy with this option and wouldn't recommend to use it currently: it has to patch \title and \author and  for this make assumptions which aren't correct for all classes and packages. Better set the title for the PDF info with pdftitle.

**Comment by septatrix** [comment]
Thanks for the quick reply. Could the error message be changed to something more descriptive? I feel like that would help.

And regarding the usage in general: Yes I primarily set them explicitly anyway. However I was toying around a bit with metadata and was interested in what options override others etc.

**Comment by u-fischer** [comment]
It is not an error, only a warning. And no, one can't change it, it is the same for all options. But at some time the option will probably be disabled, it doesn't fit in future plans.
