### ISSUE TITLE
Default unicode=true breaks usage with platex

### ISSUE THREAD

**Issue by jfbu** [latex3/hyperref#171]
[Sphinx](www.sphinx-doc.org) uses `platex` has default for Japanese document. Next major release will switch to `uplatex`. But currently all users with an up-to-date latex installation see their Japanese document build fail with error

```
(/usr/local/texlive/2020/texmf-dist/tex/platex/pxjahyper/pxjahyper.sty

! Package pxjahyper Error: hyperref 'unicode' mode is not supported.

See the pxjahyper package documentation for explanation.
```

Could there be a way for hyperref to detect it is used with `platex` and avoid then setting `unicode=true`?

Relates: https://github.com/sphinx-doc/sphinx/issues/8859

**Comment by u-fischer** [comment]
probably. Can you please provide a minimal example?

**Comment by jfbu** [comment]
ok, turns out our template loads `pxjahyper`:
```
\documentclass{jsbook}
\usepackage{hyperref}
\usepackage{pxjahyper}
\title{こんにちは}
\date{2021年02月09日}
\author{JFB}
\begin{document}
\maketitle
\tableofcontents
\chapter{こんにちは}


\end{document}
```
(not extremely minimal...)

**Comment by u-fischer** [comment]
I pushed a fix. But I will wait one or two days before I upload to ctan, in case something else comes up.

**Comment by jfbu** [comment]
Thanks for quick fix. I confirm it fixes it on our side (meaning that pdf build, I don't read Japanese so can't say more).

**Comment by u-fischer** [comment]
The fix has been uploaded to ctan.
