### ISSUE TITLE
Russian with cleveref stopped working after latest puenc-changes

### ISSUE THREAD

**Issue by LSinev** [latex3/hyperref#175]
MWE
```
% !TeX program = xelatex

\listfiles
\documentclass[a4paper, 14pt]{memoir}
\usepackage{polyglossia}
\setmainlanguage[babelshorthands=true]{russian}
\setotherlanguage{english}
\setmainfont{PT Serif}
\newfontfamily\cyrillicfont{PT Serif}
\usepackage{hyperref}
\usepackage{cleveref}
\begin{document}
\section{Проверка связи}

Любя, съешь щипцы, "--- вздохнёт мэр, "--- кайф жгуч. Шеф взъярён тчк щипцы
с~эхом гудбай Жюль. Эй, жлоб! Где туз? Прячь юных съёмщиц в~шкаф. Экс-граф?
Плюш изъят. Бьём чуждый цен хвощ! Эх, чужак! Общий съём цен шляп (юфть) "---
вдрызг!

Любя, съешь щипцы, "--- вздохнёт мэр, "--- кайф жгуч. Шеф взъярён тчк щипцы
с~эхом гудбай Жюль. Эй, жлоб! Где туз? Прячь юных съёмщиц в~шкаф. Экс-граф?
Плюш изъят. Бьём чуждый цен хвощ! Эх, чужак! Общий съём цен шляп (юфть) "---
вдрызг!

\end{document}
```
errors like
```
! Undefined control sequence.
\@tempa ->\CYRP \cyrr \cyri \cyrl \cyro \cyrzh 
                                               \cyre \cyrn \cyri \cyre 
l.12 \begin{document}
```
log file 
[hyperref_bug.log](https://github.com/latex3/hyperref/files/5983985/hyperref_bug.log) (well, maybe not hyperref but cleveref, but with hyperref 7.00g things like this worked about a week ago)

**Comment by davidcarlisle** [comment]
oh that's surprising..

I'd need to trace exactly how cleveref is affecting things but I think if you put

`\let\CYRDZE\relax`

before loading hyperref then it will work as before.

**Comment by u-fischer** [comment]
It errors also without hyperref. And this here errors too:


~~~~
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage[babelshorthands=true]{russian}
\setmainfont{PT Serif}
\usepackage{cleveref}
\begin{document}
\label{test}\cpageref{test}
\end{document}
~~~~

**Comment by LSinev** [comment]
somehow old hyperref prevented cleverref fail. Wow!
[hyperref_700g.log](https://github.com/latex3/hyperref/files/5984232/hyperref_700g.log) (log of starting MWE with hyperref 7.00g)

**Comment by davidcarlisle** [comment]
@u-fischer  we could make the Cyrillic setup like the Greek and allow its loading to be forced with the psdextra option?

**Comment by davidcarlisle** [comment]
@LSinev  yes the change in hyperref is that (while makeing the code paths for luatex/xetex/pdftex more similar we changed things such that support for Cyrillic in bookmarks is only loaded if the Cyrillic support is loaded (commands `\cyr...` 

As Ulrike's example shows that is not correctly  set up with polyglossia+cleverref previously hyperref set up the Cyrillic but now it sees Cyrillic is not set up for normal text so it doesn't set up the bookmarks either.

We'll sort something out but the workaround I gave above should get the hyperref version working.

**Comment by LSinev** [comment]
Thank you!

**Comment by u-fischer** [comment]
@davidcarlisle  well we could. But basically we simply revealed a cleveref bug: It expands at begin document one of its russian fix names. hyperref prevented the error by providing fall back definitions for all cyrX commands, but even if we reenable this cleveref is still completly broken with russian. You need TU-definitions for the commands, not PU.

**Comment by davidcarlisle** [comment]
@u-fischer  yes I agree that this is a cleverref bug really in this case, but looking down the file I think there is only the usual "history" reasons why Cyrillic is treated with a fixed internal text but Greek is an external file and has an exposed option that forces loading

**Comment by u-fischer** [comment]
@davidcarlisle  the bookmarks are not a problem.  hyperref doesn't need the PU-definitions to handle something like `\section{Проверка связи}`.

**Comment by davidcarlisle** [comment]
@u-fischer  yes I know, yes OK let's leave it for now and push it to cleverref...  (although normalising the treatment of the extensions might make sense at some point)

**Comment by u-fischer** [comment]
> (although normalising the treatment of the extensions might make sense at some point)

Well greek got only the special treatment, as some of it commands are used in psdextra and through it in math..

**Comment by davidcarlisle** [comment]
@u-fischer  "history" as I say... (but let's see if it gets fixed at cleveref)

**Comment by davidcarlisle** [comment]
@LSinev  can you report this to cleveref? You could reference this page The maintainer is apparently reachable at toby-cleveref@dr-qubit.org

**Comment by LSinev** [comment]
This email doesn't exist (as reported by mail server). Searching https://www.dr-qubit.org/cleveref.html pointed me to toby@dr-qubit.org (got from https://www.dr-qubit.org/email.html). But this email not responded yet (with spam protection reply), though maybe it needs PGP signed messages

**Comment by dbitouze** [comment]
> though maybe it needs PGP signed messages

AFAIR, no: Toby relies on a gray list.

**Comment by u-fischer** [comment]
> though maybe it needs PGP signed messages

I got a confirmation by a bot that my (unsigned) email got through when I sent a bug report some weeks ago. But I didn't get an answer, so I don't know if the bot said the truth ...

**Comment by LSinev** [comment]
@tsc25 (trying to invite Toby to this discussion thread by mentioning as emails do not respond for weeks)
> But basically we simply revealed a cleveref bug: It expands at begin document one of its russian fix names. hyperref prevented the error by providing fall back definitions for all cyrX commands, but even if we reenable this cleveref is still completly broken with russian. You need TU-definitions for the commands, not PU.

**Comment by u-fischer** [comment]
As it is a cleveref bug I close here.
