### ISSUE TITLE
puenc-greek.def duplicated/difference

### ISSUE THREAD

**Issue by kberry** [latex3/hyperref#177]
I guess a recent version of hyperref introduced a new version of the file puenc-greek.def. This also exists in greek-fontenc, and the two versions are different. So which one users will get is random. Have you talked with G\"unter Milde, who is maintaining greek-fontenc (afaik)? Thanks.

**Comment by u-fischer** [comment]
oh, damn. Yes that should be resolved, and as we came later, hyperref should probably choose another name for the greek block.

**Comment by kberry** [comment]
hopefully fixed within the next couple of weeks, at least? wouldn't be ideal for the final tl20 (or initial tl21) to be released with this conflict. thanks.

**Comment by davidcarlisle** [comment]
Yes sorry we got a bit sidetracked with the latex release. One possibility is simply to delete the hyperref one  (the greek-fontenc one is bigger but fine) but as Ulrike says we could keep both files and rename ours. We'll fix it asap..

**Comment by u-fischer** [comment]
A new version has been uploaded.
