### ISSUE TITLE
cleveref's poorman option and hyperref

### ISSUE THREAD

**Issue by dliessi** [latex3/hyperref#179]
I'm trying to use cleveref's poorman option, but the sed file it produces lacks the lines to substitute \cref commands if hyperref is loaded.
I tried with the following minimal example:
```
\documentclass{article}
\usepackage{hyperref}
\usepackage[poorman]{cleveref}
\begin{document}
\section{A}
\label{a}
\cref{a}
\end{document}
```
If I comment/remove hyperref, the sed files contains the line
```
s/\\cref{a}/\\cref@section@name \\nobreakspace \\ref {a}/g
```
otherwise it does not.

I'm using an up to date TeX Live 2020 on Linux, cleveref 2018/03/27 v0.21.4, hyperref 2021-02-10 v7.00j.
I'm not sure if this is a bug in cleveref or in hyperref: I also wrote to cleveref's author.

**Comment by u-fischer** [comment]
Sorry but this is clearly a cleveref problem. It writes the sed file, it knows that hyperref exists (and also tests for it) and if something fails it must be corrected in cleveref.
