### ISSUE TITLE
\url and \href commands have issues with utf8 characters

### ISSUE THREAD

**Issue by derMart** [latex3/hyperref#183]
I am using pdflatex on a standard texlive ubuntu distribution:
```
pdflatex --version
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)
```
Consider following minimal example:
```
\documentclass{article}%
\usepackage[utf8]{inputenc}%
\usepackage[unicode]{hyperref}%
\urlstyle{same}%

\begin{document}%
\url{https://test.com/’}\\%
\href{https://test.com/’}{https://test.com/’}\\%
\href{https://test.com/%E2%80%99}{https://test.com/’}%
\end{document}%
```
which compiles to:
![Screenshot from 2021-03-18 17-50-26](https://user-images.githubusercontent.com/1069456/111664919-91182680-8812-11eb-92bb-3b1a2c4960e6.png)

To my understanding, the url `https://test.com/’` is perfectly valid.
`\url` renders the special character incorrectly, also the link points to the incorrect url.
The first `\href` renders the url correctly, but the link incorrectly points to `https://test.com/\OT1\textquoteright`.
I was only able to get a workaround by the second `\href`, but this is not so nice, as one needs to url encode the special characters in the link.

**Comment by derMart** [comment]
For anyone interested, the workaround seems to work with the monospace font too:
```
\href{https://test.com/%E2%80%99}{\texttt{https://test.com/’}}\\%
```

**Comment by josephwright** [comment]
This works fine for me with the current release: `\listfiles` shows
```
 *File List*
 article.cls    2021/02/12 v1.4n Standard LaTeX document class
  size10.clo    2021/02/12 v1.4n Standard LaTeX file (size option)
inputenc.sty    2021/02/14 v1.3d Input encoding file
hyperref.sty    2021-02-27 v7.00k Hypertext links for LaTeX
 ltxcmds.sty    2020-05-10 v1.25 LaTeX kernel commands for general use (HO)
   iftex.sty    2020/03/06 v1.0d TeX engine tests
pdftexcmds.sty    2020-06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
kvdefinekeys.sty    2019-12-19 v1.6 Define keys (HO)
pdfescape.sty    2019/12/09 v1.15 Implements pdfTeX's escape features (HO)
 hycolor.sty    2020-01-27 v1.10 Color options for hyperref/bookmark (HO)
letltxmacro.sty    2019/12/03 v1.6 Let assignment for LaTeX macros (HO)
 auxhook.sty    2019-12-17 v1.6 Hooks for auxiliary files (HO)
kvoptions.sty    2020-10-07 v3.14 Key value format for package options (HO)
  pd1enc.def    2021-02-27 v7.00k Hyperref: PDFDocEncoding definition (HO)
hyperref-langpatches.def    2021-02-27 v7.00k Hyperref: patches for babel langu
ages
 intcalc.sty    2019/12/15 v1.3 Expandable calculations with integers (HO)
etexcmds.sty    2019/12/15 v1.7 Avoid name clashes with e-TeX commands (HO)
   puenc.def    2021-02-27 v7.00k Hyperref: PDF Unicode definition (HO)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
  bitset.sty    2019/12/09 v1.3 Handle bit-vector datatype (HO)
bigintcalc.sty    2019/12/15 v1.5 Expandable calculations on big integers (HO)
atbegshi-ltx.sty    2021/01/10 v1.0c Emulation of the original atbegshi
package with kernel methods
  hxetex.def    2021-02-27 v7.00k Hyperref driver for XeTeX
stringenc.sty    2019/11/29 v1.12 Convert strings between diff. encodings (HO)
rerunfilecheck.sty    2019/12/05 v1.9 Rerun checks for auxiliary files (HO)
atveryend-ltx.sty    2020/08/19 v1.0a Emulation of the original atvery package
with kernel methods
uniquecounter.sty    2019/12/15 v1.4 Provide unlimited unique counter (HO)
l3backend-xetex.def    2021-03-02 L3 backend support: XeTeX
  ts1cmr.fd    2019/12/16 v2.5j Standard LaTeX font definitions
 nameref.sty    2021-04-02 v2.47 Cross-referencing by name of section
refcount.sty    2019/12/15 v3.6 Data extraction from label references (HO)
gettitlestring.sty    2019/12/15 v1.6 Cleanup title references (HO)
    test.out
    test.out
```

**Comment by u-fischer** [comment]
No, the url is not valid. `’`  is U+2019 and clearly not ascii.  It must be percent encoded in the PDF (there are perhaps PDF viewer around which perhaps can it, but you can't rely on it).

With the current hyperref you will have to stick to the last version.

I just uploaded a new version of the new LaTeX pdfmanagement-testphase package which should be available tomorrow or the day after in a current texlive.  

With it you could do this (be aware that **testphase** means it is in the testphase, and it is not yet compatible with everything!):

~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass{article}
\usepackage{hyperref}
\urlstyle{same}

\begin{document}%
\hypersetup{href/urlencode,href/format=\rmfamily}

\url {https://test.com/’}\\%
\href{https://test.com/’}{https://test.com/’}

\end{document}
~~~~

This will give a percent encoded url in the pdf:

~~~~
/URI (https://test.com/%E2%80%99)
~~~~

and print like this:

![image](https://user-images.githubusercontent.com/4047173/111667283-d63d5800-8814-11eb-907b-8f24f12b357f.png)

This won't use the url package for the \url command, so hyphenation could be odd or different.

**Comment by derMart** [comment]
@josephwright  thanks, ok my `\listfiles` output is as follows:
```
 *File List*
 article.cls    2019/12/20 v1.4l Standard LaTeX document class
  size10.clo    2019/12/20 v1.4l Standard LaTeX file (size option)
inputenc.sty    2018/08/11 v1.3c Input encoding file
hyperref.sty    2020/01/14 v7.00d Hypertext links for LaTeX
 ltxcmds.sty    2019/12/15 v1.24 LaTeX kernel commands for general use (HO)
   iftex.sty    2019/11/07 v1.0c TeX engine tests
pdftexcmds.sty    2019/11/24 v0.31 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
kvdefinekeys.sty    2019-12-19 v1.6 Define keys (HO)
pdfescape.sty    2019/12/09 v1.15 Implements pdfTeX's escape features (HO)
 hycolor.sty    2020-01-27 v1.10 Color options for hyperref/bookmark (HO)
letltxmacro.sty    2019/12/03 v1.6 Let assignment for LaTeX macros (HO)
 auxhook.sty    2019-12-17 v1.6 Hooks for auxiliary files (HO)
kvoptions.sty    2019/11/29 v3.13 Key value format for package options (HO)
  pd1enc.def    2020/01/14 v7.00d Hyperref: PDFDocEncoding definition (HO)
 intcalc.sty    2019/12/15 v1.3 Expandable calculations with integers (HO)
etexcmds.sty    2019/12/15 v1.7 Avoid name clashes with e-TeX commands (HO)
   puenc.def    2020/01/14 v7.00d Hyperref: PDF Unicode definition (HO)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
  bitset.sty    2019/12/09 v1.3 Handle bit-vector datatype (HO)
bigintcalc.sty    2019/12/15 v1.5 Expandable calculations on big integers (HO)
atbegshi.sty    2019/12/05 v1.19 At begin shipout hook (HO)
 hpdftex.def    2020/01/14 v7.00d Hyperref driver for pdfTeX
atveryend.sty    2019-12-11 v1.11 Hooks at the very end of document (HO)
rerunfilecheck.sty    2019/12/05 v1.9 Rerun checks for auxiliary files (HO)
uniquecounter.sty    2019/12/15 v1.4 Provide unlimited unique counter (HO)
l3backend-pdfmode.def    2020-02-03 L3 backend support: PDF mode
 nameref.sty    2019/09/16 v2.46 Cross-referencing by name of section
refcount.sty    2019/12/15 v3.6 Data extraction from label references (HO)
gettitlestring.sty    2019/12/15 v1.6 Cleanup title references (HO)
    test.out
    test.out
 ***********
```
so it is a little different to yours. I am running Ubuntu 20.04, any chance this gets fixed for this LTS distribution?

**Comment by josephwright** [comment]
@derMart I'm afraid that's not how it works for LaTeX as-packaged by Ubuntu or other Linux systems. They take a TeX Live version, in your case TL'19, and once that stops getting package updates, that's it: you might see I guess some security-related binary fixes, but nothing else. So nothing will change until you get a system with TL'20 (or TL'21, in pretest right now).

**Comment by u-fischer** [comment]
@derMart Joseph compiled with xelatex. That helps for the printed output. It doesn't create valid in the PDF, so you are at the mercy of the PDF viewer if they work or not.

**Comment by derMart** [comment]
Ah, I see, thanks for the clarification. I sadly find many occasions where ubuntu's (debian's) internal package management is causing trouble. I remember also having a hard time upgrading the tex live distribution around the package management in the past, but that is getting OT.

@u-fischer Thank you for clarifying. Yes, of course you are right, it is not a valid URL. These things always confuse me.
Thanks also for you solution. If I understand right, that solution is equivalent to the \href workaround I've found, apart of course, that it automatically url encodes the link.

One thing remains: The questioned URL is not a URL according to the original RFC, but what Wikipedia calls an [Internationalized URL](https://en.wikipedia.org/wiki/URL#Internationalized_URL). According to that article, modern browsers do understand those IDN+IRIs, (which I will call Internationalized Resource Locators) IRL's and translate them to a URL in the background. So, to me this gives some motivation to also use IRL's in a pdf.

1. @josephwright If you write it works fine for you (in TL'20 (?)), does that mean the link in the pdf is a url encoded URL or an IRL?
2. If not, are there plans for the hyperref package to support IRL's, which, are understood by any modern browser?

**Comment by derMart** [comment]
> @derMart Joseph compiled with xelatex. That helps for the printed output. It doesn't create valid in the PDF, so you are at the mercy of the PDF viewer if they work or not.

So you mean that xelatex actually produces a IRI in the pdf? Any chance how to do that with pdflatex?

**Comment by u-fischer** [comment]
> So you mean that xelatex actually produces an IRI in the pdf? Any chance how to do that with pdflatex?

Yes, but you don't want it, as not all PDF viewer support this. In the annotation in the PDF you want percent encoded url, and so this is what the new hyperref driver will try to produce.

**Comment by derMart** [comment]
> In the annotation in the PDF you want percent encoded url, and so this is what the new hyperref driver will try to produce.

No, I want an IRI, as modern browsers will understand it.

**Comment by derMart** [comment]
> Yes, but you don't want it, as not all PDF viewer support this.
Just to be sure that there is no misunderstanding. What do you mean by support this?
That they convert between showing the IRI version to the user and sending the URL version to the browser?
If so, well according to wikipedia that is not needed anymore. If not, what else is there to support which can break?

**Comment by u-fischer** [comment]
> Just to be sure that there is no misunderstanding. What do you mean by support this?

It doesn't work. We tested non-ascii urls with a number of PDF viewer, OS and various encodings and only percent encoding is reliable (and is also what the PDF reference requires). Without it links either don't work or open the wrong pages.

**Comment by derMart** [comment]
@u-fischer Thank you for the explanation. Ok, I am convinced to not use IRIs in pdfs at the moment.

To recap and keep focused on the issue:
The desired behavior of `\url` command when hitting a non URL character is to show the IRI version as text to the user and write the % encoded URL version to the pdf annotation.
- Currently, on TL'19 with `pdflatex` that is completely broken as it shows the wrong text to the user and writes the wrong pdf annotation.
- In TL'20 (?) with `xetex` (@josephwright ) it is broken in a way that it shows the IRI to the user but also writes the IRI version to the pdf?

So my question is, which versions of tex live and compilers does this affect and will it be fixed someday (without the workaround from @u-fischer) just using standard procedure?

**Comment by u-fischer** [comment]
My code is not a work-around. It is the future. The pdfmanagement code will at some time be added to the latex kernel and hyperref will use the new code by default. It is currently only in a separate package to allow testing and give other packages the time to adapt to the new code.

**Comment by u-fischer** [comment]
There is nothing to fix here, so I'm closing.
