### ISSUE TITLE
Extra-line with backref, author-year citation in table p-column

### ISSUE THREAD

**Issue by P-Tse** [latex3/hyperref#184]
Hi,

I am using the backref=page option in hyperref with author-year citation. I noticed that when a citation is used at the start of the cell in a table with p alignment for columns, an extra line will appear at the start, before the citation.

Here's a MWE:

> \documentclass[]{article}
\listfiles
\errorcontextlines=\maxdimen
\usepackage[authoryear]{natbib}
\usepackage[backref=page]{hyperref}
\begin{filecontents}{\jobname.bib}
	@book{key,
		author = {Author, A.},
		year = {2001},
		title = {Title},
		publisher = {Publisher},
	}
\end{filecontents}
\begin{document}
\begin{table}
	\begin{tabular}{p{0.25\textwidth}|p{0.45\textwidth}}
		\hline
		\cite{key} & A \cite{key} 
	\end{tabular}
\end{table}
\bibliographystyle{apalike}
\bibliography{\jobname}
\end{document}

Here's the details of the version of the compiler:
> This is pdfTeX, Version 3.141592653-2.6-1.40.22 (MiKTeX 21.3) (preloaded format=pdflatex 2021.3.20)  20 MAR 2021 14:01
entering extended mode
**./document.tex
(document.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>

The file list is
> *File List*
 article.cls    2020/04/10 v1.4m Standard LaTeX document class
  size10.clo    2020/04/10 v1.4m Standard LaTeX file (size option)
  natbib.sty    2010/09/13 8.31b (PWD, AO)
hyperref.sty    2021-02-27 v7.00k Hypertext links for LaTeX
 ltxcmds.sty    2020-05-10 v1.25 LaTeX kernel commands for general use (HO)
   iftex.sty    2020/03/06 v1.0d TeX engine tests
pdftexcmds.sty    2020-06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
kvdefinekeys.sty    2019-12-19 v1.6 Define keys (HO)
pdfescape.sty    2019/12/09 v1.15 Implements pdfTeX's escape features (HO)
 hycolor.sty    2020-01-27 v1.10 Color options for hyperref/bookmark (HO)
letltxmacro.sty    2019/12/03 v1.6 Let assignment for LaTeX macros (HO)
 auxhook.sty    2019-12-17 v1.6 Hooks for auxiliary files (HO)
kvoptions.sty    2020-10-07 v3.14 Key value format for package options (HO)
  pd1enc.def    2021-02-27 v7.00k Hyperref: PDFDocEncoding definition (HO)
hyperref-langpatches.def    2021-02-27 v7.00k Hyperref: patches for babel langu
ages
 intcalc.sty    2019/12/15 v1.3 Expandable calculations with integers (HO)
etexcmds.sty    2019/12/15 v1.7 Avoid name clashes with e-TeX commands (HO)
   puenc.def    2021-02-27 v7.00k Hyperref: PDF Unicode definition (HO)
 backref.sty    2021/02/04 v1.41 Bibliographical back referencing
rerunfilecheck.sty    2019/12/05 v1.9 Rerun checks for auxiliary files (HO)
atveryend-ltx.sty    2020/08/19 v1.0a Emulation of the original atvery package
with kernel methods
uniquecounter.sty    2019/12/15 v1.4 Provide unlimited unique counter (HO)
bigintcalc.sty    2019/12/15 v1.5 Expandable calculations on big integers (HO)
     url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
  bitset.sty    2019/12/09 v1.3 Handle bit-vector datatype (HO)
atbegshi-ltx.sty    2020/08/17 v1.0a Emulation of the original atbegshi package

with kernel methods
 hpdftex.def    2021-02-27 v7.00k Hyperref driver for pdfTeX
l3backend-pdftex.def    2021-03-02 L3 backend support: PDF output (pdfTeX)
 nameref.sty    2021-04-02 v2.47 Cross-referencing by name of section
refcount.sty    2019/12/15 v3.6 Data extraction from label references (HO)
gettitlestring.sty    2019/12/15 v1.6 Cleanup title references (HO)
document.out
document.out
document.bbl

The only warning I received is 
> LaTeX Warning: File `document.bib' already exists on the system.
               Not generating it from this source.

Please let me know if you need any further information. Thanks a lot.

**Comment by u-fischer** [comment]
yes, with backref the citation writes  into the aux-file, but it doesn't switch to horizontal mode first. Use 
`\leavevmode\cite`.
