### ISSUE TITLE
Occasional warning of missing destination from pdfTeX

### ISSUE THREAD

**Issue by akiyks** [latex3/hyperref#186]
Recently, I noticed very occasional warnings from pdfTeX on TeX Live 2020 and 2021 saying:

> pdfTeX warning (dest): name{quickquizctr.13.1} has been referenced but does not exist, replaced by a fixed one
> 
> pdfTeX warning (dest): name{quickquizctrC.E.2.8} has been referenced but does not exist, replaced by a fixed one

There are hundreds of similar links in the document, but the other links are correctly handled.

There is no such warning when I downgrade hyperref to v7.00g.
hyperref versions v7.00j and v7.00k cause above warnings emitted.
v7.00h and v7.00i are not tested yet.

I suspect this is a regression in hyperref side.  But I might be missing something.

I'm afraid I'm not able to provide minimal code to reproduce, but if you need actual code to reproduce,
it is available at git://git.kernel.org/pub/scm/linux/kernel/git/paulmck/perfbook.git.

The update and reference of counters are done in the following manner (in qqz.sty).

```
\newcommand{\QuickQuiz}[1]{
	\begin{tcolorbox}[breakable]
	\refstepcounter{quickquizctr}
	\small\QuickQHeading{QQ}{QQA}{\thechapter.\thequickquizctr}
	{#1}
}

\newcommand{\QuickQ}[1]{
	\begin{tcolorbox}[breakable]
	\refstepcounter{quickquizctrC}
	\QuickQHeading{QQA}{QQ}{\QuickQuizAnswerChapter.\thequickquizctrC} \\
}

```

And the definition of \QuickQHeading is

```
\newcommand{\QuickQHeading}[3]{\hyperref[#2.#3]{\textbf{Quick Quiz #3:}}\label{#1.#3}}
```

The update of quickquzctr and quickquizctrC by \refstepcounter{} might be racy with
the reference of their values by \thequickquizctr and \thequckquizctrC.

Does anybody have a clue to resolve this?

**Comment by u-fischer** [comment]
I see nothing in the commits that would affect destinations. I took a look at your code but it is completly out-of-bound to use this to debug your problem. It loads tons of packages, and doesn't even compile for me on windows directly, I would have to wade through your makefile to understand what happens. 

Your snippets doesn't show the \label command so it is quite unclear how you create the targets for the `\hyperref`.

Unless you provide a sensible example I will have to close this as unclear.

**Comment by akiyks** [comment]
I see.
Can you wait a couple of days or a week for me to prepare a minimal example for you?
I'm not sure I can reproduce this issue in a small example, but I'll do my best.

By the way, do I need to reproduce on Windows?

Thank you for taking a look at this.
Regards,
Akira

**Comment by u-fischer** [comment]
Sure I have no problems to keep this open for now. You don't need to test on windows, if you reasonably can expect it to work there too it is quite ok. If I can't manage or can't reproduce the warning I can always ask for clarification.

**Comment by akiyks** [comment]
So, I managed to create a minimal working example to reproduce this symptom.
[mwe.zip](https://github.com/latex3/hyperref/files/6290925/mwe.zip)

Command to build (on Ubuntu, TeX Live 2021)
```
latexmk -pdf main.tex
```
With hyperref 7.00k, main.log contains the following two warnings:
```
Package tcolorbox Warning: Discard zero height first box part due to break problems (possible loss of zero height content) on input line 36.

pdfTeX warning (dest): name{quickquizctr.1.2} has been referenced but does not exist, replaced by a fixed one
```
With hyperref 7.00g, the log is clean of warning.

So, it appears there is some conflict between hyperref and tcolorbox when
the previous page is stretched to avoid orphan and the tcolorbox is forwarded
to the next page, and there is a destination at the top of the tcolorbox.

I hope you can reproduce them.

**Comment by u-fischer** [comment]
The change is cause by commit https://github.com/latex3/hyperref/commit/f59667380eef4f9ec2c3344dca6a4472c25ef599 which fixed issue #167. 

After this change a break can occur after at \refstepcounter issued in vertical mode, and it you case it means that tcolorbox discards it completly. 

Avoid to issue \refstepcounter in vertical mode---apart from your concrete problem it can also affect spacing as hyperref has to insert a whatsits. In your example the warnings go away if I switch to horizontal mode first:

~~~~
\newcommand{\QuickQuiz}[1]{
	\begin{tcolorbox}[breakable]
	\leavevmode\refstepcounter{quickquizctr}%<--- leavevmode
	\small\QuickQHeading{QQ}{QQA}{\thechapter.\thequickquizctr}
	{#1}
}
\newcommand{\QuickQuizAnswer}[1]{%
	\leavevmode\refstepcounter{quickquizctrE}%<--- leavevmode
	\hyperref[QQA.\thechapter.\thequickquizctr]{\rule{7pt}{7pt}}%
	\label{QQE.\thechapter.\thequickquizctrE}
	\end{tcolorbox}
}
~~~~

**Comment by akiyks** [comment]
Thank you!
So, does switching to horizontal mode work on older versions of hyperref such as those
found on Ubuntu 20.04 or 18.04 ?
I think they should, but just wanted to confirm.

**Comment by u-fischer** [comment]
It will work in the sense that you won't loose destinations or get errors. But it can change documents as \refstepcounter will no longer suppress a break point as described in the issue #167.

**Comment by akiyks** [comment]
Hmm.
I'll see if we need two variants of these macros, then.
Anyway, thank you very much for your help.

I'm closing this issue.
