### ISSUE TITLE
Provide a `\hrefstyle` acting on `\href`, similar to `\urlstyle`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/hyperref#195]
Sometimes, users may want that all the `\href` texts share a same style, for example `\ttfamily`. This could be achieved by, for example
```diff
diff --git a/hyperref.dtx b/hyperref.dtx
index 0a573a0..bb321c6 100644
--- a/hyperref.dtx
+++ b/hyperref.dtx
@@ -7611,7 +7611,7 @@
   \catcode`\#=12 %
   \gdef\href@$1{\expandafter\href@split$1##\\}%
   \gdef\href@split$1#$2#$3\\$4{%
-    \hyper@@link{$1}{$2}{$4}%
+    \hyper@@link{$1}{$2}{\csname hrefstyle\endcsname{$4}}%
     \endgroup
   }%
 \endgroup
```
Then `\newcommand*\hrefstyle{\texttt}` will do the work.

Similarly, A `\hyperstyle` could be provided for `\hyperref`.

**Comment by u-fischer** [comment]
\href creates quite a variety of link types and it is quite unclear if a single command is really usefull, even more as a number of packages (starting with url) try to add some formatting too. 

With the new pdfmanagement you can use the hooks (protect must be reset first here):

~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass{article}

\usepackage{hyperref,color}

\begin{document}


\AddToHook{pdfannot/link/URI/begin}{\let\protect\relax\ttfamily\color{red}}
\AddToHook{pdfannot/link/GoToR/begin}{\let\protect\relax\ttfamily\color{green}}

\href{https://www.latex-project.org}{uri  link}

\hrefurl{https://www.latex-project.org}{uri  link}

\href{manual.pdf}{file (GoToR) link}

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/124652379-5f4bce00-de9c-11eb-9b70-88a5e4c08a10.png)

**Comment by muzimuzhi** [comment]
thanks, that's fairly enough.
