### ISSUE TITLE
Add some parameter to \href for opening http/https links in new Tab/window

### ISSUE THREAD

**Issue by yashparmar414** [latex3/hyperref#196]
As we click in any (\href) in PDF,  the hyperlink should open in new window/tab of browser.
Suppose I written
\href{https://github.com/}{GITHUB}
I want this link to get opened in next tab if i am clicking this in PDF file(Suppose PDF file is opened in browser)

There is pdfnewwindow variable available in "\hyperref", but it get ignored when it comes to http/https.

Below Lines are taken from wikipedia as proof

Variable: pdfnewwindow 
values: true false
Description: define if a new PDF window should get opened when a link leads out of the current document. 
**NB: This option is ignored if the link leads to an http/https address.**

Go to below link, scroll until you see table.
Find pdfnewwindow variable.
[Click Here](https://en.wikibooks.org/wiki/LaTeX/Hyperlinks#\hyperref)

**Comment by u-fischer** [comment]
there is imho nothing in the PDF spec that allows to control how the browser will open the link. If you open the pdf in your browser, use the context menu and choose something like "open in a new tab". And check if your browser has some general option settings.

**Comment by muzimuzhi** [comment]
- `\href{http(s):///...}{text}` will write a PDF annotation with action type `URI` (resolve a URI).
 - The `pdfnewwindow` option only applies for action types `GoToR` (jump to some position in another PDF), `GoToE` (jump to some position in a PDF which is embedded in another PDF), and `Launch` (launch an application, open or print a document). This restriction is set by the PDF Reference, so `hyperref` has to follow it.
 - Therefore `pdfnewwindow` cannot have any effect on the http/https links, as described in the link to wikibook for latex. Perhaps the `hyperref` manual can add more words about this option as well.

**Comment by yashparmar414** [comment]
> * `\href{http(s):///...}{text}` will write a PDF annotation with action type `URI` (resolve a URI).
> * The `pdfnewwindow` option only applies for action types `GoToR` (jump to some position in another PDF), `GoToE` (jump to some position in a PDF which is embedded in another PDF), and `Launch` (launch an application, open or print a document). This restriction is set by the PDF Reference, so `hyperref` has to follow it.
> * Therefore `pdfnewwindow` cannot have any effect on the http/https links, as described in the link to wikibook for latex. Perhaps the `hyperref` manual can add more words about this option as well.

**Comment by yashparmar414** [comment]
@muzimuzhi 
What shoud I do now,
I want to create my one-paged resume and wanted to add some links in it.
but I want to open those links in new tab as soon as recruiter clicks.
Right now, the links are opening in **same tab** if I open the resume.pdf in browser.
Any latex command that helps to open **_http/https URLs in new tabs/window._**

**Comment by u-fischer** [comment]
LaTeX can't do anything here.
