### ISSUE TITLE
Query: how to use `\cite` style/color outside of `\cite`

### ISSUE THREAD

**Issue by tecosaur** [latex3/hyperref#197]
Hello,

I am involved with the Org-mode project, and we've recently added a native citation syntax :tada:. One of the possibilities this allows for is using CSL-generated citations with a variety of formats. When exporting to LaTeX these are formatted like so:
```tex
\hyperlink{bib_target_key}{...citation text...}
```

This works well, however since `citecolor` has no effect on this, the output is not consistent with what one sees if using biblatex et. al. I think it would be quite nice if we could apply the same style/color as `\cite` to these citations.

I've tried grepping for `citecolor` and using `latexdef`with `\cite` and `\@citex` but I'm a bit lost in the codebase, with this being the first time I've taken a peek at it.

If someone might be able to advise me on what could be done here (or a better place to ask this question), I would be greatly appreciative :slightly_smiling_face:.

**Comment by u-fischer** [comment]
You can use the internal link command, its first argument sets a context, and with context "cite" the citecolor is used. 

~~~~
\documentclass{article}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{colorlinks}
\begin{document}
\hypertarget{some-target}{aaa}

\makeatletter
\hyper@linkstart{cite}{some-target}xxxxx\hyper@linkend
\makeatother

\end{document}
~~~~

**Comment by tecosaur** [comment]
Thanks! That looks mos helpful.
