### ISSUE TITLE
Reconsider the default URL style (`\urlstyle`)

### ISSUE THREAD

**Issue by claell** [latex3/hyperref#198]
This is likely a bit controversial. However, it might make sense to reconsider the default URL style.

See https://tex.stackexchange.com/questions/53962/why-are-urls-typeset-with-monospace-fonts-by-default/510190 and https://graphicdesign.stackexchange.com/questions/97173/is-monospacing-urls-in-academic-papers-still-advised for reference.

The argument of distinguishing characters is imho only partly valid: for lI1 vs. `lI1` I can see the point, but not for O0 vs. `O0`, where the monospace font performs more poorly in LaTeX than Helvetica. GitHub uses a different monospace font that doesn't have this problem.

![grafik](https://user-images.githubusercontent.com/6171135/129187688-122b78d6-d083-415f-9aec-468cd6b2cb89.png)
![grafik](https://user-images.githubusercontent.com/6171135/129187779-2cc02ae8-d48a-4402-af7a-257a02be05c9.png)

**Comment by u-fischer** [comment]
The default url style is set by the `url` package (which is loaded by hyperref) and not by hyperref. 

But beside this, I doubt that this will change, there are millions of documents which use hyperref or url and changing them is imho out of question.
