### ISSUE TITLE
Consider a better default style for links

### ISSUE THREAD

**Issue by claell** [latex3/hyperref#199]
The default link style with a box around it looks not very nice to me. I suggest to change the default to use `colorlinks` instead.

Also see https://tex.stackexchange.com/questions/823/remove-ugly-borders-around-clickable-cross-references-and-hyperlinks.

**Comment by u-fischer** [comment]
No sorry, this won't change. `colorlinks` adds color specials, and so can affect the spacing and the printing of documents. This should be a conscious choice of an author or journal. 

If you really want this for all your document then create a `hyperref.cfg` and add `\hypersetup{colorlinks}` and store it in a place where hyperref finds it.

**Comment by claell** [comment]
It is somewhat understandable that there should not be downsides coming from this. I wasn't aware of it, although I'd argue that the current boxes also come with their downsides (like multiline references).

For reference, in the linked TeX Stack Exchange question, there is a decent amount of votes for a comment wishing something like this to be the default.
![grafik](https://user-images.githubusercontent.com/6171135/129189501-69fa40b4-71e6-4a5b-8d44-db184cfd5b44.png)

Maybe there is a way to overcome the existing downsides while providing a nicer style?

**Comment by u-fischer** [comment]
the boxes are not created by hyperref but by the pdf viewer, they don't affect printing. 

If you use the new pdfmanagement (this requires a current LaTeX, and it is in the testphase), you will get nicer colors. You can also try to set the border style to underline (this is not supported by all pdf viewers). And if someone makes a feature request I would consider to change the border style default if the pdfmanagement is loaded. 

~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}

\documentclass{article}
\usepackage{hyperref}
\hypersetup{pdfborderstyle={/S/U/W 1}}
\begin{document}
\section{section}\label{sec}
colorschemes:

\url{www.abc}
\nameref{sec}

\hypersetup{colorscheme=daleif}

\url{www.abc}
\nameref{sec}

\hypersetup{colorscheme=henryford}

\url{www.abc}
\nameref{sec}


\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/129192371-8414efa3-eb3a-4d2d-9ed8-4ffa5b316fb8.png)

**Comment by u-fischer** [comment]
a link annotation is simply a rectangle area hovering over the page, it has no connection to the text below it and can't color it.

**Comment by claell** [comment]
Alright. I assume, you were talking about problems like described here (https://tex.stackexchange.com/questions/183471/color-environments-influence-spacing) when you mentioned that color specials can affect spacing and printing? Would it be worth to open a feature request for the used color environment to not cause these problems?
