### ISSUE TITLE
Add option to only once set uniform link color

### ISSUE THREAD

**Issue by claell** [latex3/hyperref#200]
Currently, the colors for different link types can be set using three options: `linkcolor`, `citecolor`, and `urlcolor`.

For my document I want all of them to be the same and was wondering whether it was sensible to add an option to set the color for all link types together, which would make the code cleaner, easier to change and less prone to mistakes.

**Comment by u-fischer** [comment]
There is the option `allcolors`, see the documentation. 

Side remark: citations aren't a special link type, they are like `\ref` a GoTo link. They only got a special interface to set the color.

**Comment by claell** [comment]
Should have looked that up first. Thanks for your fast reply!
