### ISSUE TITLE
Indication to escape hashes is only given in log file

### ISSUE THREAD

**Issue by ISSOtm** [latex3/hyperref#201]
Here is a sample document:
```latex
\documentclass{report}
\usepackage{hyperref}
\begin{document}
\footnote{\href{https://example.com#}{...}}
\end{document}
```

This prints a couple of errors like:
```
! Illegal parameter number in definition of \Hy@tempa.
<to be read again> 
                   }
l.4 \footnote{\href{https://example.com#}{...}}
                                               
You meant to type ## instead of #, right?
Or maybe a } was forgotten somewhere earlier, and things
are all screwed up? I'm going to assume that you meant ##.
```
However, the last "You meant to type ## instead of #, right?" paragraph is *not* printed to stdout, only to the log file, which left me puzzled for a while. (I had missed the line about hashes not needing escaping *except within another command* in the documentation.)

Would it be possible to additionally print it to stdout? It would help solving such problems more quickly.

**Comment by u-fischer** [comment]
That is not a hyperref error but a tex error. You get it also with 

~~~~
\documentclass{report}
\begin{document}
\def\blub{#}
\end{document}

~~~~

The second part is what you get if you type h at the error prompt, in \nonstopmode it is also written to the log.
