### ISSUE TITLE
Escaped hashes within commands always yield double hashes

### ISSUE THREAD

**Issue by ISSOtm** [latex3/hyperref#202]
Taking the same sample input from #201:
```latex
\documentclass{report}
\usepackage{hyperref}
\begin{document}
\footnote{\href{https://example.com#anchor}{...}}
\end{document}
```
This complains about "`#` where `##` is expected" four times (`\Hy@tempa` 3×, `\Hy@gtemp` 1×).

Doubling the hash drops two of the `\Hy@tempa` errors, but keeps the other two. Tripling the hash yields the same result, and four hashes removes all errors.

However, in all of these cases, the generated URL is `https://example.com##anchor`—this seems like a bug, as `\href{https://example.com#anchor}` outside of `\footnote{}` generates the expected `https://example.com#anchor` link. (Doubling the hash then causes the URL fragment to be dropped entirely, for some reason.)

**Comment by u-fischer** [comment]
Doubling is wrong. The right escape is you have an url in an argument of another command is `\#`:

~~~~
\documentclass{report}
\usepackage{hyperref}
\begin{document}
\footnote{\href{https://example.com\#anchor}{...}}
\end{document}
~~~~
