### ISSUE TITLE
Add hyperref.ist to distribution

### ISSUE THREAD

**Issue by dahosek** [latex3/hyperref#203]
Somewhat inexplicably, the hyperref.ist that's described in the documentation is not part of the distribution, requiring authors to find this and copy/paste it into a new document (and at least copying/pasting from the MacOS preview app into Aquamacs loses some of the page breaks in the copy-paste process. I can't speak to other platforms). As the .ist approach is the best way to work around issues like #109 it seems like adding the hyperref.ist to what's packaged on CTAN (and thus TeX live, and probably MikTeX) would provide an easily¹ implemented fix. 

---
1. Well, maybe not that easily. As far as I can tell, short of writing a custom TeX engine, there appears to be no straightforward way to specify that makeindex should be run with an index style with TeXshop. For my needs, it's not a big deal to drop down to a command line and generate a hyperlinked index that way.

**Comment by u-fischer** [comment]
there is no hyperref.ist in the documentation, and the hyperindex.ist doesn't look to me as if it is meant as a complete .ist, more like an example how someone could adapt some of the settings of their .ist.

**Comment by dahosek** [comment]
Sorry, I cut and pasted into a file that I named based on what I was thinking the name should be.

By default, makeindex does not apply *any* index style, so this ist is, in fact, complete. (I'd add that there's a directive include which appears in din.ist, mkind.ist, and tex.ist that apparently is unimplemented in makeindex (as are a number of other directives in those same files) that if it were, would make incorporating this in a new ist simpler.
