### ISSUE TITLE
\includeonly + \tablecontents + hyperref -> pdf dest warning

### ISSUE THREAD

**Issue by kberry** [latex3/hyperref#208]
I don't suppose this is news, but using \includeonly and \tableofcontents with hyperref causes a warning from pdftex:
```
\documentclass{book}
\usepackage{hyperref}
%\includeonly{mych1}
\begin{document}
\frontmatter
\tableofcontents

\mainmatter
\include{mych1}
\include{mych2}
\end{document}
```

Run a couple of times without the \includeonly, so everything is present, then enable it, and pdftex reports:
```
pdfTeX warning (dest): name{chapter.2} has been referenced but does not exist
, replaced by a fixed one
```

It would be nice if there was a way to avoid this. I guess I could add another \pdfsuppresswarning... option to pdftex, but then any other real undefined destinations would also get hidden. Any ideas? Thanks.

The chapters can be anything, of course. My test mych1.tex:
```
\chapter{First Chapter}                                                         
                                                                                
Text of first chapter.
```

And mych2.tex:
```
\chapter{Second Chapter}                                                        
                                                                                
Text of second chapter.
```

**Comment by u-fischer** [comment]
No I don't think that one can do something. I mean it is not only the toc. Every `\ref` into a chapter which is not included is missing the destination. Beside this I also don't think that I want do something here. The warnings are real and imho useful, and one reason that I asked for an extension for \pdfdest etc for structure destination is to keep this warnings when ever possible.

**Comment by kberry** [comment]
When using \includeonly, "no destination" warnings are expected and just
noise, as far as I can see.

By "noise", I mean that the destinations would be defined if the whole
document was run. Isn't the point of \includeonly? To only process part
of the document, while still having the crossref/other aux information
from all of the document available?

Thus the only way I can imagine to show only real warnings in this case
would be for LaTeX to save defined pdf destinations along with the other
stuff it already saved, precisely for use with \includeonly. I doubt
that is easy or even particularly feasible, but, just mentioning ...

If you don't agree, even in principle, then that's fine, I guess I'll
just add a warning-suppression parameter, or something. 'cause I don't
want to see them when they are fully expected. --thanks, karl.

**Comment by u-fischer** [comment]
> I'll just add a warning-suppression parameter, 

I think that would be the right solution. 

When using \includeonly you can *print*  a correct table of contents with entries pointing to chapters not included, and *print* references to such chapters, but you can't create a working bookmark  entry or link to such a chapter.  The link will be either dead or point to the wrong location. Regardless what we do, something would be wrong, and so it shouldn't be our code but a choice of the users to suppress related warnings.
