### ISSUE TITLE
`\protect` leaks into the `.out` file via `\pdfbookmark`, ruins the section names in PDF

### ISSUE THREAD

**Issue by ilyaza** [latex3/hyperref#218]
The following MWE demonstrates the issue in the subject (an extra byte in a 16-bit encoding):
```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage[unicode]{hyperref}  % same without [unicode]

\let\textendashORI\textendash
\def\textendash{\text{\textendashORI}}

\begin{document}

\pdfbookmark[0]{Sections 1--2 here}{supersec.5.0}

Text of the sections.

\end{document}
```

**Comment by u-fischer** [comment]
`\textendash` is used by hyperref to replace the `--`. 

If you redefine it it is up to you to make the definition bookmark safe, e.g. with `\texorpdfstring`

~~~~
\def\textendash{\texorpdfstring{definition for text}{definition for bookmarks}}
~~~~


> `% same without [unicode]`

unicode is the default since some time for all engines.

**Comment by ilyaza** [comment]
> `\textendash` is used by hyperref to replace the `--`.

This is not clear.  Currently, to support `utf8x` encoding, I have the following \text* macros redefined:
```latex
\@for\next:={% after removing the duplicates of greek symbols already defined above
  quotedbl,quoteright,less,greater,backslash,asciicircum,underscore,g,%
  braceleft,bar,braceright,asciitilde,exclamdown,cent,currency,yen,brokenbar,%
  ordfeminine,registered,degree,periodcentered,ordmasculine,onequarter,onehalf,%
  threequarters,questiondown,Hbar,crh,hbar,Tbar,tbar,Bhook,Oopen,Chook,chook,%
  Dafrican,Dhook,Ereversed,Eopen,Fhook,florin,Gammaafrican,Iotaafrican,Khook,%
  khook,Nhookleft,Phook,phook,Esh,Thook,thook,Tretroflexhook,Vhook,Yhook,yhook,%
  Ezh,eturned,baht,turna,scripta,turnscripta,bhook,htb,oopen,openo,ctc,dtail,%
  rtaild,dhook,htd,reve,schwa,rhookschwa,eopen,revepsilon,%
  rhookrevepsilon,closerevepsilon,bardotlessj,htg,scriptg,scg,gammalatinsmall,%
  ramshorns,turnh,hth,htheng,bari,iotalatin,sci,ltilde,beltl,rtaill,%
  lyoghlig,turnm,turnmrleg,ltailm,nhookleft,ltailn,rtailn,scn,baro,scoelig,%
  closeomega,phi,turnr,turnlonglegr,turnrrtail,longlegr,rtailr,fishhookr,lhti,%
  scr,invscr,rtails,esh,htbardotlessj,raisevibyi,ctesh,turnt,tretroflexhook,%
  rtailt,baru,vhook,scriptv,turnv,turnw,turny,scy,rtailz,ctz,ezh,yogh,%
  ctyogh,glotstop,revglotstop,invglotstop,stretchc,bullseye,scb,closeepsilon,%
  htscg,sch,ctj,turnk,scl,htq,barglotstop,barrevglotstop,dzlig,dyoghlig,%
  dctzlig,tslig,tesh,teshlig,tctclig,primstress,lengthmark,dexiakeraia,%
  aristerikeraia,question,anoteleia,stigma,Digamma,digamma,qoppa,sanpi,%
%  endash,
  emdash,quoteleft,quotedblleft,quotedblright,bullet,%
  perthousand,pertenthousand,referencemark,interrobang,colonmonetary,lira,%
  naira,won,dong,numero,trademark,visiblespace}\do{%	Handle utf8x \text*
```

Should one protect them all the way you write below?

> If you redefine it it is up to you to make the definition bookmark safe, e.g. with `\texorpdfstring`
> ```latex
> \def\textendash{\texorpdfstring{definition for text}{definition for bookmarks}}
> ```

**Comment by ilyaza** [comment]
> `\textendash` is used by hyperref to replace the `--`.

Thinking about this more: I became completely lost.  Why would `hyperref` use a macro with an unknown expansion **when it knows what it wants to achieve**, and *can use* `\texorpdfstring` itself?

**Comment by davidcarlisle** [comment]
Note that you can not use `\let` on any encoding-specific command that way.

If you compare with

```
\documentclass{article}
\usepackage{amsmath}
\usepackage[unicode]{hyperref}  % same without [unicode]

\typeout{^^J\meaning\textendash ^^J}
%\let\textendashORI\textendash
%\def\textendash{\text{\textendashORI}}

\begin{document}

\pdfbookmark[0]{Sections 1--2 here}{supersec.5.0}

Text of the sections.

\end{document}
```

you will see that `\textendash` has a PU-specific specific definition explicitly so that it works in bookmarks, which the commented out code removes. As such there is nothing hyperref can do here as the tex-primitive definitions are removing the hyperref definition to make this work in bookmarks.

If you use `\let` you just copy the top level switch command and do not copy the internal commands that hold theactual definition (this is true for encoding-specific commands or commands defined with `\DeclareRobustCommand`.

In recent releases you could use `\NewCommandCopy`

so ideally you would ensure that all the commands are declared as encoding specific and have a PU-specific definition if that is required.

**Comment by davidcarlisle** [comment]
> 
> 
> > `\textendash` is used by hyperref to replace the `--`.
> 
> Thinking about this more: I became completely lost. Why would `hyperref` use a macro with an unknown expansion **when it knows what it wants to achieve**, and _can use_ `\texorpdfstring` itself?

why do you say it has an unknown expansion? It has a standard definition as an encoding specific command which hyperref does not change.  It just defines a bookmark (PU) encoding version of the command with

```
\DeclareTextCommand{\textendash}{PD1}{\205}% U+2013
```

which your code then removed.

**Comment by u-fischer** [comment]
> Should one protect them all the way you write below?

If you define or redefine something that can also be used in a section title and so in the bookmark you should test that it works. 

>  Why would hyperref use a macro with an unknown expansion when it knows what it wants to achieve, and can use \texorpdfstring itself?

`\textendash` is a standard, encoding dependant command of LaTeX and as David says hyperref sets it up so that it works. You are breaking the command and so it is your job to handle the side effects. 

Beside this I wouldn't use utf8x, it is not really compatible with the utf8 handling of LaTeX.

**Comment by ilyaza** [comment]
> Note that you can not use `\let` on any encoding-specific command that way.
> …
> you will see that `\textendash` has a PU-specific specific definition explicitly so that it works in bookmarks, which the commented out code removes. 

I do not follow.  This “PU-specific definition” is not removed.  It is just moved into `\text`, where it would happily get called.  `\text` is just a (protected) shortcut for `\ifmmode` — cannot one use it in a character’s definition?!

**Comment by davidcarlisle** [comment]
@ilyaza  note this is a bug reporting address not a help forum, hyperref uses the standard latex commands to specify bookmark encoding (PD1 and PU) versions of the commands it supports. You added tex primitive redefinitions which removed that and defined `\textendash` directly. This is clearly not a hyperref issue.

> \text is just a (protected) shortcut for \ifmmode 

not at all, in text mode it's essentially `\mbox` and in math mode it's a 4-way \mathchoice construct, neither of which would work by default in bookmarks.  It isn't clear why you are redefining `\textendash` at all (simply removing the redefinition fixes the issue)  but if you do redefine it you need to define it in a way that works in all contexts.

**Comment by ilyaza** [comment]
> > Should one protect them all the way you write below?
> 
> If you define or redefine something that can also be used in a section title and so in the bookmark you should test that it works.

As a general recommendation, this approach seem completely broken.  
 - For example, one cannot test compatibility with future versions…
 - Second, there is more than a hundred thousand Unicode chars.  Should I check them all?  
 - Third, my current setup loads 215 LaTeX packages (or at least 215 files).  Following this advice, one would need to check compatibility with 216 contexts…  (But maybe there is a shortcut — see below.)

> `\textendash` is a standard, encoding dependant command of LaTeX and as David says hyperref sets it up so that it works. 

Well, I never saw any description of what “a standard, encoding dependant command of LaTeX” actually means.  It may be a defect of my education — but somehow I suspect that I would need to inspect the source of `\PU-cmd`.  Sigh…

**Comment by ilyaza** [comment]
> It isn't clear why you are redefining `\textendash` at all 

This is a maximally simplified version of code making Unicode chars available in LaTeX.  Do you know another way to do this?  As in `$α=75°$` ?

**Comment by u-fischer** [comment]
As David said: this here is a bug report tracker. Please ask such questions e.g. on tex.stackexchange.

**Comment by ilyaza** [comment]
> > \text is just a (protected) shortcut for \ifmmode
> 
> not at all, in text mode it's essentially `\mbox` and in math mode it's a 4-way \mathchoice construct, neither of which would work by default in bookmarks. It isn't clear why you are redefining `\textendash` at all (simply removing the redefinition fixes the issue) but if you do redefine it you need to define it in a way that works in all contexts.

Well, I double-checked, and 
```latex
\section{Here $2+\text{Foo\textendash Bar}$, or \text{Foo\textendash Bar}}
```
works without any problem whatsoever (well, I knew it in advance — this is why I made the MWE as it is written above).  Does not it put us back the full circle?!

So what should a user know to understand that `\text{\endash}` may be problematic, but the section header above is not?

**Comment by ilyaza** [comment]
> As David said: this here is a bug report tracker. 

And I’m reporting a bug!

- Deep inside its stomach, `hyperref` is using 7 macros:
```latex
      \HyPsd@StringSubst{\\}{\textbackslash}#1%
      \HyPsd@Subst{---}\textemdash#1%
      \HyPsd@Subst{--}\textendash#1%
      \HyPsd@Subst{!`}\textexclamdown#1%
      \HyPsd@Subst{?`}\textquestiondown#1%
        \HyPsd@StringSubst\(\textparenleft#1%
        \HyPsd@Subst(\textparenleft#1%
```
- Since (apparently), these macros are used at a very low level of processing pipeline, they do not work in this context even if they are working at *other* contexts of `hyperref`.
- These macros are user-visible, and are used in many other contexts (e.g., by `utf8x`).
- Still, `hyperref` relies that their definitions are not going to be changed from the only form it can understand.

How this does not form a bug?!   (Especially if it is trivial to change — as I [haha: correctly!] pointed above: just copy ***the needed*** definitions to `\HyPsd@textbackslash` etc., and use these copies inside `\HyPsd@Subst`…

**Comment by u-fischer** [comment]
`\textendash` is defined by the LaTeX kernel as a font encoding dependant command (e.g. in OT1enc.def and TUenc). hyperref adds a definition for PU encoding. That is the right way to use such text-commands. If you break it, and so break hyperref and other packages which assume that it is still encoding dependant it is a bug of your code not of hyperref.

If you want a list of all the text commands hyperref and LaTeX set up and which you can break with careless redefinitions I suggest that you look into puenc.def, tuenc.def and T1enc.def.
