### ISSUE TITLE
superscript and subscript warnings

### ISSUE THREAD

**Issue by FrisoDB** [latex3/hyperref#219]
In some cases it is really useful to have superscript and subscripts in an (sub)caption. Whether in mathmode or textmode, hyperref keeps reporting multiple warnings for each caption with this issue. It basically drowns out relevant warnings. Can this be fixed?

An example of subscripts in mathmode and textmode:
https://tex.stackexchange.com/questions/1013/how-to-typeset-subscript-in-usual-text-mode

**Comment by u-fischer** [comment]
As the linked question shows: Use \texorpdfstring https://tex.stackexchange.com/a/1017/2388.
