### ISSUE TITLE
bib keys in the binary output

### ISSUE THREAD

**Issue by niruvt** [latex3/hyperref#221]
[This](https://tex.stackexchange.com/q/625328/174620) question on SE has reported a problem, that the cite-keys defined in the bib-file are preserved in the binary output with `hyperref`. Some people (like me and the OP) find it odd. Can something be done in order to avoid this behavior?

**Comment by u-fischer** [comment]
As mentioned in https://tex.stackexchange.com/questions/560276/hide-internal-bibkeys-in-pdf, hyperref offers with `\HyperDestNameFilter` a method to change destination names. To offer an interface to change specifically the destination names of citations (or glossaries or similar packages using keys to identify something) would be imho a task of bibliography packages.

**Comment by mrpiggi** [comment]
Using `\[pdf]mdfivesum` together with `\HyperDestNameFilter` would be a possible generic solution
