### ISSUE TITLE
`\vnameref` with `nospace` option

### ISSUE THREAD

**Issue by gusbrs** [latex3/hyperref#224]
`\vnameref` seems to be swapping the space position before and after the `\nameref` call when the `varioref` option `nospace` is active.

MWE:

```latex
\documentclass{article}

\usepackage[nospace]{varioref}
\usepackage{nameref}

\begin{document}

\section{Section 1}
\label{sec:section-1}

\clearpage{}

Foo\vnameref{sec:section-1}

\end{document}
```
Results in:

![Screenshot from 2022-01-27 15-03-00](https://user-images.githubusercontent.com/19410606/151417376-3dd54620-e298-42e8-a2aa-995b2edd45fe.png)

**Comment by u-fischer** [comment]
I added a space, this should fix this in the next version.

**Comment by gusbrs** [comment]
Thank you!
