### ISSUE TITLE
feature request: reproducible documents

### ISSUE THREAD

**Issue by Reissner** [latex3/hyperref#228]
as seen in 
https://tex.stackexchange.com/questions/229605/reproducible-latex-builds-compile-to-a-file-which-always-hashes-to-the-same-va
with pdflatex, xelatex and lualatex one can create reproducible pdfs, 
but the way to do so depends on the engine. 
hyperref had the chance to unify things a lot. 

It seems to support pdfinfo already and what is missing for all engines is just pdftrailerid. 
Still, for pdflatex there should be a way to do \pdfsuppressinfo: 
I dont know how to suppress the banner.

**Comment by josephwright** [comment]
Each engine produces a different structure: there's no possibility of getting the same PDF from pdfTeX and XeTeX.
