### ISSUE TITLE
Support sending empty option to pdfremotestartview

### ISSUE THREAD

**Issue by sbenz** [latex3/hyperref#231]
I'm generating PDFs for a project where the recipient has strict requirements around inheriting the zoom levels of PDFs.  By sending `pdfstartview=` to `hypersetup` I can achieve the desired effect for the current PDF, however links to other PDFs produced with `\href` default to `\Fit`, even when I set `pdfremotestartview=` in `hypersetup`.  I confirmed I can switch it to `XYZ` by using that option but it doesn't appear there is any way to tell `hyperref` to not set anything at all for `\href` links.

It also appears that if I set the `href` target to include a page "anchor" (e.g. `my-other-file.pdf#page=1`) that it does not include `\Fit` for the view (I assume because I theoretically could also set `view=` as one of the target parameters).

Would it be possible for `pdfremotestartview` to support an empty option as well to make it consistent with `pdfstartview` and allow fallback to the default behavior of whatever the PDF client is set to?

Here's my current `hypersetup` for the file I'm working with:

```
\hypersetup{
  colorlinks=true,
  linkcolor={blue},
  filecolor={Blue},
  citecolor={Blue},
  urlcolor={Blue},
  pdfpagemode={UseOutlines},
  pdfcreator={LaTeX},
  bookmarksopen=true,
  pdfstartpage=,
  pdfstartview=,
  pdfremotestartview=,
  pdfnewwindow=true,}
```

Please let me know if there's any additional information I can provide.  Thanks!

**Comment by u-fischer** [comment]
Show a complete example. You can use pdf's from the mwe package as examples.

**Comment by sbenz** [comment]
Sure, apologies for not providing that with the original issue - hopefully these are useful but please let me know if I failed to include the output needed.  

Here is an example with the defaults for `pdfstartpage`, `pdfstartview` and `pdfremotestartview`:
```
\documentclass{article}
\usepackage{mwe}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{
  colorlinks=true,
  linkcolor={blue},
  filecolor={blue},
  citecolor={blue},
  urlcolor={blue},
  pdfpagemode={UseOutlines},
  pdfcreator={LaTeX},
  bookmarksopen=true,
  pdfnewwindow=true,}

\begin{document}

Here is a \href{other.pdf}{link} where Fit is set as the default.

Here is a \href{other.pdf#page=1}{link} where the default view exists.

\end{document}
```

Which produces a PDF with the following objects (decoded using qpdf, but if there's another way to provide what you need please let me know):


```
%% using default pdfstartpage and pdfstart view results in the following object which defaults the view to Fit
%% Original object ID: 1 0
4 0 obj
<<
  /D [
    7 0 R
    /Fit
  ]
  /S /GoTo
>>
endobj

%% and the two links, the second which does not have /Fit
%% Original object ID: 4 0
14 0 obj
<<
  /A <<
    /D [
      0
      /Fit
    ]
    /F (other.pdf)
    /NewWindow true
    /S /GoToR
  >>
  /Border [
    0
    0
    0
  ]
  /C [
    0
    .5
    .5
  ]
  /H /I
  /Rect [
    189.569
    656.13
    207.9
    665.255
  ]
  /Subtype /Link
  /Type /Annot
>>
endobj

%% Original object ID: 5 0
15 0 obj
<<
  /A <<
    /D (page=1)
    /F (other.pdf)
    /NewWindow true
    /S /GoToR
  >>
  /Border [
    0
    0
    0
  ]
  /C [
    0
    .5
    .5
  ]
  /H /I
  /Rect [
    189.569
    644.174
    207.9
    653.3
  ]
  /Subtype /Link
  /Type /Annot
>>
endobj
```

And here is an example where I've attempted to "ignore" the default of /Fit by providing blank options to `pdfstartpage`, `pdfstartview` and `pdfremotestartview`:

```
\documentclass{article}
\usepackage{mwe}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{
  colorlinks=true,
  linkcolor={blue},
  filecolor={blue},
  citecolor={blue},
  urlcolor={blue},
  pdfpagemode={UseOutlines},
  pdfcreator={LaTeX},
  bookmarksopen=true,
  pdfstartpage=,
  pdfstartview=,
  pdfremotestartview=,
  pdfnewwindow=true,}

\begin{document}

Here is a \href{other.pdf}{link} where Fit is set as the default.

Here is a \href{other.pdf#page=1}{link} where the default view exists.

\end{document}
```

And the resulting PDF objects (note the document level \Fit object no longer exists, as expected):

```
%% link objects
%% Original object ID: 1 0
13 0 obj
<<
  /A <<
    /D [
      0
      /Fit
    ]
    /F (other.pdf)
    /NewWindow true
    /S /GoToR
  >>
  /Border [
    0
    0
    0
  ]
  /C [
    0
    .5
    .5
  ]
  /H /I
  /Rect [
    189.569
    656.13
    207.9
    665.255
  ]
  /Subtype /Link
  /Type /Annot
>>
endobj

%% Original object ID: 2 0
14 0 obj
<<
  /A <<
    /D (page=1)
    /F (other.pdf)
    /NewWindow true
    /S /GoToR
  >>
  /Border [
    0
    0
    0
  ]
  /C [
    0
    .5
    .5
  ]
  /H /I
  /Rect [
    189.569
    644.174
    207.9
    653.3
  ]
  /Subtype /Link
  /Type /Annot
>>
endobj
```

As mentioned in the original issue, I would have expected the first link in the second example (without the `#page=1`) to not output the `/D [ 0 /Fit ]` attribute, since that's the behavior I'm hoping for to just fall back on the default for the viewer.

Thanks!

**Comment by u-fischer** [comment]
you don't want an empty remote start view but XYZ, so try `\usepackage[pdfremotestartview=XYZ]{hyperref}`

**Comment by sbenz** [comment]
Got it, thank you so much for that. I had tried XYZ but had set numeric values as part of it which didn't appear to be working the way I expected.  Setting the option without any values works great.

Thanks again and apologies for opening a non-issue.
