### ISSUE TITLE
\nameref no longer redefined

### ISSUE THREAD

**Issue by kberry** [latex3/hyperref#234]
As of hyperref 7.00o, \nameref cannot be previously defined. Apparently a consequence of using \NewDocumentCommand instead of \DeclareRobustCommand to define it. Is this intentional? I did not see it noted. In any case, it seems an unnecessary incompatibility to introduce now?

RobinF set up ltugboat.cls to define \nameref decades ago. Admittedly that's not ideal, but it was a different world back then. Thus
```
\documentclass{ltugboat}
\usepackage{hyperref}
\begin{document}
\end{document}
```
fails with 7.00o ... --thanks for considering, karl.

**Comment by u-fischer** [comment]
> Is this intentional?

No ;-). More habit. I normally try to avoid to silently overwrite existing commands.  I can add a test for it in the afternoon and reupload. 

> RobinF set up ltugboat.cls to define \nameref decades ago.

I think you should also consider to change the class longer term and define \nameref in begindocument only if it is undefined.

We are trying to unify and sort the reference commands. For example the next latex will contain starred versions of \ref*, \pageref* and \Ref*. And imho one the next steps should be to provide also \nameref, and then your  definition could harm. 


 > Admittedly that's not ideal, but it was a different world back then. 

History is thick here I agree.

**Comment by kberry** [comment]
Re another hyperref update to still overwrite \nameref -- yes, please.

Re ltugboat only providing \nameref atbegindocument-time ... good idea.
I will do it. It doesn't look like ltugboat defines any other
ref-related commands, so hopefully this was a one-time thing.

Thanks,
Karl

**Comment by u-fischer** [comment]
this should be resolved now.
