### ISSUE TITLE
\nameref with custom environments

### ISSUE THREAD

**Issue by johanzietsman-em** [latex3/hyperref#237]
I define my own custom environments for documenting requirements, for example. When I call \nameref to refer to the title of a requirement, the command displays the title of the section/chapter in which the requirement appears, and not of the requirement itself. How can I make my custom environments compatible with the \nameref command?

Perhaps you can help, @davidcarlisle? I would appreciate it very much.

Here is an example of my custom environment definition as I have it in my package. I pass the title of the requirement as the only command to the environment, but I can also pass in the label if that would help.

```
\RequirePackage{tocloft}
\RequirePackage{totcount}
\newcommand{\listrequirementname}{List of Requirements}
\newlistof[chapter]{requirement}{req}{\listrequirementname}

\newcounter{requirements}
\regtotcounter{requirements}

\newenvironment{requirement}[1]{%
  \refstepcounter{requirement}%
  \stepcounter{requirements}%
  \noindent
  \centering
  \begin{minipage}{0.9\textwidth}
	\centering
	\vspace{3mm}\par{Requirement \therequirement: #1}
	\vspace{-3mm}
	\addcontentsline{req}{requirement}{\protect\numberline{\therequirement}#1}\par\nobreak
	\small
	\begin{tabular}{p{0.95\linewidth}}
		\toprule
		\vspace{-3mm}
}{%
		\\
		\bottomrule
	\end{tabular}
  \end{minipage}
  \par\medskip\ignorespacesafterend%
  \vspace{3mm}
}

\crefname{requirement}{Requirement}{Requirements}
```

**Comment by u-fischer** [comment]
well basically `\@currentlabelname` must have the right content. Something like 

~~~~
\GetTitleString{#1}%
 \let\@currentlabelname\GetTitleStringResult
~~~~

(\Gettitlestring is from the gettitlestring package and it's main purpose is to clean up the text so that it doesn't error if written to the aux-file .  You are not required to use it, you can process your title with other commands if your prefer.)

**Comment by johanzietsman-em** [comment]
Thank you for your prompt reply, @u-fischer.

I have tried to get a value into ``\@currentlabelname`` by doing the following early in my environment definition:
```
\let\@currentlabelname\#1
```

I suspect that the hyperref package calls ``\GetTitleString``, which overwrites my value in ``\@currentlabelname``. It appears that the titles of sections, chapters, figures, etc. are stored in macros such as ``\@sect`` and ``\@caption``. I have tried storing my title in ``\@caption``, but so far it has not worked.

**Comment by u-fischer** [comment]
Sorry but why don't you use my code? You can not use \let on a text argument.  

~~~~
\documentclass{article}
\usepackage{nameref}
\makeatletter
\newcounter{requirement}
\newenvironment{requirement}[1]{%
  \refstepcounter{requirement}%  
  \GetTitleString{#1}%
  \let\@currentlabelname\GetTitleStringResult
  Requirement \therequirement: #1\par  
  }{}
\makeatother
\begin{document}

\begin{requirement}{A requirement}\label{req:1}
xxx
\end{requirement}

\nameref{req:1}

\end{document}
~~~~

**Comment by johanzietsman-em** [comment]
Fantastic!!! Thank you so much, @u-fischer. You have solved my problem. I can now simply call ``\nameref`` with a label as reference, and it prints the correct title.

For future reference, here is what works:

```
\RequirePackage{tocloft}
\RequirePackage{totcount}
\newcommand{\listrequirementname}{List of Requirements}
\newlistof[chapter]{requirement}{req}{\listrequirementname}

\newcounter{requirements}
\regtotcounter{requirements}

\newenvironment{requirement}[1]{%
  \refstepcounter{requirement}%
  \stepcounter{requirements}%
  \GetTitleString{#1}%
  \let\@currentlabelname\GetTitleStringResult%
  \noindent
  \centering
  \begin{minipage}{0.9\textwidth}
	\centering
	\vspace{3mm}\par{Requirement \therequirement: #1}
	\vspace{-3mm}
	\addcontentsline{req}{requirement}{\protect\numberline{\therequirement}#1}\par\nobreak
	\small
	\begin{tabular}{p{0.95\linewidth}}
		\toprule
		\vspace{-3mm}
}{%
		\\
		\bottomrule
	\end{tabular}
  \end{minipage}
  \par\medskip\ignorespacesafterend%
  \vspace{3mm}
}

\crefname{requirement}{Requirement}{Requirements}
```
