### ISSUE TITLE
Conflict with draft option, cleveref's \cref and... \textbf in \caption

### ISSUE THREAD

**Issue by dbitouze** [latex3/hyperref#238]
Issue
------
Until `hyperref` v7.00n (at least), the following MCE:
```latex
\documentclass{article}
\usepackage{hyperref}
\usepackage{cleveref}

\hypersetup{draft}

\begin{document}
\begin{figure}
  \caption{%
    foo%
    \textbf{foo}%
  }
  \label{bar}
\end{figure}

See \cref{bar}.
\end{document}
```
worked like a charm. But since at least v7.00p, the (second) compilation fails with:
```latex
! Use of \@@cref@getlabel doesn't match its definition.
\text@command #1->\edef \reserved@a {
                                     \unexpanded {#1}}\ifx \reserved@a \@emp...

l.36 See \cref{bar}
```
Context
----
- Up to date TeX Live 2022
- Compilation with `pdflatex`, `xelatex` or `lualatex.
- My *File List*:

        article.cls    2021/10/04 v1.4n Standard LaTeX document class
        size10.clo    2021/10/04 v1.4n Standard LaTeX file (size option)
        varioref.sty    2021/07/07 v1.6f package for extended references (FMi)
        hyperref.sty    2022-05-17 v7.00q Hypertext links for LaTeX
        ltxcmds.sty    2020-05-10 v1.25 LaTeX kernel commands for general use (HO)
        iftex.sty    2022/02/03 v1.0f TeX engine tests
        pdftexcmds.sty    2020-06-27 v0.33 Utility functions of pdfTeX for LuaTeX (HO)
        infwarerr.sty    2019/12/03 v1.5 Providing info/warning/error messages (HO)
        keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
        kvsetkeys.sty    2019/12/15 v1.18 Key value parser (HO)
        kvdefinekeys.sty    2019-12-19 v1.6 Define keys (HO)
        pdfescape.sty    2019/12/09 v1.15 Implements pdfTeX's escape features (HO)
        hycolor.sty    2020-01-27 v1.10 Color options for hyperref/bookmark (HO)
        letltxmacro.sty    2019/12/03 v1.6 Let assignment for LaTeX macros (HO)
        auxhook.sty    2019-12-17 v1.6 Hooks for auxiliary files (HO)
        nameref.sty    2022-05-17 v2.50 Cross-referencing by name of section
        refcount.sty    2019/12/15 v3.6 Data extraction from label references (HO)
        gettitlestring.sty    2019/12/15 v1.6 Cleanup title references (HO)
        kvoptions.sty    2020-10-07 v3.14 Key value format for package options (HO)
        pd1enc.def    2022-05-17 v7.00q Hyperref: PDFDocEncoding definition (HO)
        intcalc.sty    2019/12/15 v1.3 Expandable calculations with integers (HO)
        etexcmds.sty    2019/12/15 v1.7 Avoid name clashes with e-TeX commands (HO)
        puenc.def    2022-05-17 v7.00q Hyperref: PDF Unicode definition (HO)
        url.sty    2013/09/16  ver 3.4  Verb mode for urls, etc.
        bitset.sty    2019/12/09 v1.3 Handle bit-vector datatype (HO)
        bigintcalc.sty    2019/12/15 v1.5 Expandable calculations on big integers (HO)
        atbegshi-ltx.sty    2021/01/10 v1.0c Emulation of the original atbegshi
        hpdftex.def    2022-05-17 v7.00q Hyperref driver for pdfTeX
        atveryend-ltx.sty    2020/08/19 v1.0a Emulation of the original atveryend packa
        rerunfilecheck.sty    2019/12/05 v1.9 Rerun checks for auxiliary files (HO)
        uniquecounter.sty    2019/12/15 v1.4 Provide unlimited unique counter (HO)
        cleveref.sty    2018/03/27 v0.21.4 Intelligent cross-referencing
        l3backend-pdftex.def    2022-04-20 L3 backend support: PDF output (pdfTeX)
         ***********

**Comment by u-fischer** [comment]
actually the bug is old. You get the same error with older version if you load nameref before hyperref.  It was hidden as normally nameref was loaded in begindocument.  As a workaround add this after begin document:

~~~~
\makeatletter
\long\def\@secondoffive#1#2#3#4#5{#2}
\long\def\@fifthoffive#1#2#3#4#5{#5}
\makeatother
~~~~

**Comment by dbitouze** [comment]
> actually the bug is old. You get the same error with older version if you load nameref before hyperref. It was hidden as normally nameref was loaded in begindocument. As a workaround add this after begin document:
> 
> ```
> \makeatletter
> \long\def\@secondoffive#1#2#3#4#5{#2}
> \long\def\@fifthoffive#1#2#3#4#5{#5}
> \makeatother
> ```

OK, thanks. Is a real fix planned?

**Comment by u-fischer** [comment]
I already pushed a fix, but I don't know yet when I will upload to ctan.

**Comment by dbitouze** [comment]
Bug still present with `hyperref` 2022-06-13 v7.00r.

**Comment by u-fischer** [comment]
hm. I wonder what I did there. Need to check.

**Comment by u-fischer** [comment]
Oh I see, I forgot to merge this change.
