### ISSUE TITLE
Dimen `\XeTeXLinkMargin` defined for all engines but apparently only needed for XeTeX

### ISSUE THREAD

**Issue by jfbu** [latex3/hyperref#240]
Looking at some log file I noticed a dimen register was allocated with name `\XeTeXLinkMargin`.

I looked into `hyperref.sty` and found this:

```latex
\newdimen\XeTeXLinkMargin
\setlength{\XeTeXLinkMargin}{2pt}
\ifxetex
  \font\XeTeXLink@font=pzdr at 1sp\relax
...
\else
  \newcommand*{\XeTeXLinkBox}[1]{%
    \begingroup
      \leavevmode
      \sbox\z@{#1}%
      \copy\z@
    \endgroup
  }%
\fi
```

which seems to indicate it is is needed only for XeTeX engine.  I did not find other references in the code and the documentation `7.7 \XeTeXLinkBox` mentions it as  XeTeX-specific thing.

Is there some reason to allocate it always?

**Comment by u-fischer** [comment]
Well it is only needed for xetex, but defining it for the other engines too makes it easier for the users: they don't have to test for the engine but can simply add the box and set the dimen.
