### ISSUE TITLE
The last version of package is not compatible with the MDPI Journal Lyx template

### ISSUE THREAD

**Issue by cpsychal** [latex3/hyperref#245]
Using the MDPI Journal Lyx template from here
https://www.mdpi.com/data/MDPI_template_lyx.zip?v=20210603

there is a problem in the compilation.

Instead, using the previous version of hyperref package everything is fine.

**Comment by u-fischer** [comment]
mdpi knows about it and they will adapt their template shortly. As a work around load `nameref` in the preamble.

**Comment by cpsychal** [comment]
Many thanks for your helpful response!
So, just adding \usepackage{nameref} is OK?

**Comment by u-fischer** [comment]
It should, but I don't have lyx to test, so try it out.

**Comment by cpsychal** [comment]
Tried it and is OK! 
Many thanks again.
