### ISSUE TITLE
utf8x (but not utf8) option to inputenc + hyperref ==> error

### ISSUE THREAD

**Issue by balducci** [latex3/hyperref#248]
hello

apologies: I don't know if this is a problem with hyperref, (recent) inputenc, both (or neither...)

When processing this source:

```
\documentclass{article}
\usepackage[utf8x]{inputenc}
\usepackage{hyperref}
\listfiles

\begin{document}

Dummy text here

\end{document}
```
with:

```
latex mom.tex
```
I get the following error:

```
##> latex mom.tex
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (Web2C 2023/dev) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./mom.tex
LaTeX2e <2022-06-01> patch level 3
L3 programming layer <2022-06-16>
(/usr/share/texmf.local/texmf/tex/latex/base/article.cls
Document Class: article 2021/10/04 v1.4n Standard LaTeX document class
(/usr/share/texmf.local/texmf/tex/latex/base/size10.clo))
(/usr/share/texmf.local/texmf/tex/latex/base/inputenc.sty
(/usr/share/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/share/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/share/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/share/texmf.local/texmf/tex/latex/hyperref/hyperref.sty
(/usr/share/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/share/texmf.local/texmf/tex/latex/iftex/iftex.sty)
(/usr/share/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/usr/share/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(/usr/share/texmf.local/texmf/tex/latex/graphics/keyval.sty)
(/usr/share/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
(/usr/share/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/usr/share/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
(/usr/share/texmf-dist/tex/latex/hycolor/hycolor.sty)
(/usr/share/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
(/usr/share/texmf-dist/tex/latex/auxhook/auxhook.sty)
(/usr/share/texmf.local/texmf/tex/latex/hyperref/nameref.sty
(/usr/share/texmf-dist/tex/latex/refcount/refcount.sty)
(/usr/share/texmf-dist/tex/generic/gettitlestring/gettitlestring.sty
(/usr/share/texmf-dist/tex/latex/kvoptions/kvoptions.sty)))
(/usr/share/texmf.local/texmf/tex/latex/hyperref/pd1enc.def)
(/usr/share/texmf-dist/tex/generic/intcalc/intcalc.sty)
(/usr/share/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
(/usr/share/texmf.local/texmf/tex/latex/hyperref/puenc.def)
(/usr/share/texmf.local/texmf/tex/latex/url/url.sty)
(/usr/share/texmf-dist/tex/generic/bitset/bitset.sty
(/usr/share/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
(/usr/share/texmf.local/texmf/tex/latex/base/atbegshi-ltx.sty))
(/usr/share/texmf.local/texmf/tex/latex/hyperref/hdvips.def
(/usr/share/texmf.local/texmf/tex/latex/hyperref/pdfmark.def
(/usr/share/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty
(/usr/share/texmf.local/texmf/tex/latex/base/atveryend-ltx.sty)
(/usr/share/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty))))
(/usr/share/texmf.local/texmf/tex/latex/l3backend/l3backend-dvips.def)
(./mom.aux) (/usr/share/texmf-dist/tex/latex/ucs/ucsencs.def) (./mom.out)
(./mom.out)
! Argument of � has an extra }.
<inserted text> 
                \par 
l.10 \end{document}
                   
? x
No pages of output.
Transcript written on mom.log.
```

[log file with error](https://gist.github.com/balducci/4a37d9690f37bcd25f35e624628e7123#file-mom-log-bad)

However, if I replace the ``[utf8x]`` option with the ``[utf8]`` one,
or omit any option to inputenc altogether, the error goes away and the
dvi file is fine.

[log file no error](https://gist.github.com/balducci/4a37d9690f37bcd25f35e624628e7123#file-mom-log-good)

Moreover, when using the ``[utf8x]`` option, the error happens only with the latest latex2e version (``LaTeX2e <2022-06-01>
patch level 3; L3 programming layer <2022-06-16>``); if I use the previous latex2e version (``LaTeX2e <2021-11-15> patch level 1; L3
programming layer <2022-06-02>``), I get no errors.

||              LaTeX2e <2021-11-15>,pl1 |  LaTeX2e <2022-06-01>,pl3|
|--|--|--|
|[utf8x]|     no error    |                                 ERROR|
|[utf8]  |     no error       |                              no error|

The error happens only when both inputenc and hyperref are used: using
only one of them (either only inputenc or hyperref) works fine.

Also, the error is invariant with respect to the hyperref versions I
could test: v7.00{qrs}

thanks for any help
ciao
-gabriele

**Comment by balducci** [comment]
> Yes that is known. I wrote the maintainer of ucs some weeks ago and told them what they must do if they want to stay
> compatible with the changes in hyperref (which followed changes in the utf8 handling in latex).
> 
> My advice is: don't to use `utf8x`. It doesn't support the various improvement which have be done in the utf8 handling in latex,
> for example you can't load files with umlauts or use umlauts in `\label` with it.

thank you very much for clarifying things

**Comment by scottkosty** [comment]
The original example compiles now. However, if we specify `\usepackage{ucs}` on the second line, it fails on an updated TeX Live 2023. From what I understand, this failure might be expected now?

**Comment by davidcarlisle** [comment]
@scottkosty  "expected" might be putting it strongly, but "not surprising"

 utf8x by default does nothing now, but as a compromise compatibility for some specific existing documents if you explicitly load `ucs` then it and `utf8x` work as before, but that over writes all of latex's default unicode handling and things will go wrong. There really isn't much that can be said other than don't load the package. The alternative would be to make ucs do nothing as well, but that would stop some documents working that currently work.

**Comment by scottkosty** [comment]
@davidcarlisle Thanks, that is very helpful!

**Comment by gjaekel** [comment]
May we reopen this issue, please? 

Not using `ucs` and `utf8x` is a **must have** with our usecase. The problems occurs after updating _TexLive-2023_ < _TexLive-2021_ on _Gentoo_, and I was able to workaround by restoring the HyperRef-Package from the 2021 installation.

```
[...]
(/usr/share/texmf-dist/tex/latex/hyperref/pd1enc.def
File: pd1enc.def 2024-01-20 v7.01h Hyperref: PDFDocEncoding definition (HO)
)
(/usr/share/texmf-dist/tex/generic/intcalc/intcalc.sty
Package: intcalc 2019/12/15 v1.3 Expandable calculations with integers (HO)
)
\Hy@SavedSpaceFactor=\count288

(/usr/share/texmf-dist/tex/latex/hyperref/puenc.def
File: puenc.def 2024-01-20 v7.01h Hyperref: PDF Unicode definition (HO)
)
Package hyperref Info: Option `pdfa' set `true' on input line 4062.
Package hyperref Info: Option `unicode' set `true' on input line 4062.
Package hyperref Info: Option `pdfusetitle' set `true' on input line 4062.
Package hyperref Info: Option `bookmarks' set `true' on input line 4062.
Package hyperref Info: Option `bookmarksnumbered' set `true' on input line 4062
.
Package hyperref Info: Option `bookmarksopen' set `true' on input line 4062.
Package hyperref Info: Option `breaklinks' set `false' on input line 4062.
Package hyperref Info: Option `colorlinks' set `false' on input line 4062.

! Argument of Â has an extra }.
<inserted text>
                \par
l.4062 \ProcessKeyvalOptions{Hyp}

I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce 
```

The 2023-Version seems to pull some source referenced as `hyperref.source.r69523`, the 2021 pulls just `hyperref.source`. Inside the `hyperref.sty` I read the versions `\ProvidesPackage{hyperref}[2024-01-20 v7.01h % Hypertext links for LaTeX]` versus `\ProvidesPackage{hyperref}[2021-02-27 v7.00k % Hypertext links for LaTeX]`.

May someone identify the differences that lead to the issue and provide a fix for it? I the issue already fixed and I have to find a way to update to the latest version of _Hyperref_ on _Gentoo_, i.e. to understand the revesion number mentioned before?

**Comment by u-fischer** [comment]
> Not using ucs and utf8x is a must have with our usecase. 

 I guess the "Not" is not intended? 

> May someone identify the differences that lead to the issue and provide a fix for it? 

ucs redefines the utf8 handling of latex and that is not compatible with hyperref. There is no fix.

You are not saying why you need to use it, so it is not possible to suggest some alternatives.

**Comment by gjaekel** [comment]
@u-fischer 
>>| Not using ucs and utf8x is a must have with our usecase.
> I guess the "Not" is not intended?
Your're right :)

@davidcarlisle 
>It should not be used with new documents.
This is no new document, it's a legacy application using TeX as printing engine.

@u-fischer 
> ucs redefines the utf8 handling of latex and that is not compatible with hyperref. There is no fix.
> You are not saying why you need to use it, so it is not possible to suggest some alternatives.

Ute, you're wrong; it worked the last about 14 years, even with LiveTex-2021. There was no LiveTex-2022 for Gentoo at the time we did our last updates. But now, using LiveTex-2023, the *current* version of hyperref break it. As written, it will work again by just replacing the current hyperref with the older one without touching any other. Therefore, the breaking change is related to some commit in-between.

**Comment by davidcarlisle** [comment]
Note that the current setup where `utf8x` is by default a no-op so you pick up standard latex UTF-8 handling was done in consultation with the original authors of ucs/utf8x. Do you have any real examples where `utf8x` processing is required and you can not simply remove it? The `ucs` package cuts deeply through the standard latex encoding support, it really isn't feasible for other packages to have duplicated code paths for documents with and without ucs.  That is not a criticsm of `ucs` it predates LaTeX defaulting to UTF-8 and served an important need, but if LaTex  was ever to default to Unicode, something had to give.

>  This is no new document, it's a legacy application using TeX as printing engine.

the application is (presumably) generating new documents. If it is generating documents to run with a current latex, it should not be adding `utf8x` it should be using the default latex encoding which is UTF-8.

**Comment by gjaekel** [comment]
@davidcarlisle As written: This is inside an existing legacy application. This application isn't generating "new" documents. It generates always the same documents with different text inside. This is from a datasource and this data is technically passed as job-specific file with high level TeX "action" macros, which is `\include`d in a fixed main document.

And *please* notice that not I choose to use ucs/utf8x, but I have to fix the current problem. And this -- Elementary, my dear Watson! -- is related to the changes in hyperref, not by ucs/utf8x or other updates, as seen.

Seems that I had to fork the hyperref package and to find some guru who try to fix it there. Or at least to archive the old version and keep using it as long as possible.

**Comment by davidcarlisle** [comment]
@gjaekel  do you have an example generated document that you could show that generates the above error, and then we could perhaps suggest how to adjust it?

**Comment by gjaekel** [comment]
@davidcarlisle I may prepare and provide an example of a "job" direct to you by email. It contains no private data, but I still don't want to publish it here.

As you may see on top, the execution of pdftex will die before `\begin{document}` with the recent version of hyperref. For a first impression, the main document will be sufficient.

**Comment by davidcarlisle** [comment]
@gjaekel d.p.carlisle at gmail .com is my not very secret email address

**Comment by gjaekel** [comment]
Yea, it's listed on your GitHub profile.

**Comment by u-fischer** [comment]
only the preamble doesn't really say *why* you are using ucs. 

If you can't simply  disable ucs by commenting the package, you could try to disable the load by putting this before documentclass

~~~~
\makeatletter
\disable@package@load{ucs}{}
\makeatother
~~~~

**Comment by gjaekel** [comment]
@u-fischer Again, don't use the term "you" - I **not** the author of this at all.

Maybe I'm just to cumsy to explain it. But to my eyes your suggestion is just another way to get rid of the ucs package. But without, to my (very limited) knowledge you will not have the feature of character combine as used by the processed data
```
Kaufmann/Kauffrau f\SetUnicodeOption{combine}\unicodevirtual{u}̈\SetUnicodeOption{nocombine}r B\SetUnicodeOption{combine}\unicodevirtual{u}̈\SetUnicodeOption{nocombine}romanagement
```
I wonder if you may tell a set of macro definition that will allow to "do the job" without ucs/utf8x but with utf8 only. Beware, there may be a bunch of other macros, too -- but I expect not very much ones.

**Comment by davidcarlisle** [comment]
@gjaekel  isn't that just a weirdly complicated way of writing

`Kaufmann/Kauffrau f\"ur B\"uromanagement`

or

`Kaufmann/Kauffrau für Büromanagement`

?

**Comment by gjaekel** [comment]
No, it isn't because the datasource represents all letters using diacritical marks as combine chars: The source contains <u><U+0308> (\xCC88), not <ü>. In addition, a big range of diacritical marks are used with arbitrarily characters.

**Comment by gjaekel** [comment]
@davidcarlisle Sorry, Google Mail don't accept my attachments.

**Comment by davidcarlisle** [comment]
sure but if the system can write the combining character pair as `\SetUnicodeOption{combine}\unicodevirtual{u}̈\SetUnicodeOption{nocombine}`   
it could surely write it as   
`\"u` instead,

That said it wouldn't be too hard to just define those macros so that combination works, or simpler still use lualatex instead of pdflatex then you can simply use the character data including combining characters and not use macros at all.

**Comment by u-fischer** [comment]
> But to my eyes your suggestion is just another way to get rid of the ucs package. 

Yes. As I wrote it is not compatible.

> But without, to my (very limited) knowledge you will not have the feature of character combine

Well up-to-now you didn't say that you want to parse chars+combining accents. Personally I would use lualatex for documents with such an input, but beside this it shouldn't be difficult to write suitable commands. A current LaTeX inputs a lot of unicode data anyway.

**Comment by gjaekel** [comment]
Both: You're **very** welcome, feel free to do it! I'll try to find and then send you all the (Java-8) source code of the service daemon that contain the generator for the data file. Me was already told that there might be other, additional challenges appear if you replace pdftex by lua(a)tex. But hey, I just read that's not hard and difficult!

**Comment by gjaekel** [comment]
Thank you for discussion so far and have a good night!

**Comment by davidcarlisle** [comment]
The code really makes little sense now, the markup is excessively complicated and the output sub optimal, but I know you are where you are and these things happen.

Fixing up the combining characters isn't so hard eg something like 

```
%\usepackage{ucs} 
%\newcommand{\combword[1]}{\SetUnicodeOption{combine}#1%
%\SetUnicodeOption{nocombine}}

\def\utfdots{̈}
\def\utfaccute{́}
\def\utfcedila{̧}
\def\utftilde{̃}
\def\utfhat{̂}
\def\utfbreve{̆}
\def\utfgrave{̀}
\def\utfring{̊}
\def\utfcaron{̌}
\def\utfmacrom{̄}
\def\SetUnicodeOption#1\unicodevirtual#2#3\SetUnicodeOption#4{%
  \def\thisaccent{#3}%
  \ifx\thisaccent\utfdots
    \"{#2}%
  \else\ifx\thisaccent\utfaccute
      \'{#2}%
   \else\ifx\thisaccent\utfcedila
      \c{#2}%
   \else\ifx\thisaccent\utftilde
      \~{#2}%
   \else\ifx\thisaccent\utfhat
      \^{#2}%
   \else\ifx\thisaccent\utfbreve
      \u{#2}%
   \else\ifx\thisaccent\utfgrave
      \`{#2}%
   \else\ifx\thisaccent\utfring
      \r{#2}%
   \else\ifx\thisaccent\utfcaron
      \v{#2}%
   \else\ifx\thisaccent\utfmacro
      \={#2}%
   \else
    \show\thisaccent
    \ERROR
   \fi\fi\fi\fi\fi\fi\fi\fi\fi\fi}
```

similarly `\textalpha`... are defined by the current Greek setup, but then your test file (sent off this site) uses assorted other asian characers not set up by default and probably other ucs specific constructs,


I suspect the thing to do is just process it with an old hyperref, and not use the code suggested above.

I picked up release 7.00k zip from the github releases page



https://github.com/latex3/hyperref/archive/refs/tags/release-7.00k.zip

unzipped that, cd into that directory and ran

pdftex hyperref.ins

to unpack the files

then simply copied them all into the directory with your test file (to avoid messing with my local paths

and then your file ran without error.

**Comment by gjaekel** [comment]
Dear David,
thank you for the time you spend to me! 

>Fixing up the combining characters isn't so hard eg something like

I'm far away to develop such TeX code by my own but I'm able to understand it.

>  but then your test file (sent off this site) uses assorted other asian characers not set up by default and probably other ucs specific constructs,

That's the imponderability, because this is test file is just a random choice. Any data entry of the DNB's library catalog may be the source. And this consist of all publications in German language in the one hand, but all publications in any language published in Germany. 


> I suspect the thing to do is just process it with an old hyperref, and not use the code suggested above.

That's the way I already proved, it solve the issue for the test file and with very high probably for any other. But by your description I learned a way to temporary prepare/provide other versions of the package without a "global impact". This offers the possibility to check other releases with an acceptable effort. This may allow to locate the breaking change.

**Comment by davidcarlisle** [comment]
@gjaekel 

> But by your description I learned a way to temporary prepare/provide other versions of the package without a "global impact". This offers the possibility to check other releases with an acceptable effort. This may allow to locate the breaking change.

I think you misunderstood my suggestion, which was to use that in production not as a debugging aid

If you unpack the old hyperref and put the `.sty` files into some directory that you distribute with the program, you can run pdflatex as

```
TEXINPUTS="/path/to/where/you/put/old/hyperref:" pdflatex your-document.tex
```

The TEXINPUTS with the trailing `:` will make (for this process only) tex look first in the old hyperref then (because of the trailing colon) look in the standard paces for all other files and fonts needed,

There is no breaking change in hyperref. The breaking change happened ten years ago when LaTeX switched to supporting Unicode by default. Since that time the `ucs` package has only been  usable in restricted cases that do not assume any existing support for Unicode.  It may have accidentally been the case that the documents produced by this application happened to work until now but, `hyperref` can not support the `ucs` package and while, as you see, we can personally help to offer solutions to your problem, we can not commit to maintaining two code paths in `hyperref` forever. `ucs` is simply not supportable with current latex as it redefines its core text handling.

As well as being incompatible with hyperref ucs is incompatible with the tagging support for accessible pdf (which is also driving many of the recent changes to hyperref). It may be that the pdfs used here are just used in printing and not distributed, but they  will certainly not meet any accessibililty standards and have no effective way to do so if using `ucs`/`utf8x`.

So I would advise using the old hyperref, set up as above, but longer term, look to switching to lualatex which can use unicode OpenType fonts and supports combining characters and other things by default, so most of the complicated tex macros causing issues here are simply not needed.

**Comment by u-fischer** [comment]
@gjaekel 

you can try something like the following. But be aware that this only fixes the error. It does not (re)enable ucs support in hyperref or in LaTeX itself. E.g. the Umlauts in the bookmarks or in the pdftitle will be wrong and you will have to use commands instead, and something like `\label{straße}`  will error. 

~~~~
\documentclass{article}
\usepackage{ucs}
\usepackage[utf8x]{inputenc}
\usepackage{hyperref}
\makeatletter\def\HyPsd@expand@utfviii{}\makeatother
\listfiles

\begin{document}
\tableofcontents
\section{Grüße  Gr\"u\ss e}

\end{document}
~~~~


![Image](https://github.com/user-attachments/assets/ae9c43e2-a5c9-48e9-aefb-b8b07c60fed0)

**Comment by gjaekel** [comment]
@davidcarlisle: No-no, I understand. It's quite clear that you will not patch hyperref "here" at the official sources. But for our usecase, there **is** a breaking change between the official _LiveTeX-2021_ and _LiveTeX-2023_. And in our environment with a fixed purpose, I was able to trace it down to the version of hyperref in that way that downgrading this and only this to the former used version will be sufficient to mitigate the local issue. That's quite dirty, not sustainable, and not a general solution at al. But it's the most practical solution for short terms.

For some kind of academic interest, I'm nevertheless interested in to see the causing change in detail and maybe to understand it. This may help, if something similar will appear in the upcoming time.

For the long term, I completely the suggested way to switch to refresh the application over all. But that's completely out of my scope; I just can report the facts and recommend it.

**Comment by gjaekel** [comment]
My(!) issue occurs on the transition `hyperref-release-7.00{m,n}`

To first orientation, here the diff for the `ChangeLog.txt`
```
diff -r -u hyperref-release-7.00m/ChangeLog.txt hyperref-release-7.00n/ChangeLog.txt
--- hyperref-release-7.00m/ChangeLog.txt        2021-06-07 11:16:15.000000000 +0200
+++ hyperref-release-7.00n/ChangeLog.txt        2022-02-22 00:58:21.000000000 +0100
@@ -1,3 +1,31 @@
+2022-02-21 Ulrike Fischer/David Carlisle
+    * a pdftex version newer than 1.10 (from 2003) is assumed
+    * removed tests for numexpr/dimexpr: etex is now required
+    * expand utf8 chars even if they are protected (preparation for
+      changes in the format)
+    * moved patches for revtex.cls to an external package
+    * added a key next-anchor to set the next anchor name.
+    * added a command \hyperget to retrieve anchor names.
+    * moved the patch for foiltex into an external package
+    * removed compability code for latex2html, this is now provided
+      by html.sty directly.
+    * removed patch for seminar, this is now in the class itself
+    * moved (basically unneeded) listings patches to external
+    package
+    * removed patch for titletoc, is now done by titletoc itself.
+    * removed lastpage patch, is no longer used as lastpage supports
+    hyperref directly.
+    * removed non-e-tex version of \hypercalcbp, e-tex is required
+    for hyperref now, removed the now unneeded internal command
+    \hypercalcbpdef.
+    * removed old, no longer needed fix for frenchb.ldf 2010/08/21 v2.5a
+    * removed patches for spanish, they are now in spanish.ldf
+    * removed hyperref-langpatches.sty, it is now empty and
+    unneeded.
+    * removed a fix for varioref which is no longer needed since
+    2019.
+
+
```

The bullet pont `expand utf8 chars even if they are protected (preparation for changes in the format)` catch my eyes.

**Comment by gjaekel** [comment]
Bingo, the introduced ` \HyPsd@expand@utfvii` triggers the issue. If I disable it, the job run through.
```
# diff -u hyperref.sty{.20250117-131240,} 
--- hyperref.sty.20250117-131240	2025-01-17 13:12:40.918181000 +0100
+++ hyperref.sty	2025-01-17 13:38:16.517060000 +0100
@@ -1777,7 +1777,7 @@
     \lccode`\~=`^^f4\relax
   \lowercase{\endgroup
     \def\HyPsd@UTFviii{%
-      \HyPsd@expand@utfvii
+%      \HyPsd@expand@utfvii
       \let\UTFviii@two@octets\HyPsd@UTFviii@two
       \let\UTFviii@three@octets\HyPsd@UTFviii@three
       \let\UTFviii@four@octets\HyPsd@UTFviii@four 
```

```
\ifcsname UTFviii@loop\endcsname
 \def\HyPsd@expand@utfvii{%
    \count@"C2
    \@tempcnta"F5
    \def\UTFviii@tmp{\expandafter\def\expandafter~\expandafter{~}}%
    \UTFviii@loop
  }
\else
 \def\HyPsd@expand@utfvii{}
\fi
```

**Comment by gjaekel** [comment]
... and this change also will make `hyperref-release-7.01l` running. Attention: I don't checked the resulting PDF file at the moment.

**Comment by u-fischer** [comment]
@gjaekel 

> Bingo, the introduced \HyPsd@expand@utfvii triggers the issue.

Yes, as I told you above disabling the command avoids the errors. I know which change we made and I know also why and when. 
But as I told you too above disabling the command is not a real fix as this breaks the support for Umlauts in the bookmarks.

**Comment by gjaekel** [comment]
The change make `hyperref-release-7.01l` running, but the PDF is corrupt. To much has been changed in the meantime.
But the PDF produced with the patched `hyperref-release-7.00n` is loadable and seems to be OK from the first view.

**Comment by u-fischer** [comment]
What do you mean by "the PDF is corrupt"?

**Comment by gjaekel** [comment]
> What do you mean by "the PDF is corrupt"?

Not valid, not processable by _evince_.

**Comment by gjaekel** [comment]
OK, `\HyPsd@expand@utfvii` is used once inside the declaration of `\HyPsd@UTFviii`. And this is used once in the declaration of `\pdfstringdef#1#2`

The macro `\pdfstringdef` is used many times. My question is: What is the purpose of / what get's lost by disabling `\HyPsd@expand@utfvii`. In other words: What's the motivation of this feature.

With this information I guess we can estimate if this hits this usecase here in some way.

**Comment by u-fischer** [comment]
\pdfstringdef converts text into a form that can be used inside a PDF in many places, e.g. for destination names, the info dictionary  and in bookmarks. It is one of the core commands of hyperref, very large and complicated and used in many places. E.g.

~~~~
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\pdfstringdef\blub{grüße}
\show\blub
\end{document}
~~~~

gives

~~~~
> \blub=macro:
->\376\377\000g\000r\000\374\000\337\000e.
~~~~

`\HyPsd@expand@utfvii` is there to allow the correct processing of umlauts. As they are now protected commands, hyperref has to expand them first. If you disable the command the above example would give (in a current LaTeX)

~~~~
> \blub=macro:
->\376\377\000g\000r\000Ã\000¼\000Ã\000Ÿ\000e.
~~~~

and so you would see odd text containing `Ã¼ÃŸ` in the bookmarks.

I don't think that disabling `\HyPsd@expand@utfvii` in itself can lead to a corrupt PDF, probably something else in your document is not compatible, but to say more I would need the corrupted PDF and code that I can compile to try to reproduce that.

**Comment by gjaekel** [comment]
I confirm that
> odd text containing Ã¼ÃŸ in the bookmarks.

happens with the disabled `\HyPsd@expand@utfvii`. For this reason, for my case the problem with the macro must be solved in a way to keep the intended functionality but not to break the TeX processing.

**Comment by u-fischer** [comment]
> For this reason, for my case the problem with the macro must be solved in a way to keep the intended functionality but not to break the TeX processing.

Well you could try 

~~~~
\documentclass{article}
\usepackage{ucs}
\usepackage[utf8x]{inputenc}
\usepackage{hyperref}
\makeatletter
\let\oriHyPsd@expand@utfviii\HyPsd@expand@utfviii
\def\HyPsd@expand@utfviii{\inputencoding{utf8}\oriHyPsd@expand@utfviii}\makeatother
\listfiles

\begin{document}
\tableofcontents
\section{Grüße  Gr\"u\ss e}

\end{document}
~~~~

but this probably not fast. 

Btw: I doubt that using an old hyperref.sty with a new LaTeX will work without errors in the long run and I would avoid that option.
