### ISSUE TITLE
documentation: percent character needs escaping in nested \href

### ISSUE THREAD

**Issue by bastistician** [latex3/hyperref#249]
https://github.com/latex3/hyperref/blob/d656e8195a5a194276e1c52bcbf70a4cccc99655/doc/hyperref-doc.tex#L1276-L1277

It seems that the tilde does *not* need to be escaped in `\href` URLs, even if used as an argument of another command.
For example, the following minimal LaTeX document compiles fine:

```tex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\emph{\href{https://example.org/~a}{tilde}}
\end{document}
```

However, the hash and **percent** symbols do need to be escaped in that case.
For example, the following fails, but would work with backslash-escaped percent or without the `\emph`:

```tex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\emph{\href{https://example.org/a%20b}{space}}
\end{document}
```
```
Runaway argument?
{\href {https://example.org/a\end {document} 
! File ended while scanning use of \emph .
```

Could this be a typo in the documentation referenced at the top?

**Comment by muzimuzhi** [comment]
I see no typos in doc. The referenced doc talks about hash and tilde only, but your second example demonstrates percent char which _do_ need to be escaped.

**Comment by bastistician** [comment]
Thanks for confirming. With "typo" I meant that the `\~{}` could be replaced by `\%` in that sentence.

Note that both # and % need no escaping in "normal" use, but they do if `\href` is used as an argument to another command. In contrast, the tilde seems to work without escaping (but maybe other examples are needed, I'm not sure).

**Comment by u-fischer** [comment]
yes I think `` \%``  is meant in this context and I changed the text. The next update will have it.

**Comment by muzimuzhi** [comment]
> With "typo" I meant that the `\~{}` could be replaced by `\%` in that sentence.

@bastistician You're right. I overlooked the "(unless ...)" part, sorry.
