### ISSUE TITLE
Strange “??” bug when \label closes the document after \pagebreak, \newpage, etc.

### ISSUE THREAD

**Issue by madmurphy** [latex3/hyperref#253]
The following manuscript prints “**??**” in the first page:

``` latex
\begin{document}

\maketitle
See page \pageref{example-label}.

\newpage

Page 1

\newpage

Page 2

\newpage

Page 3

\label{example-label}
\end{document}
```

However if I replace `\label{example-label}` with `Hi! \label{example-label}` or `\label{example-label} Hi!`, things work again.

The bug happens only when `\label` is the last macro before the end of the document.

--madmurphy

**Comment by davidcarlisle** [comment]
th code you supplied can not be run at all, if I add a preamble and run latex twice I get a link "4"

```
\documentclass{article}
\usepackage{hyperref}
\title{}
\begin{document}



\maketitle

See page \pageref{example-label}.



\newpage



Page 1



\newpage



Page 2



\newpage



Page 3



\label{example-label}

\end{document}
```

**Comment by u-fischer** [comment]
In your first example you had text on the last page:

~~~~
\newpage

Page 3

\label{example-label}
\end{document}
~~~~

Now you show a page without any text

~~~
\newpage{}

\label{example-label}
\end{document}
~~~

And yes that doesn't work (and it is unrelated to hyperref). A label is only written if the page is actually shipped out.
