### ISSUE TITLE
Multiple # (hash) characters lead to incomplete link adresses.

### ISSUE THREAD

**Issue by fspreck-indiscale** [latex3/hyperref#254]
See, e.g., https://tex.stackexchange.com/questions/654824/two-consecutive-hash-caracters-in-url-href-in-latex-produce-incomplete-link-adre and https://tex.stackexchange.com/questions/540169/link-with-multiple-does-not-work-properly/540185#540185

Having multiple `#` signs in a link address leads to incomplete link addresses in the compiled PDF which are cut before the second `#` sign.

I.e., 

```latex
\href{https://matrix.org/\#/\#mychannel:matrix.org}{\#mychannel:matrix.org}
```

leads to the link address https://matrix.org/#/.

It really seems to be caused by having two consecutive hash characters in the URL since deleting the first # character in the URL, i.e.,

```latex
\href{https://matrix.org//\#mychannel:matrix.org}{\#mychannel:matrix.org}
```

results in the link URL https://matrix.org//#mychannel:matrix.org.

## Complete code example

(this is beamer, but the same happens, e.g., in an article)

```latex
\documentclass[ignorenonframetext,aspectratio=43]{beamer}

\usepackage{xcolor}

\begin{document}
\begin{frame}
  \href{https://matrix.to/\#/\#mychannel:matrix.org}{\#mychannel:matrix.org}
\end{frame}
\end{document}
```

**Comment by davidcarlisle** [comment]
we may possibly be able to do something but such a string isn't a valid URI, the second # is supposed to be % encoded as %23

eg https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

> Of the ASCII character set, the characters : / ? # [ ] @ are reserved for use as delimiters of the generic URI components and must be percent-encoded

**Comment by fspreck-indiscale** [comment]
Thanks for the reply, @davidcarlisle!  You're right, using

```latex
\href{https://matrix.org/\#/\%23mychannel:matrix.org}{\#mychannel:matrix.org}
```

works like a charm.  Interestingly though,

```latex
\href{https://matrix.org/\%23/\%23mychannel:matrix.org}{\#mychannel:matrix.org}
```

i.e., replacing both `#` by `%23` is not resolved properly by the browser, but that is probably rather a problem of my pdf viewer (evince 42.3) and/or my browser (firefox 103.0.2).

**Comment by davidcarlisle** [comment]
> replacing both # by %23

That is a different URL entirely. That was my point: a URI can have at most one `#`

`http://example.com/aa/bb/cc#foo`

is a refererence to `http://example.com/aa/bb/cc` and an internal fragment id  `foo`.  So if either the path to the resource or the fragment id have a # that # must be %-encoded. 

But

`http://example.com/aa/bb/cc%23foo`

is a reference to the resource  `http://example.com/aa/bb/cc#foo`  which is typically a 404 error unless the server has a file of name `cc#foo`

`http://example.com/aa/bb/cc#foo%23br`

is a refererence to `http://example.com/aa/bb/cc` and an internal fragment id  `foo#bar`, which is what you want here.
