### ISSUE TITLE
Expanded arguments of \cmd are printed in backref.pdf

### ISSUE THREAD

**Issue by dr-scsi** [latex3/hyperref#255]
I can't tell why but all calls of `\cmd` produce expanded results in `backref.pdf`.   Take for example this part of the code:
```
% \subsection{Formatting of the back references list}
%
%    The back references list is separated from the entry
%    by \cmd{\newblock},
%    if the used bibliography package supports this. The package options
%    control the kind of back references (page numbers, sections numbers),
%    whereas the hooks control the formatting.
%
%    There are two hooks \cmd{\backref} and a new hook \cmd{\backrefalt},
%    available since version 1.21 of package |backref|. The former one
%    is enabled by default.
```
which looks like this in `backref.pdf`:

![backref](https://user-images.githubusercontent.com/59777257/186145454-cbcb4675-e006-4520-b931-d3ab6eaa13da.png)

This is with v1.41, last revised 2021/02/04.

**Comment by u-fischer** [comment]
yes, sorry that was a bug of the definition of `\cmd` in the doc package. This has already been corrected and in the next version the documentation will be okay again.

**Comment by dr-scsi** [comment]
Ah, thanks for the hint.  Now I see report [#874](https://github.com/latex3/latex2e/issues/874) in latex2e repo.  Sorry for the noise.
