### ISSUE TITLE
set pdfbordercolor to the same as the text color

### ISSUE THREAD

**Issue by kusma** [latex3/hyperref#257]
It'd be really useful to be able to automatically underline links in PDFs and use `colorlinks=false`, but without having to know up front what the color of the text will be everywhere.

So something like `colorborders=false` that made the borders the same color as the text (e.g behaving similar to `\underline`) would be great.

**Comment by u-fischer** [comment]
Please add a small but complete example that demonstrates your feature request which can be used for tests.

**Comment by u-fischer** [comment]
Closing as no example has been provided.
