### ISSUE TITLE
disabling patch for `\descriptionlabel` buggy

### ISSUE THREAD

**Issue by mrpiggi** [latex3/hyperref#258]
https://github.com/latex3/hyperref/blob/f0675e206b6215cfb3094abacb6f836dbdaadaa0/nameref.dtx#L536-L545

According to the documentation, `\@ifundefined{NR@nopatch@longtable}` should be `\@ifundefined{NR@nopatch@lists}`

**Comment by u-fischer** [comment]
Hm, yes looks like a copy and paste error.

**Comment by mrpiggi** [comment]
for sure

**Comment by u-fischer** [comment]
7.00u sent to ctan.
