### ISSUE TITLE
The pdf output shows both Figure index and the caption.

### ISSUE THREAD

**Issue by ngoctuansqtt** [latex3/hyperref#262]
Hi, I currently use the  hyperref pakage to creat the reference link to the figure. However, the pdf output shows both Figure Index and the defined caption on my latex file. This issues has occured after I updating my packages using Miktex console. Please give me some idea  to resolve this problem. Thank you very much.

Here is my code:

\usepackage{hyperref}
\usepackage{cite}
\usepackage[hang,large,bf]{caption}
\usepackage{caption}

...

\begin{figure}[!h]
	\centerline{\includegraphics[width=0.68\linewidth]{Chuong1/pic/powertrace_measurements}}	
	\caption{Power consumption measurement setups.}
	\label{Fig:powertrace_measurements}
\end{figure}

The numbers in Fig~\ref{Fig:powertrace_measurements} illustrate in which sequence the component interact with each other when a power trace is recorded.

And this is the output:
![image](https://user-images.githubusercontent.com/9635652/203735354-019b72de-5afc-4ae4-a695-26be283ff7ad.png)

**Comment by u-fischer** [comment]
don't show only snippets of your code. Always create a small but complete document that can be used for a test and attach also the log-file of the compilation. This here works fine for me:

~~~~
\documentclass{article}
\usepackage{hyperref}
\usepackage{cite}
\usepackage[hang,large,bf]{caption}

\begin{document}
\begin{figure}[!h]
figure
\caption{Power consumption measurement setups.}
\label{Fig:powertrace_measurements}
\end{figure}

The numbers in Fig~\ref{Fig:powertrace_measurements} illustrate in which 
sequence the component interact with each other when a power trace is 
recorded. 
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/203835521-06cbd620-d269-47bc-a909-98e896a35a26.png)

**Comment by u-fischer** [comment]
I'm closing this as no example was provided to reproduce the problem.
