### ISSUE TITLE
visibility of choice parameter of \ChoiceMenu

### ISSUE THREAD

**Issue by j-hap** [latex3/hyperref#263]
System:
Win10
MiKTeX 22.8.28
XeTeX, Version 3.141592653-2.6-0.999994
LuaHBTeX, Version 1.15.1 (MiKTeX 22.8.28)
pdfTeX, Version 3.141592653-2.6-1.40.24

I'm somewhat confused on how the `\ChoiceMenu` with radio option is expected to be used:

1. the label parameter defines a label for the whole group, the `name` option gives the button group a name in meta information of a generated pdf. Unfortunately the choice parameter is always printed on the left side of the radiosymbol. one can redefine `\LayoutChoiceField` like this: `\renewcommand{\LayoutChoiceField}[2]{\leavevmode #2 #1}` but that places only the label of the whole group on the right of the group. Also I have to misuse the choice parameter to insert a `\quad` between choices if I want the buttons and their labels to have spacing.
2. the label parameter defines a label for each button. That way I can place it one the right side of each button. By defining the same `name` option on multiple `\ChoiceMenu`s, I can achieve true radio button behavior, see https://tex.stackexchange.com/questions/371974/how-do-i-get-choice-radio-box-on-the-left-side-of-text-using-hyperref .

So far I opted for Method 2, because I need the labels to the right of the symbol and also want to position members of a group freely. When defining multiple `\ChoiceMenu`s with the same name option, I do not want / need to define the choice parameter (`#3`). When I don't define it, the radiosymbol is not shown, so I need at least one character in there. I opted for `\vphantom{a}`, that way I'm sure no character is inserted left of the radiosymbol, that could potentially mess with the formatting. I get a warning that this token is not allowed in a PDF string.

When I do that, everyhing looks as I want, but looking at the form data in Acrobat, all radio buttons (without a printed choice) have the same object name: `\376\377\000\040`

The ones in the example where the choice parameter is used get the same prefix, but every character is preceeded by a \0
`\376\377\000O\000p\000t\000i\000o\000n\000A`

Especially the name itself looks like some kind of encoding problem to me. Don't know about the prefix though.
The result is the same with pdflatex, xelatex and lualatex

Here's my ideas for a fix:
- the naming of the form object should match the given choice parameter
- an option `hidechoice` or something to not include the choice parameter as text in the genrated pdf, only as a form object name

That way one could use individual `\ChoiceMenu`s, assign them the same `name` option (which is correctly represented as the group name in the pdf) and also have a good "tag" name for the form object while also giving an individual label, that can be placed where ever.

minimal example:
```
\documentclass[11pt, a4paper]{article}
\usepackage{hyperref} % for form fields
\usepackage{pifont} % for \ding
\setlength\parindent{0cm}

\begin{document}
\begin{Form}
    A single \texttt{\textbackslash{}ChoiceMenu} with a group label\\
    \ChoiceMenu[radio, radiosymbol=\ding{108}, name=options1]{Options:\quad}{OptionA,OptionB}

    \medskip

    A single \texttt{\textbackslash{}ChoiceMenu} with a group label and spacing between options\\
    \ChoiceMenu[radio, radiosymbol=\ding{108}, name=options2]{Options:\quad}{OptionA,\qquad{}OptionB}

    \medskip

    There is no way to put the choice text to the right of each button. Using
    individual button, one can to that with

    \medskip

    \texttt{\textbackslash{}renewcommand{\textbackslash{}LayoutChoiceField}[2]{\textbackslash{}leavevmode \#2 \#1}}

    \medskip

    \renewcommand{\LayoutChoiceField}[2]{\leavevmode #2 #1}
    % \ChoiceMenu[radio, radiosymbol=\ding{108}, name=options3]{OptionA}{\vphantom{A}}
    \ChoiceMenu[radio, radiosymbol=\ding{108}, name=options3]{OptionA}{ }
    \qquad
    % \ChoiceMenu[radio, radiosymbol=\ding{108}, name=options3]{OptionB}{\vphantom{B}}
    \ChoiceMenu[radio, radiosymbol=\ding{108}, name=options3]{OptionB}{ }

    \medskip

    Looking back at the single \texttt{\\ChoiceMenu} this only places the group
    label to the right, which is not what I need.\\
    \ChoiceMenu[radio, radiosymbol=\ding{108}, name=options4]{Options:\quad}{OptionA,OptionB}
\end{Form}
\end{document}
```

Thank you for your work on latex <3

EDIT:
I tried setting
`\renewcommand{\LayoutChoiceField}[2]{\leavevmode{}#1}`
to suppress printing the choice, but that also hid the radiosymbol

**Comment by j-hap** [comment]
Thank you, I'll give that a try!

**Comment by simonkurka** [comment]
My evince doesn't work correctly with repeated `\ChoiceMenu` calls with the same name. After clicking 3 times between Options of different ChoiceMenu calls, it breaks. While research i stumbled upon this issue-entry.

As explained in https://github.com/latex3/hyperref/issues/3#issuecomment-408598838 only the first option is added to a list of fields. With another call of `\ChoiceMenu` the first option of that call is also added to the list and seems to break things in certain viewers.

I worked around it by adding a `continue` property and patching the Radio-Group generation. When adding the `continue` property it pretends to skip the first option and always starts with option 2.

Actually different option values did not make any difference to me.

```tex
\makeatletter
\newif\ifFld@continue
\Fld@continuefalse
\define@key{Field}{continue}[true]{%
  \lowercase{\Field@boolkey{#1}}{continue}%
}
\patchcmd{\@@Radio}
{\Fld@listcount=0}
{\Fld@listcount=\ifFld@continue0\else1\fi}
{\typeout{Patching of @@Radio succeeded.}}
{\typeout{Patching of @@Radio failed.}}
\makeatother

\ChoiceMenu[name=RadioGroup,radio]{}{a,b,c,d}\\
\ChoiceMenu[name=RadioGroup,radio,continue]{}{e}
```

I hope this is helpful for people stumbling across the same problem.
