### ISSUE TITLE
Missing declaration for "nswissgerman" and "swissgerman"

### ISSUE THREAD

**Issue by ilian002** [latex3/hyperref#264]
# Problem description:
I use hyperref together with the package: `\usepackage[nswissgerman]{babel}`.
I noticed that the references in the document use English names. These names are loaded correctly in hyperref with the option `\usepackage[ngerman]{babel}`.

## Proposed solution from  babel-german owner [@jspitz](https://github.com/jspitz) 
Please add these two lines to `hyperref.sty` :
```
\HyLang@DeclareLang{nswissgerman}{german}{}
\HyLang@DeclareLang{swissgerman}{german}{}
```
## minimal working example:
```
\documentclass{article}
\usepackage[nswissgerman]{babel}
\usepackage{hyperref}
\usepackage{biblatex}
\begin{document}
\section{MWE} \label{section}
\subsection{subsection} \label{subsection}
\autoref{section} \ \autoref{subsection}
\end{document}
```
Original Post in repo: [ babel-german (issue #7)](https://github.com/jspitz/babel-german/issues/7#issue-1491467549)

**Comment by u-fischer** [comment]
this is resolved in the version 7.00w I just uploaded to ctan.
