### ISSUE TITLE
URL including special characters do not work in the frame env

### ISSUE THREAD

**Issue by atsuyaw** [latex3/hyperref#267]
I encountered a problem with `\href{}{}` not being able to handle URLs containing `%` in Beamer documents.
The cord was such one:
```tex
\documentclass[dvipdfmx]{beamer}
\usepackage{url} 
\usepackage{hyperref}

\begin{document}
\begin{frame}
    \url{https://www.google.com%a}

    \href{https://www.google.com%a}{Google}
\end{frame}
\end{document}
```
Then, the LaTeX compiler out the following message:
```
Runaway argument?
\url {https://www.google.com\par \href {https://www.google.com\end {f\ETC.
! File ended while scanning use of \frame.
<inserted text> 
                \par 
```
Here, please note that the `\url{}` also does not work.

In the case without the `frame` environment, the error does not appear but outs
```
Package hyperref Message: Stopped early.
```
and a resultant:
![image](https://user-images.githubusercontent.com/68371029/210201724-596e2139-8bc0-4dda-a0ef-9864e44cfed8.png)

Therefore, the `\href{}{}`/`\url{}` may not work correctly in specific environments.

**Comment by u-fischer** [comment]
Use the `fragile` option for the frame.

**Comment by atsuyaw** [comment]
@u-fischer 
Oh, the behavior of `href` is the same to `verb`, right?
Thank you!

**Comment by u-fischer** [comment]
> Oh, the behavior of `href` is the same to `verb`, right?

Yes, at least if the url contains special chars like `%`  or `#`.
