### ISSUE TITLE
Documentation error: punec-greek.def renamed to puenc-greekbasic.def

### ISSUE THREAD

**Issue by gmilde** [latex3/hyperref#269]
puenc-greek.def was renamed to puenc-greekbasic.def in commit 5ca026a91e on Feb 27, 2021.
The manual still shows the old name in section
7.29 [puenc encoding, puenc-greek.def and puenc-extra.def](https://ftp.mpi-inf.mpg.de/pub/tex/mirror/ftp.dante.de/pub/tex/macros/latex/contrib/hyperref/doc/hyperref-doc.html#x1-570007.29)

**Comment by muzimuzhi** [comment]
Issue title contains a mis-spelling: `puenc-greek.def` not `punc-greek.def`, note the missing `e` in `pu-enc`.
