### ISSUE TITLE
strange composite definition in puenc-greekbasic.def

### ISSUE THREAD

**Issue by gmilde** [latex3/hyperref#271]
With the MWE
~~~
\documentclass[]{article}
\usepackage[LGR]{fontenc}
\usepackage[unicode]{hyperref}
\begin{document}
\section{\texorpdfstring{\"I \"'i}
        {\textIotadieresis \'\textIotadieresis \"'\textiota}}
\end{document}
~~~
I get in the PDF sidebar toc
a GREEK CAPITAL LETTER IOTA WITH DIALYTIKA for `\textIotadieresis` 
but a GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS for `\'\textIotadieresis`.

I don't know, whether the composite definition for `\'\textIotadieresis`
is required for backwards compatibility or can be safely removed.
(There is no GREEK CAPITAL LETTER IOTA WITH DIALYTIKA AND TONOS  in Unicode.)

The "logical" macro `\'\textiotadieresis` does not work because `\textiotadieresis` is not defined. With "textalpha" or the "greek"  option of Babel, the LICR for  ΐ is `\'"\textiota`.

**Comment by u-fischer** [comment]
Well `\"'\textiota`  (`\'"\textiota`, both seems to work) obviously relies on a ligature and is not something hyperref can use. I agree that it looks a bit odd that hyperref uses `\textIotadieresis` for the capital iota and also for the small iota with tonos, but my guess would be that this was done to avoid the need for another command. One could add `\textiotadieresis` as an alias but I don't think that one should remove the current composite. 

Btw: unicode is the default since quite some time and so not needed. And naturally using the utf8 chars make the code much shorter and less confusing:

~~~~
\documentclass[]{article}
\usepackage[LGR]{fontenc}
\usepackage{hyperref}
\begin{document}
\section{Ϊ ΐ }
 \end{document}
~~~~

**Comment by gmilde** [comment]
> Well `\"'\textiota` (`\'"\textiota`, both seems to work) obviously relies on a ligature and is not something hyperref can use.

However, it is not a ligature and works in a pdf-string. Look at the PDF output of:
~~~
\documentclass{article}
\ifdefined \UnicodeEncodingName
  \usepackage{fontspec}
  \setmainfont{DejaVu Serif}
\fi
\usepackage[greek]{babel}
\usepackage[unicode]{hyperref}
\begin{document}
\section{\"'\textiota \"'ι}
\end{document}
~~~
(the latter may be helpful if you don't have a ΐ on your keybord).
You may compile with pdflatex, xelatex, or lualatex,
`[unicode]` is still required with pdflatex and TL20 (Debian/stable).

The reason why combined accents like `\"'` or `~<` work also in TU and PU is a "chained composite" definition: e.g. greek-fontenc.def defines
`\DeclareTextCompositeCommand{\"}{\LastDeclaredEncoding}{\'}{\accdialytikatonos}`
and puenc-greek.def defines
~~~
\DeclareTextCommand{\accdialytikatonos}{PU}[1]{#1\83\010\83\001}
\DeclareTextCompositeCommand{\accdialytikatonos}{PU}{\textiota}{\83\220} % ΐ
\DeclareTextCompositeCommand{\accdialytikatonos}{PU}{\textupsilon}{\83\260} % ΰ "03B0
~~~

**Comment by gmilde** [comment]
> Well `\"'\textiota` (`\'"\textiota`, both seems to work) obviously relies on a ligature and is not something hyperref can use.

However, it is not a ligature and works in a pdf-string. Look at the PDF output of:
~~~
\documentclass{article}
\ifdefined \UnicodeEncodingName
  \usepackage{fontspec}
  \setmainfont{DejaVu Serif}
\fi
\usepackage[greek]{babel}
\usepackage[unicode]{hyperref}
\begin{document}
\section{\"'\textiota \"'ι}
\end{document}
~~~
(the latter may be helpful if you don't have a ΐ on your keybord).
You may compile with pdflatex, xelatex, or lualatex,
`[unicode]` is still required with pdflatex and TL20 (Debian/stable).

The reason why combined accents like `\"'` or `~<` work also in TU and PU is a "chained composite" definition: e.g. greek-fontenc.def defines
`\DeclareTextCompositeCommand{\"}{\LastDeclaredEncoding}{\'}{\accdialytikatonos}`
and puenc-greek.def defines
~~~
\DeclareTextCommand{\accdialytikatonos}{PU}[1]{#1\83\010\83\001}
\DeclareTextCompositeCommand{\accdialytikatonos}{PU}{\textiota}{\83\220} % ΐ
\DeclareTextCompositeCommand{\accdialytikatonos}{PU}{\textupsilon}{\83\260} % ΰ "03B0
~~~

**Comment by u-fischer** [comment]
> However, it is not a ligature 

I meant the `'` on its own:

~~~~
\documentclass[]{article}
\usepackage[LGR]{fontenc}

\begin{document}
\textiota \quad '\textiota \quad  '\/\textiota
\end{document}
~~~~

gives (with pdflatex)

![image](https://user-images.githubusercontent.com/4047173/216813504-936af845-e636-4fb7-bdaf-1eceb4fb51a8.png)

and shows in the log `\LGR/cmr/m/n/10  (ligature 'i)` (and doesn't work in the bookmarks).

If you have an additional accent command it can naturally handle the ' too. 

> Users get this when loading Babel with the "geek" option or "textalpha", so there may be no need
> to duplicate it from the "hyperref" side in puenc-greekbasic.def.
> A small comment documenting the "odd" `\'\textIota` expansion may suffice.

I would greatly prefer not to add to hyperref language specific descriptions or code.  Nowadays probably 95% of all document are "for the screen", and so language packages should imho not only support and describe how to print characters but also how to get the right output in the bookmarks, the document window title, the keywords in the metadata. With the hooks it is now easy to add code conditionally.

**Comment by gmilde** [comment]
> I would greatly prefer not to add to hyperref language specific descriptions or code.

Agreed.
What I want to know is, where to draw the line between
* definitions cared for by "hyperref" and 
* definitions cared for by "greek-fontenc".

Currently, most definitions in "puenc-greekbasic.def" are also in "puenc-greek.def" 
from "greek-fontenc".

Will "hyperref" ultimatively:
a) drop support for Greek LICRs (i.e. deprecate "puenc-greekbasic.def" and remove after a while),
b) keep "puenc-greekbasic.def" as-is "indefinitely",
b) keep just backwards-compatibility definitions in "punec-greekbasic.def" 
    (i.e. the ones that are not also defined in "greek-fontenc" ),
c) support common LICRs for modern "monotonic" Greek (the Greek and Coptic Unicode block)
    and leave the "polytonic" Greek for "greek-fontenc".

I would  remove duplicate definitions  "greek-fontenc" (loading them from "puenc-greekbasic.def" instead) unless there are plans to drop them from "hyperref".

**Comment by gmilde** [comment]
> I meant the ' on its own ... 

I did not catch that from

> Well ` \"'\textiota` (`\'"\textiota`, both seems to work) obviously relies on a ligature ...

**Comment by josephwright** [comment]
I suspect I'll sort all of this from `l3text` perhaps this week :)

**Comment by u-fischer** [comment]
> Will "hyperref" ultimatively:

Well what ultimatively will happen is rather unclear.  

Currently I think hyperref can not stop to load puenc-greekbasic.def.  But it should be possible to move it to greek-fontenc so that the definitions are in one place.

**Comment by josephwright** [comment]
I'm working on some ideas: let me fix the most urgent stuff and I'll then make suggestions  :)

**Comment by gmilde** [comment]
All definitions in `puenc-greekbasic.def` except the misleading composite definition `\'\textIotadieresis` for the small ΐ are now in [puenc-greek.def](http://mirrors.ctan.org/language/greek/greek-fontenc/puenc-greek.def) from the `greek-fontenc` bundle.
This file is loaded by babel-greek (and also by textalpha.sty) if PU is defined.

Hyperref may opt to load this file instead of the more limited `puenc-greekbasic.def` to cover cases of Greek LICRs from alternative packages,
e.g., "ucs" (`\usepackage[utf8x]{inputenc}`) or  "textgreek".

**Comment by u-fischer** [comment]
as the greek puenc has now moved to babel-greek I will close this.
