### ISSUE TITLE
Issue with CheckBoxes not being independent

### ISSUE THREAD

**Issue by stanford-scs** [latex3/hyperref#272]
If I attempt to create a document with simple, independent checkboxes, like this:

```
\documentclass[12pt,letter]{article}
\usepackage{hyperref}

\begin{document}

\begin{Form}

Check this box: \CheckBox[name=one]{}

And check this box: \CheckBox[name=two]{}

\end{Form}

\end{document}
```

This works with some PDF readers, but with evince, I can only check one box at a time.  However, evince works properly with any PDF forms that weren't created by hyperref, which suggests something may be weird in how the name is getting encoded.  It essentially behaves as if all checkboxes had the same name.

**Comment by u-fischer** [comment]
Did you try what I suggested in the comment of your question at tex.sx=?

~~~~
\DocumentMetadata{} 
\documentclass{article} 
\usepackage{l3pdffield-testphase} 
\begin{document} 
\ExplSyntaxOn    
\pdffield_checkbox:n{name=A}\quad \pdffield_checkbox:n{name=B} \ExplSyntaxOff  
\end{document}
~~~~

**Comment by stanford-scs** [comment]
That doesn't compile for me.  I'm using pdflatex from texlive 2022 with arch linux, and it runs into multiple errors with your document, even though it does come with `l3pdffield-testphase.sty`.

**Comment by u-fischer** [comment]
You can compile on texlive.net and then download the pdf to check: https://texlive.net/run

**Comment by stanford-scs** [comment]
Thanks.  Evince doesn't like that form either.  It doesn't let me check either of the checkboxes.  Weird that evince likes other PDF forms, though.  I guess at this point it's not clear whether the problem is evince or pdflatex...

**Comment by u-fischer** [comment]
Well looking through the issues here https://gitlab.gnome.org/GNOME/evince it looks as if evince has a number of problems with checkboxes. 

The checkboxes from hyperref do have problems, but without a clear bug report that something is missing in the l3pdffield code I will assume that the problem is with evince.

**Comment by stanford-scs** [comment]
It seems that hyperref fails to include the Off option for its checkboxes.  For example, if I look at a working pdf file not generated by latex with `pdftk x.pdf dump_data_fields`, I'll see things like this:

```FieldType: Button
FieldName: CheckBox5
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
```

When I do something similar with hyperref, the `FieldStateOption: Off` is missing.

**Comment by u-fischer** [comment]
> It seems that hyperref fails to include the Off option for its checkboxes.

Yes, the checkbox code of hyperref is faulty (see e.g. also #153), but it wouldn't be trivial to correct that as the code is in various driver files and the task is at best long term. That's why I suggested to use the l3pdffield code.
