### ISSUE TITLE
Typo in the manual?

### ISSUE THREAD

**Issue by dr-scsi** [latex3/hyperref#273]
Hi,

looking at the manual, I think this line:
https://github.com/latex3/hyperref/blob/d90a5d874d2ec1536aca07a3be938faef1f23cb8/doc/hyperref-doc.tex#L1649

should read:
```
\section{\texorpdfstring{\textcolor{red}{Red}}{Red} Mars}
```

**Comment by u-fischer** [comment]
well if you try it, you can see that both works:

~~~~
\documentclass{article}
\usepackage{hyperref,color}
\begin{document}

\section{\texorpdfstring{\textcolor{red}}{}{Red} Mars}

\section{\texorpdfstring{\textcolor{red}{Red}}{Red} Mars}


\end{document}
~~~

**Comment by dr-scsi** [comment]
Thanks for your quick response.  This line
https://github.com/latex3/hyperref/blob/d90a5d874d2ec1536aca07a3be938faef1f23cb8/doc/hyperref-doc.tex#L1638
wasn't a direct hint to me (at least) for the other notation.  Am I missing something?

**Comment by davidcarlisle** [comment]
@dr-scsi  in one case you get `\textcolor{red}` in the other you get nothing, in either case followed by `{Red} Mars`  so the color is applied  or not depending on the mode, you do not need to duplicate the string.

**Comment by dr-scsi** [comment]
@davidcarlisle - Thanks, now I see what's happening.  I'm closing this report.
