### ISSUE TITLE
new line in \href first token

### ISSUE THREAD

**Issue by linasstonys** [latex3/hyperref#277]
If there is a new line after a command in first token it is converted to space. I would expect that it would be eaten. 
For example:
```
\documentclass{article}
\usepackage{hyperref}
\def\doibase{http://dx.doi.org/}
\begin{document}
\href {\doibase 
  10.1103/PhysRevLett.108.151804}{10.1103/PhysRevLett.108.151804}
\end{document}
```
link will be `http://dx.doi.org/ 10.1103/PhysRevLett.108.151804`
Problem is that bibtex automatically create such input.
```
\bibitem [{\citenamefont {Ahn}\ \emph {et~al.}(2019)\citenamefont {Ahn} \emph  
  {et~al.}}]{KOTO:2018dsc}%  
  \BibitemOpen  
  \bibfield  {author} {\bibinfo {author} {\bibfnamefont {J.~K.}\ \bibnamefont  
  {Ahn}} \emph {et~al.} (\bibinfo {collaboration} {KOTO}),\ }\href {\doibase  
  10.1103/PhysRevLett.122.021802} {\bibfield  {journal} {\bibinfo  {journal}  
  {Phys. Rev. Lett.}\ }\textbf {\bibinfo {volume} {122}},\ \bibinfo {pages}  
  {021802} (\bibinfo {year} {2019})}\BibitemShut {NoStop}%  
```
Could \href suppress newline characters in first token?

**Comment by u-fischer** [comment]
yes that is known, see e.g. https://tex.stackexchange.com/questions/565133/prevent-hyperref-href-from-inserting-spaces-into-target-urls-containing-macros/565159#565159.

It is a concious decision of hyperref. By explicitly defining the endline char as a space it allows to input long urls with spaces like this:

~~~~
\href{https://url
         with 
        spaces}
~~~~

The drawback is that you have to suppress the space with a percent char always, even if there is a command. 

You could try the following:

~~~~
\documentclass{article}
\usepackage{hyperref}
\ExplSyntaxOn
\def\doibase{http://dx.doi.org/\linux_eatdoispace:n}

\cs_new:Npn\linux_eatdoispace:n#1{\exp_last_unbraced:Ne\token_if_eq_charcode:NNF{\char_generate:nn{13}{10}}#1{#1}}
\ExplSyntaxOff
\begin{document}
\href {\doibase 10.1103}{10.1103/PhysRevLett.108.151804} 

\href {\doibase 
  10.1103/PhysRevLett.108.151804}{10.1103/PhysRevLett.108.151804}
\end{document}
~~~~

**Comment by Rimole** [comment]
"Problem is that bibtex automatically create such input."
Me thinks, **bibtex** is the thing which should be fixed: After \doibase issue % and start a new line.
Bug reporting to bibtex:
https://tug.org/mailman/listinfo/biblio
