### ISSUE TITLE
v7.00x 2023-04-22 broke book class

### ISSUE THREAD

**Issue by stiglitzkleiber** [latex3/hyperref#278]
issue: when compiling (Lua, own class based on scrbook) errors are thrown about  \def \else \fi and having an extra line; no hypersetup accepted by the system

remedy: v7.00x 2023-04-22 replaced with 2022-02-21 v7.00n  and all works as expected

please: check v7.00x 2023-04-22 with lualatex and book.cls

**Comment by u-fischer** [comment]
Please provide a small but complete example that demonstrates the error. hyperref works fine for me with scrbook and book.

**Comment by stiglitzkleiber** [comment]
This is the MWE; all compilations done using TexStudio 4.5.2
----------------------------
\documentclass[
		%nswissgerman %
		   english   %% 
		]{scrbook}
\usepackage{hyperref}
%
\begin{document}   
 \subsection*{A minimal working example to test hyperref.sty}
TexLive for Mac updated 01.05.2023 using TexLive Utility (old installations deleted).
% 
 Try using the url command: ~  \url{https://www.namsu.de/Extra/pakete/Hyperref.html}
 
Try using the href command: ~  \href{https://tex.stackexchange.com/questions/tagged/hyperref}{Query for "hyperref" in Stackexchange}

\end{document}   %}

———————————————

These are the error messages:

# ——— BEGIN error messages  ——— 
** Compiled with LuaLatex **
7: Extra \else.
7: Extra \fi.
7: File `.def' not found.

** Compiled with PdfLatex  **
7: Extra \else.
7: Extra \fi.
7: File `.def' not found.

** Compiled with XeLatex  **
Process started: lualatex -synctex=1 -draftmode -no-pdf  --shell-escape  "mwe-hyperref2023".tex

/Library/TeX/texbin/lualatex: unrecognized option '-no-pdf'
This is LuaHBTeX, Version 1.16.0 (TeX Live 2023) 
 system commands enabled.
(./mwe-hyperref2023.tex

LaTeX2e <2022-11-01> patch level 1

tput: No value for $TERM and no -T specified
 L3 programming layer <2023-04-20>

(/usr/local/texlive/2023/texmf-dist/tex/latex/ko
ma-script/scrbook.cls
Document Class: scrbook 2023/04/24 v3.40 KOMA-Script document class (book)

(/usr/local/texlive/2023/texmf-dist/tex/latex/k
oma-script/scrkbase.sty

(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-scri
pt/scrbase.sty

(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrlfile.sty

(/usr/local/texlive/2023/texmf-dist/te
x/latex/koma-script/scrlfile-hook.sty

(/usr/local/texlive/2023/texmf-dist/tex/lat
ex/koma-script/scrlogo.sty))
)

(/usr/local/texlive/2023/texmf-dist/tex/latex
/graphics/keyval.sty)
)
)

(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-scr
ipt/tocbasic.sty
)

(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrsi
ze11pt.clo
)

(/usr/local/texlive/2023/texmf-dist/tex/late
x/koma-script/typearea.sty
)
)

(/usr/local/texlive/2023/texmf-dist/tex/latex/hyper
ref/hyperref.sty

(/usr/local/texlive/2023/texmf-dist/tex/generic/ltxcmds/l
txcmds.sty)

(/Users/elster/Library/texmf/tex/latex/texmf-local/iftex/iftex.sty)

(/usr/local/texlive/2023/texmf-dist/tex/gene
ric/pdftexcmds/pdftexcmds.sty

(/usr/local/texlive/2023/texmf-dist/te
x/generic/infwarerr/infwarerr.sty)
)

(/usr/local/texlive/2023/texmf-dist/tex/late
x/kvsetkeys/kvsetkeys.sty)

(/usr/local/texlive/2023/texmf-dist/tex/generic/kvdefinekeys/kvde
finekeys.sty)

(/usr/local/texlive/2023/texmf-dist/tex/generic
/pdfescape/pdfescape.sty
)

(/usr/local/texlive/2023/texmf-dist/tex/late
x/hycolor/hycolor.sty)

(/usr/local/texlive/2023/texmf-dist/te
x/latex/letltxmacro/letltxmacro.sty)

(/usr/local/texlive/2023/texmf-dist/tex/latex/auxhook/
auxhook.sty)

(/usr/local/texlive/2023/texmf-dist/tex/latex/hype
rref/nameref.sty

(/usr/local/texlive/2023/texmf-dist/tex/latex/
refcount/refcount.sty
)

(/usr/local/texlive/2023/texmf-dist/tex/gener
ic/gettitlestring/gettitlestring.s
ty
 (/usr/local/texlive/2023/texmf-dist/tex/late
x/kvoptions/kvoptions.sty
)
)
)

(/usr/local/texlive/2023/texmf-dist/tex/latex/et
oolbox/etoolbox.sty
)

(/usr/local/texlive/2023/texmf-dist/tex/latex/hyperref/pd1e
nc.def)

(/usr/local/texlive/2023/texmf-dist/tex/generic/
intcalc/intcalc.sty)

(/usr/local/texlive/2023/texmf-dist/tex/latex/hyperref/puenc.def
)

(/usr/local/texlive/2023/texmf-dist/tex/late
x/url/url.sty)

(/usr/local/texlive/2023/texmf-dist/tex/generic/bitset
/bitset.sty

(/usr/local/texlive/2023/texmf-dist/tex/gene
ric/bigintcalc/bigintcalc.sty
))

(/usr/local/texlive/2023/texmf-dist/tex/latex/base/atbegshi-ltx.sty
)
)
! Extra \else.
\Hy@AtEndOfPackageHook ...color}\fi \fi \fi \else 
                                                  \def \HyOpt@DriverType { (...

l.7 
  
? 

#  ———— END of error messages ---------------

Same behaviour with nswissgerman (instead of english)

**Comment by muzimuzhi** [comment]
@stiglitzkleiber  I can't reproduce the error. Can you attach a full log file? Also it seems `iftex.sty` is loaded from `TEXMFHOME`, which may or may not be relevant to current issue.
```
(/Users/elster/Library/texmf/tex/latex/texmf-local/iftex/iftex.sty)
```

**Comment by u-fischer** [comment]
As @muzimuzhi  wrote: your problem is probably the local iftex.sty. Remove it.

**Comment by stiglitzkleiber** [comment]
great, this did the job! (moved even more obsolete materials to the trash bin)
thanks a lot for your help!
