### ISSUE TITLE
wish: set Language metadata-field in the PDF automatically if the main language is explicitly set in the LaTeX document and pdflang is not supplied

### ISSUE THREAD

**Issue by ghost** [latex3/hyperref#280]
After about 20 years of semi-ignorant LaTeXing, I discovered the document-language meta-field in the PDF Catalog and the option pdflang of hyperref, which leads me to the following wish.

Some LaTeX documents set the main language explicitly. Examples:

1.
```
\documentclass[ngerman]{article}
\usepackage{babel}
\usepackage{hyperref}
…
```

2.
```
\documentclass{article}
\usepackage[ngerman]{babel}
\usepackage{hyperref}
…
```

3.
```
\documentclass[french,USenglish,ngerman,deutsch]{svmono}
\usepackage[french,USenglish,main=ngerman]{babel}
\usepackage{hyperref}
…
```

We ask that in such clear cases (namely, if the main language of the LaTeX document is explicitly set AND the `pdflang=…` option of hyperref is missing), the `/Lang` meta-data field of the PDF Catalog be automatically set according to the main language of the LaTeX document. In the examples above, the value of this field would be `de` (as far as I understand the PDF specification). As of now, the documentation of hyperref says that the default value is _relax_, which means that the `/Lang` field simply does not appear in the metadata. There's no need to keep it this way if the language is that clear.

The final word on whether the task of setting `/Lang` should lie with babel or hyperref (if we were to choose between these two options only; cf. https://github.com/latex3/babel/issues/244#issuecomment-1548717497) is, of course, with the developers. My take on this is that though technically the pdflang option belongs to hyperref at this moment, the document language field in the PDF Catalog has nothing to do with the _hyper_ part of hypertext and thus probably better be _**logically**_ done by (the _localization_ and internationalization package) babel.

Crosspost: http://github.com/latex3/babel/issues/244 .

Gratefully,

AlMa

**Comment by u-fischer** [comment]
closing here. If `\DocumentMetada`  is used it tries to detect the main language, but without pdfmanagement we can't do that.
