### ISSUE TITLE
\MakeUppercase in section text style definition breaks links to said section

### ISSUE THREAD

**Issue by briha** [latex3/hyperref#281]
The [AAS conference paper template](http://www.univelt.com/FAQ.html#SUBMISSION) (which is distinct from AASTex, used for AAS journals) uses `\MakeUppercase` in their section definition. As a result, the anchor of that section is broken, and any link just points to the end of the document (including the pdf bookmarks). Links to subsection and below work as expected, for those are not made uppercase.

For reference, here's the `\section` definition used in the AAS conference paper template:
```latex
\newcommand\section{\@startsection {section}{1}{\z@}%
                                   {-1.5ex \@plus -1ex \@minus -.2ex}%
                                   {0.5ex \@plus.2ex}%
                                   {\normalsize\bfseries\MakeUppercase}}
```

**Comment by u-fischer** [comment]
It would be really better if you made an effort and showed a small and complete example. 

Try with `\makeatletter \AddToNoCaseChangeList{\Hy@@SectionAnchor} \makeatother`.

**Comment by briha** [comment]
Apologies, I assumed the publicly available class would be enough. Here's a MWE for the record, though the solution you proposed does work. Is that expected non-working behaviour, i.e., is the template doing something wrong?

`MWE.cls`
```latex
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{MWE}[]
\RequirePackage{fancyhdr}


\newcommand\@ptsize{1}
\input{size1\@ptsize.clo}
\setlength\lineskip{1\p@}
\setlength\normallineskip{1\p@}
\renewcommand\baselinestretch{}
\setlength{\textheight}{8.75in}
\setlength{\textwidth}{6in}


\setcounter{secnumdepth}{0}

\newcommand\section{\@startsection {section}{1}{\z@}%
                                   {-1.5ex \@plus -1ex \@minus -.2ex}%
                                   {0.5ex \@plus.2ex}%
                                   {\normalsize\bfseries\MakeUppercase}}

\newcommand\subsection{\@startsection{subsection}{2}{\z@}%
                                     {-1.25ex\@plus -1ex \@minus -.2ex}%
                                     {0.5ex \@plus .2ex}%
                                     {\bfseries}}

\setcounter{tocdepth}{3}
\pagestyle{fancy}
\pagenumbering{arabic}
```

`MWE.tex`
```latex
\documentclass[letterpaper,preprint,paper,11pt]{MWE}
\usepackage{hyperref}

\usepackage{lipsum}
%\makeatletter \AddToNoCaseChangeList{\Hy@@SectionAnchor} \makeatother
\begin{document}


\section{Section 1}
\lipsum[3-6]
\section{Section 2}
\subsection{Section 2.1}
\lipsum[8]
\section{Section 3}
\subsection{Section 3.1}
\lipsum[9-14]
\section{Section 4}
\lipsum[15-20]



\end{document}
```

The bookmarks to the subsection do work, while the section ones point to the end of the document.

**Comment by u-fischer** [comment]
> Is that expected non-working behaviour, i.e., is the template doing something wrong?

No really. The section is unnumbered, so there is no anchor for the links from the toc from the counter and hyperref sneaks it in at the begin of the text. That isn't the best place and additionally the hyperref code does it in a way so that is not easy to protect the code against \MakeUppercase. In the new code for the tagging project this is done differently and there is no problem.  I will add the `\AddToNoCaseChangeList{\Hy@@SectionAnchor}` to the next hyperref version.

**Comment by briha** [comment]
Thank you for the prompt fix! Should I close this issue, or wait for when the fix is actually implemented?
