### ISSUE TITLE
Mojibakes and question symbols for non-latin symbols

### ISSUE THREAD

**Issue by sindzicat** [latex3/hyperref#286]
Hello!

Lets say we have the following code:

```tex
\documentclass{article}

\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[russian]{babel}

\usepackage[colorlinks=true,urlcolor=blue, unicode=true]{hyperref}

\begin{document}
    
    \href{https://ru.wikipedia.org/wiki/Праща}{праща}
    
    \nolinkurl{https://ru.wikipedia.org/wiki/Праща}

\end{document}
```

After compiling via PDFLatex I see the following:

![image](https://github.com/latex3/hyperref/assets/33900895/a32b4b75-6ebc-4e3f-b060-6b6ebcbab5e1)

The end of `\nolinkurl` output contains mojibakes.

When I hover cursor over blue hyperlink, I see correct text in popup, but when I click this link, uncorrect url `https://ru.wikipedia.org/wiki/?????` is opened in browser.

Please help me to fix this for PdfLatex. I tried to goole this problem, but didn't find anything.

**Comment by u-fischer** [comment]
You need to percent encode the url in the `\href`. And with pdflatex you can't use non-ascii chars in `\nolinkurl`, that is not supported. 

See also https://tex.stackexchange.com/a/672447/2388 and https://tex.stackexchange.com/a/670811/2388

> Please help me to fix this for PdfLatex

this here is not a support forum but a bug tracker. Please ask such question e.g. on tex.stackexchange.

**Comment by sindzicat** [comment]
@u-fischer, thanks for answer. I was sure I found a bug and that some workaround may exists.

Is this possible to fix this in the future?
