### ISSUE TITLE
minimal report with \maketitle and hyperref causes same identifier warning

### ISSUE THREAD

**Issue by kberry** [latex3/hyperref#288]
Subject says it all (not that this is news). With input file tryreport.tex:
```
\documentclass{report}
\title{Some title}
\author{Some author}
\usepackage{hyperref}
\begin{document}
\maketitle

\chapter{First chapter}

That's all.
\end{document}
```

and running with:
```
pdflatex tryreport.tex
```

this message is given:
```
pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has 
been already used, duplicate ignored                                 
```

It does not seem right that a basic {report} file taking all the defaults generates a warning.

Maybe somehow pageanchor=false should be set by default for  title pages, per Ulrike's answer at https://tex.stackexchange.com/questions/18924. Or something?

**Comment by u-fischer** [comment]
I have an open issue about that: https://github.com/latex3/latex2e/issues/647

**Comment by u-fischer** [comment]
closing here as this actually a latex issue
