### ISSUE TITLE
tooltip hover text 

### ISSUE THREAD

**Issue by RobinHankin** [latex3/hyperref#295]
Hi there, Love the package! 

I am using it to write documents discussing pure mathematics, in which every symbol in every equation is clickable, and takes you to a page of help about it.

I am thinking about the tooltip text that appears when I  hover the mouse over a clickable link.  Currently what I see when I hover over a symbol is something like "Go to page 49" (and clicking it takes me to the right place!).  But I would like to see something more informative such as a defining equation or English definition.

How can I customise my tooltips?

**Comment by u-fischer** [comment]
This here is an issue tracker not a general support forum. Please ask such questions e.g. on tex.stackexchange or similar sites
and then provide more details. Tooltips depend on your code (are you using pdfcomment?) and also on the viewer you use.
