### ISSUE TITLE
problems with update

### ISSUE THREAD

**Issue by ffr314** [latex3/hyperref#301]
since i updated all my packages i get an error with the hyperref package.

this tex-file caused the same error message and i attached the log file

\documentclass{report}

\usepackage{hyperref}

\begin{document}

test

\end{document}

[test.log](https://github.com/latex3/hyperref/files/12700481/test.log)

**Comment by u-fischer** [comment]
your iftex package is outdated.

~~~~
(C:\Program Files\MiKTeX 2.9\tex/generic/iftex\iftex.sty
Package: iftex 2020/03/06 v1.0d TeX engine tests
~~~~

It should be

~~~~
Package: iftex 2022/02/03 v1.0f TeX engine tests
~~~~

**Comment by ffr314** [comment]
Thanks a lot!
