### ISSUE TITLE
nameref does not check for \NR@nopatch@amsthm or \NR@nopatch@theorem

### ISSUE THREAD

**Issue by mbertucci47** [latex3/hyperref#302]
On page 3 of the documentation, it says one can disable nameref's patch of `\@opargbegintheorem` and `\@begintheorem` by defining `\NR@nopatch@amsthm` and `\NR@nopatch@theorem`, respectively. However, I don't see any reference to this in the code (no `\@ifundefined{NR@nopatch@<patch>}`), and the following example shows these commands definitions don't change when the "nopatch" commands are defined:
```tex
\documentclass{article}

\usepackage{amsthm}

\makeatletter

% makes no difference if these are commented
\def\NR@nopatch@amsthm{}
\def\NR@nopatch@theorem{}

\usepackage{nameref}

\begin{document}

\ShowCommand{\@opargbegintheorem}
\ShowCommand{\@begintheorem}

\end{document}
```
Apologies if I missed or am misunderstanding something.

**Comment by u-fischer** [comment]
Hm, yes. Somehow they got forgotten. I added them now and the next update will fix this.

**Comment by mbertucci47** [comment]
Thanks! I think this can be closed now.
