### ISSUE TITLE
Last version of `hyperref` breaks `etoc`

### ISSUE THREAD

**Issue by dbitouze** [latex3/hyperref#305]
Consider the following MWE:

```latex
\documentclass{article}
\usepackage{etoc}
\usepackage{blindtext}
\usepackage{hyperref}

\begin{document}
\tableofcontents
\Blinddocument
\end{document}
```
With `hyperref`:

- `v7.01b`, the table of contents is okay,
- `v7.01c`, the table of contents is empty.

**Comment by u-fischer** [comment]
That is something that etoc should handle.  If you look into the log you can find a message that looks like a hyperref message but is from etoc:

~~~~
Package hyperref Warning: old toc file detected; run LaTeX again (cheers from `etoc').
~~~~

This is from this code which relies on assumptions about hyperref internals which are no longer valid

~~~~
\def\Etoc@openouttoc{%
  \ifEtoc@hyperref
   \ifx\hyper@last\@undefined
    \IfFileExists{\jobname .toc}
      {\Hy@WarningNoLine
         {old toc file detected; run LaTeX again (cheers from `etoc')}%
       \global\Etoc@toctoks={}%
      }
 .....
~~~~

Until now hyperref wrote code into the auxfile (`\global\let\hyper@last\relax`) to detect if a previous compilation used hyperref too to avoid errors steeming from the different `\contentsline` definitions. But this code is no longer needed and has been removed as `\contentsline`  has been synchronized (around two years ago) with latex and use the same numbers of arguments.

(Something similar applies also to `\newlabel`, the safety code from hyperref is no longer needed either).

**Comment by jfbu** [comment]
Thanks @dbitouze and @u-fischer.  I will fix this, now I observed something weird in the log file, it says:

```
...
) (/usr/local/texlive/2023/texmf-dist/tex/latex/hyperref/hyperref.sty
Package: hyperref 2023-07-08 v7.01b Hypertext links for LaTeX
...
```

but if I visit the file `/usr/local/texlive/2023/texmf-dist/tex/latex/hyperref/hyperref.sty` I see
```
...
%% File: hyperref.dtx
\NeedsTeXFormat{LaTeX2e}[2020/10/01]
\ProvidesPackage{hyperref}
  [2023-10-21 v7.01c %
  Hypertext links for LaTeX]
```

so indeed I do have `v7.01c` (my installation was updated about 36hours ago; and I could confirm the problem discovered by @dbitouze ) but I find no `v7.01c` anywhere in the log file...

**Comment by jfbu** [comment]
@dbitouze @u-fischer Thanks both I will fix this.

I made an earlier post on some problem with version strings in log file but this was based on me not having had yet a proper meal and having made a silly confusion in my Emacs dired buffer between files. Sorry. I thus hard-deleted it from here.

**Comment by jfbu** [comment]
I have uploaded to CTAN `etoc v1.2c 2023/10/28` which fixes this.
