### ISSUE TITLE
Typo in command name in hyperref.dtx

### ISSUE THREAD

**Issue by rriegs** [latex3/hyperref#307]
The command `\cyreref` on line 22325 of hyperref.dtx should instead be `\cyrerev`:

https://github.com/latex3/hyperref/blob/7a25bf387853f6c92517603606c9d66f18efd7fa/hyperref.dtx#L22322-L22325

This is in reference to the definition on line 21988 (and would be consistent with the corresponding command for the capital character):

https://github.com/latex3/hyperref/blob/7a25bf387853f6c92517603606c9d66f18efd7fa/hyperref.dtx#L21987-L21988

I'm not sure if this file is the original source of this error, but by now it has propagated to other repositories, in particular [ctex-kit](https://github.com/CTeX-org/ctex-kit)'s xeCJK.dtx.

**Comment by u-fischer** [comment]
resolved in version 7.01f
