### ISSUE TITLE
Self-referential declaration in hyperref.dtx

### ISSUE THREAD

**Issue by rriegs** [latex3/hyperref#308]
The command `\textddagger` declared on line 20088 is self-referential:

https://github.com/latex3/hyperref/blob/7a25bf387853f6c92517603606c9d66f18efd7fa/hyperref.dtx#L20086-L20088

This was likely intended to reference the above line, `\textdaggerdbl`, however, I also note that the PU equivalents are just `\ddagger` and `\ddag`:

https://github.com/latex3/hyperref/blob/7a25bf387853f6c92517603606c9d66f18efd7fa/hyperref.dtx#L22854-L22857

These are further aliased in `\psdaliasnames` via `\let\ddagger\textdaggerdbl`, and so line 20088 may not in fact be necessary at all.

**Comment by u-fischer** [comment]
resolved in version 7.01f
