### ISSUE TITLE
Typo (and incorrect command) in hyperref.dtx

### ISSUE THREAD

**Issue by rriegs** [latex3/hyperref#310]
The command `\textDiamandSolid` declared on line 24595 and its alias `\DiamandSolid` declared on line 26137 are misspelled and are also the incorrect command for the referenced Unicode symbol:

https://github.com/latex3/hyperref/blob/7a25bf387853f6c92517603606c9d66f18efd7fa/hyperref.dtx#L24594-L24595

First off, these should be spelled "diamond" instead of "diamand" everywhere it occurs, and second, while there is a bbding command `\DiamondSolid`, it yields "◆" (U+25C6) BLACK DIAMOND instead of "❖" (U+2756) BLACK DIAMOND MINUS WHITE X. The later symbol is instead referenced by `\OrnamentDiamondSolid` (as suggested by the comment in line 24594, barring the spelling error).

The best solution is likely to introduce separate declarations for both symbols.

Similar to #307, this error has propagated to other repositories including [ctex-kit](https://github.com/CTeX-org/ctex-kit)'s xeCJK.dtx.

**Comment by u-fischer** [comment]
hm, yes a combination of diamond and the german Diamant. I think I will dare to change that.

**Comment by u-fischer** [comment]
resolved in version 7.01f
