### ISSUE TITLE
Incorrect declaration `\CYRSDSC{\CYRS}` in hyperref.dtx

### ISSUE THREAD

**Issue by rriegs** [latex3/hyperref#314]
The composite command `\CYRSDSC{\CYRS}` declared on line 22184 of hyperref.dtx should instead be `\k{\CYRS}` (i.e., ogonek applied to Cyrillic capital letter Es):

https://github.com/latex3/hyperref/blob/7a25bf387853f6c92517603606c9d66f18efd7fa/hyperref.dtx#L22182-L22187

This change would be consistent with the declaration for the lowercase version of the letter on line 22187 and would eliminate a redundancy (and possible conflict) in that `\CYRSDSC` by itself as declared on line 22183 is intended to be a synonym for `\k{\CYRS}`.

Similar to #307 and #310, this error has propagated to other repositories including [ctex-kit](https://github.com/CTeX-org/ctex-kit)'s xeCJK.dtx.

**Comment by muzimuzhi** [comment]
> Similar to #307 and #310, this error has propagated to other repositories including [ctex-kit](https://github.com/CTeX-org/ctex-kit)'s xeCJK.dtx.

@rriegs Thanks for your report again! This has been fixed in `ctex-kit` dev, see https://github.com/CTeX-org/ctex-kit/commit/81f7050b2b6dabdbe9dd2c472c3e8e446d17a322.

**Comment by u-fischer** [comment]
this has been fixed in the newest hyperref.  7.01g
