### ISSUE TITLE
LaTeX socket Error: Sockets can only be declared at top-level!

### ISSUE THREAD

**Issue by yihui** [latex3/hyperref#315]
Hi, it seems the commit 908b150980ad82fca0df5e80ce5126dd164ab9ae introduced this error when `hyperref` is used together with `setspace`:

```
! LaTeX socket Error: Sockets can only be declared at top-level!

For immediate help type H <return>.
 ...                                              
                                                  
l.2080  {\providecommand\UseSocket[2]{#2}}
                                          

It is not allowed to declare sockets inside a group. Move the declaration to
the top-level.
```

Minimal reproducible example:

```tex
\documentclass{article}
\usepackage{setspace}
\spacing{1}
\usepackage{hyperref}

\begin{document}
Test.
\end{document}
```

This problem has affected a number of users:

- https://stackoverflow.com/q/77465287/559676
- https://github.com/rstudio/tinytex/issues/430
- https://community.rstudio.com/t/177023

We will truly appreciate it if it could be fixed, although I don't understand whether this is a problem of `hyperref` or `setspace` (I'll be happy to report to [the latter repo](https://github.com/latex-package-repositories/setspace) if the problem belongs there).

Thanks a lot!

**Comment by u-fischer** [comment]
Sorry but this an user error. 

`spacing` is an enviroment, not a command. It is defined as 

~~~~
\newenvironment{spacing}[1]{%
  \par
  \begingroup             % moved from \endspacing by PGBR 29-1-91
    \setstretch {#1}%
}{%
  \restore@spacing
}
~~~~

This means that by using simply `\spacing{1}` you are opening a group that is never closed. Without hyperref you would get a message:

~~~~
### semi simple group (level 1) entered at line 180 (\begingroup)
### bottom level 
~~~~

You probably want to use \singlespacing or `\setstretch {1}`.

**Comment by yihui** [comment]
@u-fischer Thank you very much!
