### ISSUE TITLE
siunitx \qty inside caption & xr-hyper problem

### ISSUE THREAD

**Issue by rafaelpap** [latex3/hyperref#327]
Dear Sir,
I have a document which uses siunitx and xr-hyper. If I include a \qty command inside a caption in the "auxiliary" document I obtain the following error:

! Undefined control sequence.
...of a water molecule \qty {1}{\meter
}
Using \num inside the caption works ok.
I attach 4 files. I compile them using
latexmk -pdf article1.tex
latexmk -pdf suppinfo1.tex
latexmk -pdf article1.tex

latexmk -pdf article2.tex
latexmk -pdf suppinfo2.tex
latexmk -pdf article2.tex

Using xr instead of xr-hyper seems to work.

[bug.zip](https://github.com/josephwright/siunitx/files/13990274/bug.zip)

Maybe I am doing something wrong?
Thanks for the attention,
Rafael RP

**Comment by davidcarlisle** [comment]
thanks for moving this from siunitx, it's a bug in xr-hyper we are looking at it.

**Comment by u-fischer** [comment]
As a work-around until a fix is on ctan you can add this after `\usepackage{xr-hyper}`:

~~~
\makeatletter
\def\XR@@dURL#1#2#3#4#5\\{%
     \unexpanded{{#1}{#2}{#3}{#4}}{\XR@URL}% 
  }%
\makeatother
~~~

**Comment by rafaelpap** [comment]
Thanks!

**Comment by u-fischer** [comment]
I have uploaded a new version that should fix this
