### ISSUE TITLE
Hyperref URLs in Print

### ISSUE THREAD

**Issue by cris46** [latex3/hyperref#329]
As LaTeX seems to be mostly thought to be printed, it's a shame that then, the URLs set will disappear. One idea to solve this might be, to add a new counter to the hrefs that are URLs and create a new type of list that could work like endnotes. While I have no idea how this could be done, I'd welcome such an addition to this very useful package.

Cris.

**Comment by muzimuzhi** [comment]
> As LaTeX seems to be mostly thought to be printed, it's a shame that then, the URLs set will disappear.

Would you care to elaborate on that disappearing?

**Comment by dbitouze** [comment]
> Would you care to elaborate on that disappearing?

I guess @cris46 means the `⟨URL⟩` of `\href{⟨URL⟩}{⟨text⟩}` hidden in printed versions .

**Comment by mrpiggi** [comment]
I used to define a wrapper macro for more or less setting an additional footnote printing the URL itself.

**Comment by dbitouze** [comment]
> I used to define a wrapper macro for more or less setting an additional footnote printing the URL itself.

It's an option (that I used with my `yathesis` class), but it's more likely to alter the page layout compared to the "normal" PDF version than the @cris46's proposal with notes, not as footnotes, but as endnotes.

**Comment by u-fischer** [comment]
Sorry but hyperref can't know if a PDF is meant for print or not (or both) and also can't know how the author wants to format url's in both cases - as you can see from the comments there are various options. You will have to define a suitable wrapper command that fits your need yourself.
