### ISSUE TITLE
LaTeX sockert Error: Sockets can only be declared at top-level!

### ISSUE THREAD

**Issue by TonyOneZero** [latex3/hyperref#331]
<img width="890" alt="image" src="https://github.com/latex3/hyperref/assets/15279954/4146a1f9-7449-4528-9cd9-a623dcb5f783">
Texlive-Version: latest

**Comment by josephwright** [comment]
E.g. https://github.com/latex3/hyperref/issues/326

**Comment by josephwright** [comment]
Also https://github.com/latex3/hyperref/issues/315 - we will need a full example and `.log`, and it will probably point to an issue with another package or class

**Comment by u-fischer** [comment]
closing as not example has been provided.
