### ISSUE TITLE
Updated to LiveTeX 2024 and hyperref gives errors.

### ISSUE THREAD

**Issue by JST55** [latex3/hyperref#334]
I updated LiveTeX on OPenSUSE 15.5 to 2024 and now hyperref is giving me errors with LaTex and PDFLaTeX.  The file uses amstex and a bunch of other style files.  I removed almost everything from the files and am still getting the same error.  I have attached the latex file with almost everything stripped from it.

If you need anything else, please ask.

Any help will be appreciated.

Jay Treiman

[Vect_Calc_hyp_test.tex.txt](https://github.com/latex3/hyperref/files/14652827/Vect_Calc_hyp_test.tex.txt)

**Comment by u-fischer** [comment]
compiles fine for me. Show your log-file.

**Comment by JST55** [comment]
OK.  Here it is.

[Vect_Calc_hyp_test.log.txt](https://github.com/latex3/hyperref/files/14653173/Vect_Calc_hyp_test.log.txt)

Thank you.

**Comment by u-fischer** [comment]
Your latex format is outdated:

you have `LaTeX2e <2020-10-01> patch level 4`. That should be `LaTeX2e <2023-11-01> patch level 1`

**Comment by JST55** [comment]
Thank you.  All that I need to do now is to figure out where that is in the repository.  Might you have an idea where that is?  Perhaps in the binaries files?

**Comment by u-fischer** [comment]
sorry no. I don't know your system and don't know what you should do to update the formats.  I'm on windows. In any case this is not a hyperref problem, so I'm closing here.
