### ISSUE TITLE
Hyperref not working

### ISSUE THREAD

**Issue by Thorwald11** [latex3/hyperref#337]
I tried to use hyperref for my document but all i get is an error message. I'm currently using Kile as an editor and as soon as I include the hyperref package the nameref.sty file opens. Here is a minimal example which already courses the error messages. 

\documentclass{scrartcl}
\usepackage{hyperref}
\begin{document}
 hello world!
\end{document}

You can also find a file with my test document log-data. As far as I can tell I installed the packages correctly and my system also runs on the newest. I'm really hoping that someone with a similar problem already found a solution for that issue or that some smarter guy can fix it. Thanks for helping.

[test.log](https://github.com/latex3/hyperref/files/14850609/test.log)

**Comment by davidcarlisle** [comment]
You have a texlive 2019 debian tex distribution but somehow have

(/usr/share/texmf/tex/latex/hyperref.sty
Package: hyperref 2024-01-20 v7.01h Hypertext links for LaTeX


it seems unlikely that apt installed that file? Did you add that by hand? if so remove it, you need a 2019 hyperref to work in texlive 2019.

**Comment by Thorwald11** [comment]
Hey thanks for quick response. I did add it by hand, i guess course it didn't worked before (but I can not tell the issue back there for sure).

**Comment by josephwright** [comment]
For ref., the version of `hyperref` in the last updates of TL'19 was `2020/01/14 v7.00d Hypertext links for LaTeX`.

**Comment by Thorwald11** [comment]
Okay so i should use that one instead? If yes how can I get it?

**Comment by davidcarlisle** [comment]
just delete the one you added and use the version that you should have aready in texmf/tex/latex/hyperref/hyperref.sty , never add files by hand to apt managed directories.

**Comment by Thorwald11** [comment]
My editor Kile gave me the chance to add an hyperref package to my document, but i always had trouble with it. I don't know for sure anymore but it was something like "i can't find/ use the hyperref package" (but it's also possible that it only sounded for me like that's the issue). Since I already started to download and install some other packages by hand I also did so with the hyperref package.

**Comment by Thorwald11** [comment]
I also tried to delete the added packages but it seems like that doesn't work. But as far as I can tell it seems to be the same error that happened in the first place.  Somehow now the hyperref.sty file opens. But at least it's the last updates of TL'19 was 2020/01/14 v7.00d Hypertext links for LaTeX. I have the log file added. 
[xray_main.log](https://github.com/latex3/hyperref/files/14851140/xray_main.log)

**Comment by davidcarlisle** [comment]
You are missing `\usepackage{letltxmacro}` to define that macro, but this is the bug tracker for upstream hyperref. There is nothing we can do here to affect the 5 year old system you are using.  The example you posted runs without error on the code in this repository.

**Comment by Thorwald11** [comment]
So it's just my system that's old fashioned and updating it to a newer one could just help. To be honest i wasn't even aware that it might be outdated cause i just installed the editor December 2023. Or is it the linux system I'm using?

**Comment by Thorwald11** [comment]
Okay i just edited \usepackage{letltxmacro} and it works. I wasn't aware that i'm supposed to use that package together with hyperref. Thanks so much for helping me with that issue.

**Comment by davidcarlisle** [comment]
it's the debian tex version but typically you don't need to update, a 2019 tex system will do most use cases but you can not always expect to grab upstream 2024 code and have it work in such a system, and in general not just for tex, you shouldn't add files by hand in to apt managed directories as that just breaks its control over package dependencies as the package manager doesn't know about your changes.  But this is a bug report system not a help forum so nothing more here to say.
