### ISSUE TITLE
Named URLs

### ISSUE THREAD

**Issue by MithicSpirit** [latex3/hyperref#346]
Is there any convenient way to save a URL to some command while properly escaping characters like `#`? Using `\def` and manually escaping these characters works, but I'd rather have something that does the escaping automatically, like the regular hyperref commands. I believe this is internally handled by `\hyper@normalise`, but I couldn't find an easy way to use that directly in a document.

**Comment by u-fischer** [comment]
this here is an issue tracker not a general support forum. Please ask such questions e.g. on tex.stackexchange.com. And do not forget to add a complete example that can be use to test solutions.

**Comment by MithicSpirit** [comment]
Sorry, this was meant as a feature request (for either a direct command to do this, or some interface to `\hyper@normalise`), but I phrased it incorrectly.

**Comment by car222222** [comment]
Closed nevertheless!  With apologies.
