### ISSUE TITLE
`\DocumentMetadata` with `bookmarks=false` gives warning

### ISSUE THREAD

**Issue by mbertucci47** [latex3/hyperref#352]
Not sure if this belongs here or at [latex2e](https://github.com/latex3/latex2e), please feel free to move.

If `\DocumentMetadata` is used with `bookmarks=false`, a warning about hooks is produced:
```
LaTeX hooks Warning: Cannot remove chunk 'hyperref/bookmark' from hook
(hooks)              'begindocument/before' because it does not exist in that
(hooks)              hook.
```
Example file:
```tex
\DocumentMetadata{lang=en-US}
\documentclass{article}
\usepackage[bookmarks=false]{hyperref}
\begin{document}
text
\end{document}
```

**Comment by u-fischer** [comment]
This has been resolve in the pdfmanagement/generic driver.
