### ISSUE TITLE
pdflatex stuck on listing when cleveref is used

### ISSUE THREAD

**Issue by AdrianVollmer** [latex3/hyperref#364]
Greetings to the LaTeX team! Thanks for your tireless work.

I noticed a bug today, hopefully you can help. Thanks in advance!

Consider this MWE:

```latex
\documentclass{article}
\usepackage{listings,hyperref,cleveref}
\begin{document}
\begin{lstlisting}
foo
\end{lstlisting}
\end{document}
```

`pdflatex` is stuck on the listing and must be interrupted with CTRL-C. This is the end of the log.

```
...
(./test.aux) (./test.out) (./test.out)^C
! Interruption.
\lsthk@EveryPar ...entprefix {\cref@currentprefix
                                                  }
l.5 foo

?
! Emergency stop.
\lsthk@EveryPar ...entprefix {\cref@currentprefix
                                                  }
l.5 foo

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on test.log.
```

This must have happened with the last update or the one before that.

**Comment by u-fischer** [comment]
This has been already corrected. Ensure that you have the hyperref version 2024-11-05 v7.01l (it is already both in texlive and miktex).

**Comment by AdrianVollmer** [comment]
I can confirm that fffd2e030c7aff952c0e9f34265fe4a03a8efd46 fixes the problem.

Thanks for your timely reply!
