### ISSUE TITLE
Missing feature: highlight links when coloring cannot be done

### ISSUE THREAD

**Issue by ilyaza** [latex3/hyperref#71]
Essentially, I need the links to be visible in a printed copy of the document — but since colors are not content-free in my document, I cannot use colors for this.  Currently I’m forced to do
```tex
\let\Ohyper@link\hyper@link
\let\Ohyper@linkurl\hyper@linkurl
\def\hyper@link#1#2#3{\Ohyper@link{#1}{#2}{\csname myHighlightLink\endcsname{#3}}}
\def\hyper@linkurl#1#2{\Ohyper@linkurl{\csname myHighlightUrlLink\endcsname{#1}}{#2}}
```
to make it possible to use my specific highlighting of the argument to `\hyperlink` and `\href` correspondingly (`\csname` allows macros to be undefined).  Can something like this be included?

(Currently I put colored dotted underline — this is not semantic in the particular format of my documents.)

**Comment by ilyaza** [comment]
**Upd:** in fact, thinking about this more: apparently, the whole system of highlighting links misses an important point.  One needs to highlight links because *usually* it is not clear that a particular chunk of a document is clickable.  However, in some cases it is completely obvious that something may be a link — provided one knows that what looks like a crossreference IS a live crossreference.

**Conclusion**: it makes sense to allow treating obvious-from-the-context links differently from those which are not clear from the context.  In my case, the point is the difference between links made by `\hyperlink{}{}` and those made by `\ref{}` and `\pageref{}`: the former **need** to be highlighted, and the latters **may** be highlighted (same for references created in the TOC.)

My current solution I try now: `\href` highlighted in blue (dots), `\hyperlink` highlighted in green (dots), the rest highlighted by (unobtrusive) yellow-on-white.  The code (after `\usepackage[normalem]{ulem}`):
```tex
\newcommand\dotulineC[1]{\bgroup 	% Same as \dotuline of ulem, but #1 is inserted after \begingroup
  \UL@setULdepth
  \markoverwith{\begingroup #1
     \advance\ULdepth0.08ex 
     \lower\ULdepth\hbox{\kern.1em .\kern.04em}%
     \endgroup}%
  \ULon}
\newif\ifInsideHyperlink
\newcommand\myHighlightLinkExplicit{\dotulineC\green}
\newcommand\myHighlightLink[1]{\ifInsideHyperlink\else\expandafter\dotulineC\expandafter\yellow\fi}	% ignore the link type
\newcommand\myHighlightUrlLink{\dotulineC\blue}

\let\Ohyperlink\hyperlink
\let\Ohyper@link\hyper@link
\let\Ohyper@linkurl\hyper@linkurl
\def\hyperlink#1#2{\InsideHyperlinktrue\Ohyperlink{#1}{\myHighlightLinkExplicit{#2}}\InsideHyperlinkfalse}
\def\hyper@link#1#2#3{\Ohyper@link{#1}{#2}{\myHighlightLink{#1}{#3}}}
\def\hyper@linkurl#1#2{\Ohyper@linkurl{\csname myHighlightUrlLink\endcsname{#1}}{#2}}
```

Notes: (1) now I pass `#1` of `\hyper@link` to `\myHighlightLink` to allow distinguishing different types of links.  (2) Because of this, `\myHighlightLink` is not protected by `\csname`, so should be defined.

**Comment by u-fischer** [comment]
hyperref has traditionally more or less control over colors, but for other formatting other packages can interfere, e.g. url.

That said with the new PDF management it is possible to use the pdfannot hooks to inject formatting.

~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
  
\documentclass{article}
\usepackage{hyperref}

\begin{document}
\section{hello world}\label{a}
some text 

\AddToHook{pdfannot/link/GoTo/begin}{\sffamily}
\nameref{a}

%\sffamily overwriten by url package:
\AddToHook{pdfannot/link/URI/begin}{\sffamily\itshape}
\url{https://github.com/latex3/hyperref}

\def\UrlFont{\sffamily}
\url{https://github.com/latex3/hyperref}

\end{document} 
~~~~

![image](https://user-images.githubusercontent.com/4047173/109397035-e60ffd80-7934-11eb-997c-da978a8db79f.png)

When using the internal commands it is also possible to use the first argument of \hyper@link to setup a "context":

~~~~
   \RequirePackage{pdfmanagement-testphase}
      \DeclareDocumentMetadata{uncompress}

      \documentclass{article}
      \usepackage{xcolor,hyperref}

      \IfHookExistsTF{hyp/link/gloss}{}
        {\NewHook{hyp/link/gloss}}
      \AddToHook{hyp/link/gloss}{glossary: \color{blue}\bfseries}
      \AddToHook{hyp/link/cite}{cite: \itshape}
      \begin{document}
      \section{section}%just for the destination

      \makeatletter
      \hyper@link{cite}{section.1}{a citation}
      \quad 
      \hyper@link{gloss}{section.1}{a glossary entry}
      \makeatother
      \end{document}
~~~~

Imho this should offer enough configuration points so I'm closing this now.

**Comment by ilyaza** [comment]
This sounds great, thanks!  However, I’m a bit lost in the implementation details you list…

So let me make sure that the following capabilities are allowed:

- The customization you provide allows having the text as an **argument** for the macros (such as `\underline`).
- One can have:

    1. `\href{foo}{Text}`
    2. `\hyperref[foo]{Text}`
    3. `\ref{foo}`
    4. `\pageref{foo}`
    5. `\cite{foo}`

    highlighted in different ways.
