### ISSUE TITLE
hyperref pdfa default?

### ISSUE THREAD

**Issue by kberry** [latex3/hyperref#79]
I wondered if hyperref's pdfa option could/should be on by default. don't know if there are operational/compatibility downsides, but preserving links across gs runs (the side effect i read about recently) would be highly desirable.

just a thought, maybe stupid ...

**Comment by u-fischer** [comment]
I don't think that this would a good idea - it sets to many options. It would be better to add an option that allows to enable the flag independently to the pdfa option.

**Comment by davidcarlisle** [comment]
@u-fischer  yet another option or close with no change?

**Comment by u-fischer** [comment]
@davidcarlisle  No we shouldn't activate it by default. Options for flags will be added later.

**Comment by davidcarlisle** [comment]
Closing for now.
