### ISSUE TITLE
adapt code for pdf version 2.0

### ISSUE THREAD

**Issue by u-fischer** [latex3/hyperref#87]
With luatex it is possible to set the pdf version to 2.0 with 

~~~~
\pdfvariable majorversion 2
\pdfvariable minorversion 0
~~~~

hyperref is not really prepared for this. E.g. this document

~~~~
\pdfvariable majorversion 2
\pdfvariable minorversion 0
\pdfvariable compresslevel=0

\documentclass{article}
\usepackage[ocgcolorlinks]{hyperref}
\begin{document}
blub
\end{document}
~~~~

creates this pdf header:

~~~~
%PDF-2.5
%ÌÕÁÔÅØÐÄÆ
~~~~

**Comment by davidcarlisle** [comment]
hmm it wouldn't be hard to fix that test but more generally this code

```
`\@namedef{Hy@pdfversion@1.2}{2}%
\@namedef{Hy@pdfversion@1.3}{3}%
\@namedef{Hy@pdfversion@1.4}{4}%
\@namedef{Hy@pdfversion@1.5}{5}%
\@namedef{Hy@pdfversion@1.6}{6}%
\@namedef{Hy@pdfversion@1.7}{7}%
\@namedef{Hy@pdfversion@1.8}{8}%
\@namedef{Hy@pdfversion@1.9}{9}%
\def\Hy@pdfversion{5}
```

assumes that a single integer is enough to store the version, so I suppose we need to go though and make it use a macro 1.5 or 2.0 or the two integer major and minor values everywhere and avoid using this existing macro.....

**Comment by u-fischer** [comment]
@davidcarlisle  pdftex imho doesn't have a major version (yet? should we ask Joseph?).  So one has to check by driver. And there are some more places where the code assumes that the minorversion is enough. I added an issue with one example so that I don't forget this topic ;-).

**Comment by davidcarlisle** [comment]
an alternative would be to just let the minor version go beyond 9 so the
algorithm is divide by 10 and add 1,
so
5->1.5
10->2.0

so only a single integer is needed that may be more compatible with any
other packages that might want to check the version number

**Comment by u-fischer** [comment]
Hm. `\pdfvariable minorversion=11`  gives `(pdf backend): illegal minor version 11, using 4 instead`. And we would still have the problem that pdftex can't create pdf 2.0 (at least I think it can't).

**Comment by davidcarlisle** [comment]
yes sorry I meant set hyperefs internal hy@version to be an integer using the combined scheme 

yes would need a change to pdftex  to be able to wrote 2.0, pdftex.web has
```

        if (pdf_minor_version < 0) or (pdf_minor_version > 9) then begin
            print_err("pdfTeX error (illegal pdfminorversion)");
....
        pdf_print("%PDF-1.");
        pdf_print_int_ln(fixed_pdf_minor_version);
```

shame we didn't get that added for tl2019, should be easy to fix to to 2020 though

**Comment by davidcarlisle** [comment]
@u-fischer  @josephwright   should be fixed by commit 2d3a583 but it could probably do with some more testing (I won't push to ctan today now)

**Comment by dbitouze** [comment]
Sorry to interrupt this discussion, but where could we find information about the differences between (current) 1.5 and (future) 2.0 PDF versions from a (pdf|xe|lua)LaTeX user's point of view?

**Comment by davidcarlisle** [comment]
@dbitouze  currently nothing except that the first view bytes of the generated PDF file can now be

   `%PDF-2.0`

as the code maintains major and minor version and doesn't just store the minor version and assume major is always 1.

In texlive 2019 this only actually works in luatex as pdftex web sources similarly hard code `1.` in teh version string, but that is fixed for texlive 2020 with a new `\pdfmajorversion` primitive, which this new hyperref code uses if it is available.

Longer term of course this will lead the way to actually adding pdf 2 features but that is for the future (and once pdf readers can cope with pdf 2)

**Comment by dbitouze** [comment]
@davidcarlisle Thanks for the explanation. Any pointer about the pdf 2 features?

**Comment by davidcarlisle** [comment]
@dbitouze  unfortunately, unlike the PDF 1.x reference manuals, the PDF 2.0 manual isn't free (and I haven't seen it)  The (not over informative) press release around the time PDF 2.0 was published gives a general overview of the changes https://www.iso.org/news/ref2199.html

**Comment by u-fischer** [comment]
pdfversion=2.0 now works with the major drivers.
