### ISSUE TITLE
Checkbox Appearance dictionary breaks some renderers

### ISSUE THREAD

**Issue by wherget** [latex3/hyperref#94]
We're creating some forms using hyperref and Chrome/Chromium as well TWINUI (Microsoft Edge) doesn't render a clicked checkbox as checked (it is unclear whether it actually changes the state of the form element).

I have come to the conclusion that this is due to the Appearance dictionary of the Checkbox not conforming to the PDF spec. (Apologies for the following legalese...) In PDF 1.7 (Section 12.7.4.2.3) it says that "Each state can have a separate appearance, which shall be defined by  an appearance stream in the appearance dictionary[...]". And that (Sec. 12.5.5) "Each appearance stream is a form XObject [...]".

Currently (after the fix for #6), hyperref writes the mandated `/Yes` entry as an empty dictionary. Unfortunately I don't (yet) have enough of a grasp of hyperref's output process to figure out the incantations needed to generate such an XObject stream.

PDF Files that work as expected have a full-blown appearance Dictionary (with both `/Yes` and `/Off` pointing to a complete XObject).

I'd gladly implement a fix given a pointer in the right direction.

**Comment by u-fischer** [comment]
I can look into it but only if you provide a small, complete example that demonstrates the issue.

**Comment by wherget** [comment]
I managed to reproduce a XeLaTeX variant (using dvipdfmx `\special`s, no idea how to translate that into `pdfescape`...)

### Steps to Reproduce:

1. Build example file below using `latexmk -xelatex file.tex`
2. Open created `file.pdf` in Chromium or Google Chrome
3. Click first checkbox
4. Click second checkbox

### Expected Result:

Both checkboxes look the same.

### Actual Result:

First checkbox has no checkmark, second checkbox has a checkmark.

### Code to reproduce

```latex
%! latexmk -xelatex
\documentclass{article}

\usepackage{hyperref}

\begin{document}
\begin{Form}

\CheckBox[name=broken]{Can you see the Checkmark?}

%%% now, to manually recreate something that approximately works...

% copied from hyperref.dtx, changed the /AP definition
\makeatletter
\def\PDFForm@Check{%
  /Subtype/Widget%
  \Fld@annotflags
  \Fld@pageobjref
  \Fld@annotnames
  /FT/Btn%
  \Fld@flags
  /Q \Fld@align
  /BS<</W \Fld@borderwidth /S/\Fld@borderstyle>>%
  /AP<< /N <</Yes @on-stream /Off @off-stream >> >>  % see references below
  /MK<<%
    \ifnum\Fld@rotation=\z@
    \else
      /R \Fld@rotation
    \fi
    \ifx\Fld@bordercolor\relax
    \else
      /BC[\Fld@bordercolor]%
    \fi
    \ifx\Fld@bcolor\relax
    \else
      /BG[\Fld@bcolor]%
    \fi
    /CA(\Hy@escapestring{\Fld@cbsymbol})%
  >>%
  /DA(/ZaDb \strip@pt\Fld@charsize\space Tf%
      \ifx\Fld@color\@empty\else\space\Fld@color\fi)%
  /H/P%
  \ifFld@checked /V/Yes/AS/Yes\else /V/Off/AS/Off\fi
  \Fld@additionalactions
}
\makeatother

% checkmark stream borrowed from working file
% (this should probably instead be drawing a /ZaDb glyph, but I don't speak enough PDF to do that)
\special{pdf:stream @on-stream (q Q q 0 0 11.955 11.955 re W n /Cs1 cs 1 1 1 sc 0 0 11.955 11.955 re f 1.5
w /Cs2 CS 0 SC q 1 0 0 1 -279.94 -655.243 cm 281.7332 660.6227 m 284.1242
658.2317 l 290.1017 664.2092 l S Q 1 w /Cs1 CS 1 0 0 SC q 1 0 0 1 -279.94 -655.243
cm 279.94 655.243 11.955 11.955 re S Q Q) <<
  /BBox [
    0
    0
    11.955
    11.955
  ]
  /FormType 1
  /Resources <<  /ProcSet [ /PDF ] >>
  /Subtype /Form
  /Type /XObject
>>}
% and a very minimalistic do-nothing stream
\special{pdf:stream @off-stream (q Q) <<
  /BBox [
    0
    0
    0
    0
  ]
  /FormType 1
  /Resources <<  /ProcSet [ /PDF ] >>
  /Subtype /Form
  /Type /XObject
>>}

\CheckBox[name=ok]{Can you see the special Checkmark?}

\end{Form}
\end{document}
```

**Comment by u-fischer** [comment]
preflight doesn't complain but I agree that it looks wrong. I will look at it, but it will take some time. One has to decide if the /AP entry can/should be optional, and how the stream dictionaries should be created (it affects all drivers, not only xelatex).

**Comment by u-fischer** [comment]
A part of the new pdfmanagement code is a new implementation for form fields. This will in due time replace the current form field code. The checkbox module already exists and use correct appearances, and is correctly checked. So I'm closing this now.

~~~~
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress,pdfversion=2.0}
\documentclass[]{article}
\usepackage{l3pdffield-testphase}
\usepackage{hyperref}
\begin{document}
\Form[NeedAppearances=false] % NeedAppearances is deprecated in pdf 2.0, but changes the behaviour.
Test checkbox: 
\ExplSyntaxOn
\pdffield_checkbox:n{name=test,checked}\quad \pdffield_checkbox:n{name=test2,checked=false}\par
\ExplSyntaxOff
\end{document}
~~~~
